import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Copyright © 2025 Connor Angiel — RedByte OS Genesis
// Complexity warning banner for circuit size guardrails
import React from 'react';
import { useClassroomModeStore } from '../stores/classroomModeStore';
export const ComplexityBanner = ({ onDismiss }) => {
    const { nodeCount, isComplexityWarning, isComplexityBlocked, safeMode } = useClassroomModeStore();
    const [showDetails, setShowDetails] = React.useState(false);
    if (!isComplexityWarning && !isComplexityBlocked)
        return null;
    if (isComplexityBlocked) {
        return (_jsxs("div", { className: "bg-red-900 text-red-50 px-4 py-3 border-b border-red-700", "data-testid": "complexity-blocked-banner", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-lg", children: "\uD83D\uDED1" }), _jsxs("div", { children: [_jsxs("div", { className: "font-semibold text-sm", children: ["Circuit limit reached (", nodeCount, " nodes)"] }), _jsx("div", { className: "text-xs text-red-200 mt-0.5", children: "Simplify your circuit or reset workspace to continue." })] })] }), _jsx("div", { className: "flex items-center gap-2", children: _jsx("button", { onClick: () => setShowDetails(!showDetails), className: "px-3 py-1.5 bg-red-800 hover:bg-red-700 text-white rounded text-xs transition-all", "data-testid": "complexity-details-button", children: showDetails ? 'Hide Details' : 'Details' }) })] }), showDetails && (_jsxs("div", { className: "mt-3 pt-3 border-t border-red-700 text-xs text-red-100", children: [_jsxs("div", { children: [_jsx("strong", { children: "Node count:" }), " ", nodeCount, " / 20 (max)"] }), _jsx("div", { className: "mt-1 text-red-200", children: "Try: Remove some components, use simpler gates, or click \"Reset Workspace\" in the top bar." })] }))] }));
    }
    return (_jsxs("div", { className: "bg-orange-900 text-orange-50 px-4 py-3 border-b border-orange-700", "data-testid": "complexity-warning-banner", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-lg", children: "\u26A0\uFE0F" }), _jsxs("div", { children: [_jsxs("div", { className: "font-semibold text-sm", children: ["Circuit is getting complex (", nodeCount, " nodes)"] }), _jsxs("div", { className: "text-xs text-orange-200 mt-0.5", children: ["Switching to step mode to stay responsive. ", safeMode && 'Safe Mode is active.'] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [onDismiss && (_jsx("button", { onClick: onDismiss, className: "px-3 py-1.5 bg-orange-800 hover:bg-orange-700 text-white rounded text-xs transition-all", "data-testid": "complexity-dismiss-button", children: "Dismiss" })), _jsx("button", { onClick: () => setShowDetails(!showDetails), className: "px-3 py-1.5 bg-orange-800 hover:bg-orange-700 text-white rounded text-xs transition-all", "data-testid": "complexity-details-button", children: showDetails ? 'Hide Details' : 'Details' })] })] }), showDetails && (_jsxs("div", { className: "mt-3 pt-3 border-t border-orange-700 text-xs text-orange-100", children: [_jsxs("div", { children: [_jsx("strong", { children: "Node count:" }), " ", nodeCount, " / 15 (warning) / 20 (max)"] }), _jsxs("div", { className: "mt-1 text-orange-200", children: ["Step mode prevents simulation lag. You can still add up to ", 20 - nodeCount, " more nodes."] })] }))] }));
};
