import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Copyright © 2025 Connor Angiel — RedByte OS Genesis
// Use without permission prohibited.
// Licensed under the RedByte Proprietary License (RPL-1.0). See LICENSE.
import { useMemo } from 'react';
export const CompareView = ({ className = '', ioSnapshot, checks }) => {
    const stats = useMemo(() => {
        const total = checks.length;
        const passing = checks.filter(c => c.pass).length;
        const failing = total - passing;
        const percent = total > 0 ? Math.round((passing / total) * 100) : 0;
        return { total, passing, failing, percent };
    }, [checks]);
    if (!ioSnapshot && checks.length === 0) {
        return (_jsxs("div", { className: `flex flex-col items-center justify-center h-full text-gray-500 text-xs font-mono p-8 text-center ${className}`, children: [_jsx("div", { className: "mb-2 text-cyan-900 opacity-50 text-4xl", children: "\u21C4" }), _jsx("div", { children: "NO SIGNALS MAPPED" }), _jsx("div", { className: "text-[10px] mt-1 opacity-50", children: "Select a board to view signals" })] }));
    }
    return (_jsxs("div", { className: `flex flex-col h-full ${className}`, style: { background: '#05080a' }, children: [_jsxs("div", { className: "p-3 border-b border-[#1a2a3a] bg-[#081018]", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h2", { className: "text-xs font-bold text-gray-200 tracking-wider", children: "SIGNAL COMPARISON" }), _jsxs("div", { className: "text-[10px] font-mono text-gray-500", children: ["TICK: ", _jsx("span", { className: "text-cyan-400", children: ioSnapshot ? ioSnapshot.tick : '---' })] })] }), _jsxs("div", { className: "flex gap-2", children: [_jsxs("div", { className: "flex-1 bg-[#0a1520] border border-[#1a2a3a] rounded p-2 flex flex-col items-center", children: [_jsx("span", { className: "text-[9px] text-gray-500 font-bold uppercase tracking-wider", children: "Match" }), _jsxs("span", { className: "text-lg font-mono text-[#00ff88] font-bold", style: { textShadow: '0 0 10px rgba(0,255,136,0.3)' }, children: [stats.percent, "%"] })] }), _jsxs("div", { className: "flex-1 bg-[#0a1520] border border-[#1a2a3a] rounded p-2 flex flex-col items-center", children: [_jsx("span", { className: "text-[9px] text-gray-500 font-bold uppercase tracking-wider", children: "Check" }), _jsx("span", { className: "text-lg font-mono text-cyan-400 font-bold", children: stats.total })] }), _jsxs("div", { className: "flex-1 bg-[#0a1520] border border-[#1a2a3a] rounded p-2 flex flex-col items-center", children: [_jsx("span", { className: "text-[9px] text-gray-500 font-bold uppercase tracking-wider", children: "Fail" }), _jsx("span", { className: `text-lg font-mono font-bold ${stats.failing > 0 ? 'text-red-500' : 'text-gray-600'}`, style: stats.failing > 0 ? { textShadow: '0 0 10px rgba(255,0,0,0.3)' } : {}, children: stats.failing })] })] })] }), _jsxs("div", { className: "flex-1 overflow-auto custom-scrollbar", children: [_jsxs("table", { className: "w-full text-left border-collapse", children: [_jsx("thead", { className: "bg-[#0a1520] text-[10px] text-gray-500 sticky top-0 z-10 font-bold tracking-wider uppercase", children: _jsxs("tr", { children: [_jsx("th", { className: "p-2 border-b border-[#1a2a3a]", children: "Signal" }), _jsx("th", { className: "p-2 border-b border-[#1a2a3a] text-right", children: "Sim" }), _jsx("th", { className: "p-2 border-b border-[#1a2a3a] text-right", children: "HW" }), _jsx("th", { className: "p-2 border-b border-[#1a2a3a] text-center", children: "Stat" })] }) }), _jsx("tbody", { className: "text-xs font-mono divide-y divide-[#1a2a3a]", children: checks.map((check) => {
                                    const isMismatch = !check.pass;
                                    return (_jsxs("tr", { className: `transition-colors hover:bg-[#102030] ${isMismatch ? 'bg-[#2a1010] bg-opacity-30' : ''}`, children: [_jsx("td", { className: "p-2 text-cyan-300 font-semibold", children: check.signalName }), _jsx("td", { className: "p-2 text-right text-gray-400", children: check.expected }), _jsx("td", { className: "p-2 text-right text-gray-400", children: check.observed }), _jsx("td", { className: "p-2 text-center", children: isMismatch ? (_jsx("span", { className: "inline-block w-2 h-2 rounded-full bg-red-500 shadow-[0_0_8px_rgba(255,0,0,0.8)]", title: "Mismatch" })) : (_jsx("span", { className: "inline-block w-1.5 h-1.5 rounded-full bg-[#00ff88] opacity-30", title: "Match" })) })] }, check.signalName));
                                }) })] }), (!ioSnapshot) && (_jsx("div", { className: "p-4 text-center text-[10px] text-orange-400 bg-orange-950/20 border-t border-orange-900/30", children: "\u26A0 Hardware not connected" }))] })] }));
};
