import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Copyright © 2025 Connor Angiel — RedByte OS Genesis
// Use without permission prohibited.
// Licensed under the RedByte Proprietary License (RPL-1.0). See LICENSE.
import React from 'react';
import { useHierarchyStore } from '../stores/hierarchyStore';
export const HierarchyBreadcrumbs = () => {
    const { stack, exitToParent, exitToTop, isEditMode, currentChip } = useHierarchyStore();
    // Don't show if we're at top level
    if (stack.length === 0)
        return null;
    const currentLevel = stack[stack.length - 1];
    return (_jsxs("div", { className: "flex items-center gap-2 px-3 py-2 bg-gradient-to-r from-purple-900/40 to-blue-900/40 border-b border-purple-600/50 shadow-lg", children: [_jsxs("div", { className: "flex items-center gap-2 bg-purple-800/50 px-3 py-1 rounded border border-purple-500/30", children: [_jsx("span", { className: "text-lg", children: "\uD83D\uDCE6" }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[10px] text-purple-300 uppercase tracking-wide", children: isEditMode ? 'Editing Chip' : 'Viewing Chip' }), _jsx("span", { className: "text-white font-bold text-sm", children: currentLevel.name })] }), _jsxs("span", { className: "text-purple-400 text-xs ml-2", children: ["L", stack.length] })] }), _jsxs("div", { className: "flex items-center gap-1 ml-4 text-xs flex-1", children: [_jsx("button", { onClick: exitToTop, className: "px-2 py-1 hover:bg-purple-700/50 rounded text-purple-200 transition-colors", title: "Return to top level", children: "\uD83C\uDFE0 Top" }), stack.map((level, i) => (_jsxs(React.Fragment, { children: [_jsx("span", { className: "text-purple-500", children: "\u203A" }), _jsx("span", { className: "text-purple-300", children: level.name })] }, i)))] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: exitToParent, className: "px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded text-white font-semibold transition-colors flex items-center gap-1", title: "Back to parent (Esc)", children: "\u2190 Back" }), _jsx("button", { onClick: exitToTop, className: "px-3 py-1 bg-blue-700 hover:bg-blue-600 rounded text-white font-semibold transition-colors", title: "Exit to top level", children: "Exit All" })] }), !isEditMode && (_jsx("div", { className: "text-xs text-purple-300 italic", children: "Read-only \u2022 Press 'E' to edit" })), currentChip && (_jsxs("div", { className: "flex items-center gap-2 text-xs border-l border-purple-600/50 pl-3", children: [_jsx("span", { className: "text-purple-400", children: "I/O:" }), _jsxs("span", { className: "text-green-400", children: [currentChip.inputs.length, " in"] }), _jsxs("span", { className: "text-orange-400", children: [currentChip.outputs.length, " out"] })] }))] }));
};
