import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
// Copyright © 2025 Connor Angiel — RedByte OS Genesis
// Use without permission prohibited.
// Licensed under the RedByte Proprietary License (RPL-1.0). See LICENSE.
import React from 'react';
import { useClassroomModeStore } from '../stores/classroomModeStore';
import { Tooltip, Menu } from '@redbyte/rb-primitives';
export const TopCommandBar = ({ projectName, onNew, onNewProject, onSaveProject, onOpenProject, onExportProject, onSave, onSaveAs, onExamples, onShare, isDirty = false, onUndo, onRedo, canUndo = false, canRedo = false, isRunning, onRun, onPause, onStep, onReset, tickCount, tickRate, onTickRateChange, onResetTickCount, perspective, onPerspectiveChange, schematicMiniEnabled, onToggleSchematicMini, onHelp, onStartHere, onManual, onExportEvidence, onOpenEvidence, onResetWorkspace, onResetLayout, }) => {
    const { safeMode, setSafeMode, isComplexityWarning } = useClassroomModeStore();
    const [showResetMenu, setShowResetMenu] = React.useState(false);
    const handleSafeModeToggle = () => {
        setSafeMode(!safeMode);
    };
    const handleResetWorkspace = () => {
        if (onResetWorkspace) {
            onResetWorkspace();
        }
        else {
            if (confirm('Clear all circuits and reset to blank workspace?')) {
                localStorage.removeItem('rb_circuit');
                localStorage.removeItem('rb_layout');
                window.location.reload();
            }
        }
        setShowResetMenu(false);
    };
    const handleResetLayout = () => {
        if (onResetLayout) {
            onResetLayout();
        }
        else {
            localStorage.removeItem('rb_layout');
            window.location.reload();
        }
        setShowResetMenu(false);
    };
    // PHASE 2C: Mount breadcrumb
    if (import.meta.env.DEV || (typeof navigator !== 'undefined' && navigator.webdriver)) {
        if (typeof window !== 'undefined' && window.__RB_MOUNT_TRACE__) {
            const timestamp = typeof performance !== 'undefined' ? performance.now().toFixed(1) : Date.now();
            window.__RB_MOUNT_TRACE__.push(`${timestamp} TopCommandBar:render`);
        }
    }
    return (_jsxs("div", { className: "min-h-[48px] border-b border-slate-700 bg-slate-900 px-4 py-2 flex flex-wrap items-center justify-between gap-4 sticky top-0 left-0 right-0 z-[100]", style: { position: 'sticky', top: 0, left: 0, right: 0, zIndex: 100 }, "data-testid": "top-command-bar", role: "toolbar", "aria-label": "Main Toolbar", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2 min-w-0", children: [_jsx("span", { className: "text-xs text-gray-500 uppercase tracking-wide mr-2", children: "Project" }), projectName && (_jsxs("div", { className: "text-xs text-slate-300 font-medium px-2 py-1 bg-slate-800/60 border border-slate-700/60 rounded", children: [projectName, isDirty ? _jsx("span", { className: "ml-1 text-cyan-400", children: "*" }) : null] })), onNewProject && (_jsx("button", { onClick: onNewProject, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "New Project", children: "New Project" })), onOpenProject && (_jsx("button", { onClick: onOpenProject, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "Open Project", children: "Open Project" })), onSaveProject && (_jsx("button", { onClick: onSaveProject, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "Save Project", children: "Save Project" })), onExportProject && (_jsx("button", { onClick: onExportProject, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "Export Project Artifacts", children: "Export..." })), onNew && (_jsx("button", { onClick: onNew, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "New Circuit", children: "New Circuit" })), onExamples && (_jsx("button", { onClick: onExamples, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "Load Example", "data-testid": "logic-playground-examples", children: "\uD83D\uDCDA Examples" })), onExportEvidence && (_jsx("button", { onClick: onExportEvidence, className: "px-3 py-1.5 text-sm bg-purple-700 hover:bg-purple-600 rounded transition-colors", title: "Export evidence for grading \u2013 includes circuit snapshot, probes, and integrity hash.", "data-testid": "export-evidence-button", children: "\uD83D\uDCCB Export Lab Evidence" })), onOpenEvidence && (_jsx("button", { onClick: onOpenEvidence, className: "px-3 py-1.5 text-sm bg-emerald-700 hover:bg-emerald-600 rounded transition-colors", title: "Open Lab Evidence (checks integrity hash - look for PASS badge)", "data-testid": "open-evidence-button", children: "\uD83D\uDDC2\uFE0F Open Lab Evidence\u2026" })), onSave && (_jsx("button", { onClick: onSave, className: `px-3 py-1.5 text-sm rounded transition-all ${isDirty
                            ? 'bg-cyan-600 hover:bg-cyan-500 shadow-lg shadow-cyan-600/30'
                            : 'bg-slate-800 hover:bg-slate-700'}`, title: "Save (Ctrl+S)", children: isDirty ? '● Save' : 'Save' })), onSaveAs && (_jsx("button", { onClick: onSaveAs, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "Save As", children: "Save As" })), onShare && (_jsx("button", { onClick: onShare, className: "px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 rounded transition-colors", title: "Share via link", children: "Share" })), onUndo && (_jsx("button", { onClick: onUndo, disabled: !canUndo, className: `px-2 py-1.5 text-sm rounded transition-colors ${canUndo
                            ? 'bg-gray-800 hover:bg-gray-700 text-white'
                            : 'bg-gray-800/50 text-gray-600 cursor-not-allowed'}`, title: "Undo (Ctrl+Z)", children: "\u21B6" })), onRedo && (_jsx("button", { onClick: onRedo, disabled: !canRedo, className: `px-2 py-1.5 text-sm rounded transition-colors ${canRedo
                            ? 'bg-gray-800 hover:bg-gray-700 text-white'
                            : 'bg-gray-800/50 text-gray-600 cursor-not-allowed'}`, title: "Redo (Ctrl+Shift+Z)", children: "\u21B7" }))] }), _jsxs("div", { className: "flex flex-wrap items-center gap-3 bg-gray-800/50 rounded-lg px-4 py-1.5 border border-gray-700/50 min-w-0", children: [_jsx("span", { className: "text-xs text-gray-500 uppercase tracking-wide mr-1", children: "Simulate" }), _jsxs("button", { onClick: () => onStep(1), "data-testid": "logic-playground-step", className: "px-5 py-2 bg-blue-600 hover:bg-blue-500 rounded font-semibold text-sm transition-all shadow-lg flex items-center gap-2", title: "Step Once (Space)", children: [_jsx("span", { className: "text-lg", children: "\u23ED" }), _jsx("span", { children: "Step" })] }), _jsx("button", { onClick: isRunning ? onPause : onRun, "data-testid": "logic-playground-run", className: `px-4 py-2 rounded font-medium text-sm transition-all flex items-center gap-2 ${isRunning
                            ? 'bg-yellow-600 hover:bg-yellow-500 shadow-lg'
                            : 'bg-green-600 hover:bg-green-500 shadow-lg'}`, title: isRunning ? 'Pause' : 'Run', children: isRunning ? (_jsxs(_Fragment, { children: [_jsx("span", { className: "text-lg", children: "\u23F8" }), _jsx("span", { children: "Pause" })] })) : (_jsxs(_Fragment, { children: [_jsx("span", { className: "text-lg", children: "\u25B6" }), _jsx("span", { children: "Run" })] })) }), _jsxs("div", { className: "flex items-center gap-2 ml-2 border-l border-gray-700 pl-3", children: [_jsx("input", { type: "range", min: "1", max: "60", value: tickRate, onChange: (e) => onTickRateChange(parseInt(e.target.value, 10)), className: "w-20 h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer", "aria-label": "Tick rate", title: "Tick rate" }), _jsxs("span", { className: "text-sm font-mono text-cyan-400 w-11 text-right", children: [tickRate, "Hz"] })] }), _jsxs("div", { className: "flex items-center gap-3 border-l border-gray-700 pl-3 text-xs text-gray-300", children: [_jsxs("div", { className: "flex flex-col leading-tight", children: [_jsx("span", { className: "text-[10px] uppercase tracking-wide text-gray-500", children: "Clock" }), _jsxs("div", { className: "flex items-center gap-2 font-mono", children: [_jsxs("span", { className: "text-cyan-300", title: "A tick is one discrete simulation step.", children: ["T+", tickCount] }), _jsxs("span", { className: "flex items-center gap-1 text-[10px] text-gray-400", children: [_jsx("span", { className: `h-2 w-2 rounded-full ${isRunning ? 'bg-green-400' : 'bg-gray-500'}` }), isRunning ? `${tickRate}Hz` : 'Paused'] })] })] }), onResetTickCount && (_jsx("button", { onClick: onResetTickCount, className: "px-2 py-1 rounded bg-gray-800 hover:bg-gray-700 text-[10px] uppercase tracking-wide text-gray-300", title: "Reset tick counter", children: "Reset" }))] }), onReset && (_jsx("button", { onClick: onReset, className: "px-2 py-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors", title: "Reset Circuit", children: _jsx("span", { className: "text-lg", children: "\u21BA" }) }))] }), _jsxs("div", { className: "flex items-center gap-2 min-w-0", children: [_jsxs("div", { className: "hidden xl:flex items-center gap-2", children: [_jsx("span", { className: "text-xs text-gray-500 uppercase tracking-wide mr-1", children: "Layout" }), _jsxs("div", { className: "flex bg-slate-800/50 rounded-lg p-0.5 border border-slate-700/50", children: [_jsx(Tooltip, { content: "Standard View", children: _jsx("button", { onClick: () => onPerspectiveChange('standard'), className: `px-3 py-1.5 text-xs font-medium rounded transition-colors ${perspective === 'standard'
                                                ? 'bg-slate-700 text-cyan-400 shadow-sm'
                                                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-700/50'}`, children: "Editor" }) }), _jsx(Tooltip, { content: "Split View (Circuit + Scope)", children: _jsx("button", { onClick: () => onPerspectiveChange('split'), className: `px-3 py-1.5 text-xs font-medium rounded transition-colors ${perspective === 'split'
                                                ? 'bg-slate-700 text-cyan-400 shadow-sm'
                                                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-700/50'}`, children: "Split" }) })] }), _jsxs("button", { onClick: handleSafeModeToggle, className: `px-3 py-1.5 rounded text-xs font-semibold transition-all ${safeMode
                                    ? 'bg-green-700 hover:bg-green-600 text-white'
                                    : 'bg-gray-700 hover:bg-gray-600 text-gray-300'}`, title: "Toggle Safe Mode (disables 3D, quad, animations)", children: ["\uD83D\uDEE1 ", safeMode ? 'Safe' : 'Normal'] }), _jsxs("div", { className: "relative", children: [_jsx("button", { onClick: () => setShowResetMenu(!showResetMenu), className: "px-3 py-1.5 rounded text-xs font-semibold bg-gray-700 hover:bg-gray-600 text-gray-300 transition-all", title: "Reset workspace or layout", children: "\u21BB" }), showResetMenu && (_jsxs("div", { className: "absolute right-0 mt-1 w-48 bg-gray-800 border border-gray-700 rounded shadow-lg z-50", children: [_jsx("button", { onClick: handleResetWorkspace, className: "block w-full text-left px-4 py-2 text-xs text-gray-300 hover:bg-gray-700 hover:text-white transition-all", children: "Reset Workspace" }), _jsx("button", { onClick: handleResetLayout, className: "block w-full text-left px-4 py-2 text-xs text-gray-300 hover:bg-gray-700 hover:text-white border-t border-gray-700 transition-all", children: "Reset Layout" })] }))] }), onManual && (_jsx("button", { onClick: onManual, className: "px-3 py-2 bg-slate-800 hover:bg-slate-700 rounded text-xs font-semibold transition-all", title: "Open Guide", children: "Guide" })), _jsx("button", { onClick: onHelp, className: "px-3 py-2 bg-purple-700 hover:bg-purple-600 rounded font-bold transition-all text-sm", title: "Help (?)", children: "?" })] }), _jsx("div", { className: "xl:hidden", children: _jsxs(Menu, { label: "Layout & Help", align: "right", children: [_jsx(Menu.Item, { onClick: () => onPerspectiveChange('standard'), children: "Editor View" }), _jsx(Menu.Item, { onClick: () => onPerspectiveChange('split'), children: "Split View" }), _jsx(Menu.Separator, {}), _jsx(Menu.Item, { onClick: handleSafeModeToggle, children: safeMode ? 'Disable Safe Mode' : 'Enable Safe Mode' }), _jsx(Menu.Item, { onClick: handleResetLayout, children: "Reset Layout" }), _jsx(Menu.Separator, {}), _jsx(Menu.Item, { onClick: onHelp, children: "Shortcuts" }), onManual && _jsx(Menu.Item, { onClick: onManual, children: "Documentation" }), onExamples && _jsx(Menu.Item, { onClick: onExamples, children: "Examples" })] }) })] })] }));
};
