import React, { useMemo, useState, useEffect } from 'react';
import { deriveProjectVerifyState, type ProjectHealth } from '../projectHealth';
import { IdeSurfaceLayout } from '../components/IdeSurfaceLayout';
import {
  IdeButton,
  IdeCallout,
  IdeDataTable,
  IdeInspectorSection,
  IdePanel,
  IdeStatusPill,
} from '../components/IdePrimitives';
import { SurfacePanel } from '../components/SurfaceLayoutPrimitives';
import type { RuntimeSimState, RuntimeVerifyRun } from '../projectRuntime';
import { computeScenarioContentHash, type VerifyScenario } from '../verifyScenario';
import { useIoBus } from '../ioBus';
import { HardwareBoard2D } from '../components/HardwareBoard2D';
import { Basys3BoardView } from '../components/Basys3BoardView';
import { useBoardSignal } from '../BoardSignalContext';
import { getIoSignalLookupKeys, getStudentFacingIoLabel, normalizeIoSignalKey } from '../ioLabels';
import type { IoSignalRole } from '../ioSignalRoles';

export interface HardwareMappingRow {
  id: string;
  nodeId?: string;
  label: string;
  direction: 'in' | 'out';
  pin: string;
  required: boolean;
}

export interface HardwareSurfaceProps {
  projectName: string;
  expectedBehavior: string;
  mappingRows: HardwareMappingRow[];
  expectedIoRows: Array<{
    signal: string;
    tick: number;
    expected: string;
  }>;
  vectorsCount: number;
  health: ProjectHealth;
  verifyCurrent: boolean;
  exportCurrent: boolean;
  runtimeSim?: RuntimeSimState;
  onSimSetInput?: (nodeId: string, v: 0 | 1) => void;
  onGenerateBringUpVectors: () => void;
  onOpenExport: () => void;
  onOpenVerify: () => void;
  onGoToDesign?: () => void;
  onSetMappingPin?: (rowId: string, alias: string) => void;
  signalRoles?: Record<string, IoSignalRole>;
  /** Last completed verify run — provides scenario/run provenance for the board view. */
  verifyLastRun?: RuntimeVerifyRun;
  /** Currently active scenario — compared to verifyLastRun to detect drift. */
  activeScenario?: VerifyScenario;
  /** Full scenario library — used to check if switch-back CTA target still exists. */
  scenarios?: VerifyScenario[];
  /** True when the active scenario uses auto-generated (starter) vectors. */
  vectorsAreAutoGenerated?: boolean;
  /** Switch the active scenario by ID — used for switch-back CTA. */
  onSwitchScenario?: (scenarioId: string) => void;
}

/** Convert a raw signal key like "ld[5]" or "sw3" into a human label like "LED LD5" / "Switch SW3". */
export function signalHumanLabel(signal: string): string {
  const ldMatch = signal.match(/ld\[?(\d+)\]?/i);
  if (ldMatch) return `LED LD${ldMatch[1]}`;
  const swMatch = signal.match(/sw\[?(\d+)\]?/i);
  if (swMatch) return `Switch SW${swMatch[1]}`;
  const btnMatch = signal.match(/btn([cudlr])/i);
  if (btnMatch) return `Button BTN${btnMatch[1].toUpperCase()}`;
  return signal.toUpperCase();
}

/** Format a single assertion entry as a plain student-readable sentence. */
export function formatAssertionPlain(a: {
  tick: number;
  signal: string;
  expected: string;
  actual: string | null;
  pass: boolean;
  hasData: boolean;
}): string {
  const sigLabel = signalHumanLabel(a.signal);
  const expectedWord = a.expected === '1' ? 'ON' : 'OFF';
  if (!a.hasData) {
    return `${sigLabel} could not be read at step ${a.tick} — no trace data available.`;
  }
  if (a.pass) {
    return `${sigLabel} is ${expectedWord} at step ${a.tick}.`;
  }
  const actualWord = a.actual === '1' ? 'ON' : 'OFF';
  return `${sigLabel} should be ${expectedWord} at step ${a.tick}, but it stayed ${actualWord}.`;
}

const HARDWARE_EMPTY_SIM: RuntimeSimState = {
  tick: 0, running: false, stepMode: false, speedHz: 1, irHash: '', traceHash: '',
  inputs: {}, signals: {}, trace: [], selectedSignalKey: null, probes: [],
};

interface AssertionEntry {
  tick: number;
  signal: string;
  expected: string;
  actual: string | null; // null = no trace data for this tick
  pass: boolean;
  hasData: boolean;
}

type HwMode = 'live' | 'bringup' | 'proof' | 'map';

export const HardwareSurface: React.FC<HardwareSurfaceProps> = ({
  projectName,
  expectedBehavior,
  mappingRows,
  expectedIoRows,
  vectorsCount,
  health,
  verifyCurrent,
  exportCurrent,
  runtimeSim,
  onSimSetInput,
  onGenerateBringUpVectors,
  onOpenExport,
  onOpenVerify,
  onGoToDesign,
  onSetMappingPin,
  signalRoles,
  verifyLastRun,
  activeScenario,
  scenarios = [],
  vectorsAreAutoGenerated = false,
  onSwitchScenario,
}) => {
  const { activeBoardSignal, hoverBoardSignal, setActiveBoardSignal, setHoverBoardSignal } = useBoardSignal();
  const [hwMode, setHwMode] = useState<HwMode>('live');
  const [bringupStepIndex, setBringupStepIndex] = useState(0);
  const [selectedMappingRowId, setSelectedMappingRowId] = useState<string | null>(null);
  const sim = runtimeSim ?? HARDWARE_EMPTY_SIM;

  const clockRoleKeys = useMemo(() => {
    const next = new Set<string>();
    const roleSource = Object.keys(signalRoles ?? {}).length > 0
      ? signalRoles ?? {}
      : verifyLastRun?.report.signalRoles ?? {};
    for (const [key, role] of Object.entries(roleSource)) {
      if (role === 'clock') {
        const normalized = normalizeIoSignalKey(key);
        if (normalized) next.add(normalized);
      }
    }
    return next;
  }, [signalRoles, verifyLastRun?.reportHash]);

  // Prefer semantic verify roles for clock detection; fall back only when no role map exists yet.
  const hasClockMapping = useMemo(
    () => {
      const requiredClockRows = mappingRows.filter(
        (row) => {
          if (row.direction !== 'in' || !row.required) return false;

          if (clockRoleKeys.size > 0) {
            return getIoSignalLookupKeys(row, mappingRows).some((key) => clockRoleKeys.has(key));
          }

          return /(^clk$|clock|clk100mhz)/i.test(getStudentFacingIoLabel(row));
        }
      );
      return requiredClockRows.length > 0 && requiredClockRows.every((row) => row.pin.trim().length > 0);
    },
    [clockRoleKeys, mappingRows]
  );
  const hasOutputMapping = useMemo(
    () => {
      const requiredOutputs = mappingRows.filter(
        (row) => row.direction === 'out' && row.required
      );
      return requiredOutputs.length > 0 && requiredOutputs.every((row) => row.pin.trim().length > 0);
    },
    [mappingRows]
  );

  const SSD_PINS = /^(CA|CB|CC|CD|CE|CF|CG|DP|AN[0-3])$/i;
  const hasSsdMapping = useMemo(
    () => mappingRows.some((row) => SSD_PINS.test(getStudentFacingIoLabel(row))),
    [mappingRows]
  );

  const hasButtonMapping = useMemo(
    () =>
      mappingRows.some(
        (row) => row.direction === 'in' && /^btn(c|u|d|l|r)/i.test(getStudentFacingIoLabel(row))
      ),
    [mappingRows]
  );

  // ── Map mode: all aliases currently assigned to rows ──────────────────
  const mapModeAliases = useMemo(() => {
    const s = new Set<string>();
    for (const row of mappingRows) {
      const pin = row.pin.trim().toUpperCase();
      if (pin) s.add(pin);
    }
    return s;
  }, [mappingRows]);

  // ── Map mode: highlight the current pin of the selected row ───────────
  const selectedMappingRowPin = useMemo(() => {
    if (!selectedMappingRowId) return null;
    const row = mappingRows.find((r) => r.id === selectedMappingRowId);
    return row?.pin?.trim().toUpperCase() || null;
  }, [selectedMappingRowId, mappingRows]);

  // ── Map mode: group rows by signal type for the assignment table ───────
  const mapModeGroups = useMemo(() => {
    const groups: Array<{ label: string; rows: HardwareMappingRow[] }> = [
      { label: 'Clock', rows: [] },
      { label: 'Switches', rows: [] },
      { label: 'Buttons', rows: [] },
      { label: 'LEDs', rows: [] },
      { label: '7-Segment', rows: [] },
      { label: 'Other', rows: [] },
    ];
    for (const row of mappingRows) {
      const pin = row.pin.trim().toUpperCase();
      const lbl = getStudentFacingIoLabel(row).toUpperCase();
      if (getIoSignalLookupKeys(row, mappingRows).some((key) => clockRoleKeys.has(key))) {
        groups[0].rows.push(row);
      } else if (/CLK|W5/.test(pin) || /CLK|CLOCK/.test(lbl)) {
        groups[0].rows.push(row);
      } else if (/^SW\d/.test(pin) || /^SW\d/.test(lbl)) {
        groups[1].rows.push(row);
      } else if (/^BTN/.test(pin) || /^BTN/.test(lbl)) {
        groups[2].rows.push(row);
      } else if (/^LD\d/.test(pin) || /^LD\d/.test(lbl)) {
        groups[3].rows.push(row);
      } else if (/^(CA|CB|CC|CD|CE|CF|CG|DP|AN\d)/.test(pin) || /^(CA|CB|CC|CD|CE|CF|CG|DP|AN\d)/.test(lbl)) {
        groups[4].rows.push(row);
      } else {
        groups[5].rows.push(row);
      }
    }
    return groups.filter((g) => g.rows.length > 0);
  }, [clockRoleKeys, mappingRows]);

  const [debounceDismissed, setDebounceDismissed] = useState(() => {
    try { return localStorage.getItem('rb-debounce-tip-dismissed') === '1'; } catch { return false; }
  });
  useEffect(() => {
    if (debounceDismissed) {
      try { localStorage.setItem('rb-debounce-tip-dismissed', '1'); } catch { /* ignore */ }
    }
  }, [debounceDismissed]);

  const ioBusIoRows = useMemo(
    () =>
      mappingRows
        .filter((r): r is HardwareMappingRow & { nodeId: string } => Boolean(r.nodeId))
        .map((r) => ({
          nodeId: r.nodeId,
          label: getStudentFacingIoLabel(r, r.id),
          direction: r.direction,
        })),
    [mappingRows]
  );
  const ioBus = useIoBus({
    ioRows: ioBusIoRows,
    runtimeSim: sim,
    setInput: onSimSetInput ?? (() => {}),
  });
  const mappedSw = useMemo(
    () => Array.from({ length: 16 }, (_, i) => ioBus.meta.swNodeIds[i] != null),
    [ioBus.meta.swNodeIds]
  );
  const mappedLd = useMemo(
    () => Array.from({ length: 16 }, (_, i) => ioBus.meta.ldNodeIds[i] != null),
    [ioBus.meta.ldNodeIds]
  );
  const effectiveBoardSignal = hoverBoardSignal ?? activeBoardSignal;

  const projectVerifyState = useMemo(() => {
    if (!verifyCurrent) return health.lastVerify ? 'stale' : 'not-run';
    return deriveProjectVerifyState({ ...health, dirtySinceVerify: false });
  }, [health, verifyCurrent]);
  const compareCurrent =
    projectVerifyState === 'assertions-match' ||
    projectVerifyState === 'assertions-differ' ||
    projectVerifyState === 'verify-error';
  const compareMatches = projectVerifyState === 'assertions-match';
  const compareDiffers =
    projectVerifyState === 'assertions-differ' || projectVerifyState === 'verify-error';
  const compareTraceOnly = projectVerifyState === 'trace';
  const exportReady = health.lastExport?.status === 'ok' && exportCurrent;

  // ── Scenario drift detection ─────────────────────────────────────────
  // Two distinct drift kinds produce different copy and CTAs.
  /** Active scenario differs from the one that produced the verify run. */
  const isDifferentScenario = Boolean(
    verifyLastRun && activeScenario && verifyLastRun.scenarioId !== activeScenario.id
  );
  /** Same scenario, but its content changed after the run (hash drift). */
  const isSameScenarioEdited = Boolean(
    verifyLastRun && activeScenario &&
    verifyLastRun.scenarioId === activeScenario.id &&
    typeof verifyLastRun.scenarioContentHash === 'string' &&
    verifyLastRun.scenarioContentHash !== computeScenarioContentHash(activeScenario)
  );
  const scenarioDrifted = isDifferentScenario || isSameScenarioEdited;

  /** The scenario the last run was for, if it still exists in the library (enables switch-back CTA). */
  const switchBackScenario = useMemo(
    () =>
      isDifferentScenario && verifyLastRun
        ? (scenarios.find((s) => s.id === verifyLastRun.scenarioId) ?? null)
        : null,
    [isDifferentScenario, scenarios, verifyLastRun]
  );
  const effectiveBlockingIssues = useMemo(
    () =>
      health.blockingIssues.filter((issue) => {
        if (issue.code === 'RBP1004' && verifyCurrent) return false;
        if (issue.code === 'RBP2002' && exportCurrent) return false;
        return true;
      }),
    [exportCurrent, health.blockingIssues, verifyCurrent]
  );
  const hardwareState = exportReady
    ? 'ready'
    : health.lastExport?.status === 'ok'
      ? 'export-stale'
      : 'export-needed';
  const hasBlocking = effectiveBlockingIssues.length > 0 || hardwareState !== 'ready';

  // ── Verify status for callout ────────────────────────────────────────
  const verifyStatus = !health.lastVerify
    ? 'NOT RUN'
    : compareTraceOnly
      ? 'TRACE ONLY'
    : compareDiffers
      ? 'ASSERTIONS DIFFER'
      : compareMatches
        ? 'ASSERTIONS MATCH'
        : compareCurrent
          ? 'SIMULATION CURRENT'
          : 'STALE';
  const exportStatus = health.lastExport?.status === 'ok'
    ? exportReady
      ? 'CURRENT'
      : 'STALE'
    : health.lastExport?.status === 'blocked'
      ? 'BLOCKED'
      : 'MISSING';
  const readinessCallout = useMemo(() => {
    if (hardwareState === 'export-stale') {
      return {
        tone: 'warn' as const,
        title: 'Re-export required',
        message:
          'The hardware bundle was built from an older version. Re-export from Export, then return here to program the board.',
      };
    }
    if (hardwareState === 'export-needed') {
      return {
        tone: 'warn' as const,
        title: 'Export required',
        message:
          effectiveBlockingIssues[0]?.message ??
          'Build the hardware bundle in Export, then return here to program the board.',
      };
    }
    return {
      tone: 'success' as const,
      title: 'Ready for hardware',
      message: compareDiffers
        ? 'Programming is available. Assertions differ from observed outputs, so review the comparison before relying on behavior.'
        : 'Programming is available for this project state.',
    };
  }, [compareDiffers, effectiveBlockingIssues, hardwareState]);
  const blockedHero = useMemo(() => {
    if (!hasBlocking) return null;
    return {
      title: hardwareState === 'export-stale' ? 'Re-export this project now' : 'Build the hardware bundle first',
      body:
        hardwareState === 'export-stale'
          ? 'Your circuit changed since the last bundle was built. Re-export from Export, then return here to program the board.'
          : 'Open Export, build the current bundle once, then return here to program the board.',
      primaryLabel: hardwareState === 'export-stale' ? 'Re-export Current Bundle' : 'Open Export',
      primaryAction: onOpenExport,
      primaryTestId: 'ide-hardware-blocked-primary',
    };
  }, [hasBlocking, hardwareState, onOpenExport]);

  // ── Bring-Up: group expectedIoRows by tick ──────────────────────────
  const bringupTickGroups = useMemo(() => {
    const map = new Map<number, Array<{ signal: string; expected: string }>>();
    for (const row of expectedIoRows) {
      const bucket = map.get(row.tick) ?? [];
      bucket.push({ signal: row.signal, expected: row.expected });
      map.set(row.tick, bucket);
    }
    return Array.from(map.entries()).sort(([a], [b]) => a - b);
  }, [expectedIoRows]);

  // ── Bring-Up: compare current step expected vs actual LD values ─────
  const mismatchedLd = useMemo<boolean[]>(() => {
    if (hwMode !== 'bringup' || bringupTickGroups.length === 0)
      return Array(16).fill(false);
    const currentGroup = bringupTickGroups[bringupStepIndex];
    if (!currentGroup) return Array(16).fill(false);
    const [, signals] = currentGroup;
    return Array.from({ length: 16 }, (_, i) => {
      const sig = signals.find(
        (s) =>
          s.signal.toLowerCase() === `ld${i}` ||
          s.signal.toLowerCase() === `ld[${i}]`
      );
      if (!sig) return false;
      return sig.expected !== String(ioBus.state.ld[i]);
    });
  }, [hwMode, bringupTickGroups, bringupStepIndex, ioBus.state.ld]);

  const bringupStepPass = useMemo(
    () => mismatchedLd.every((v) => !v),
    [mismatchedLd]
  );

  // ── Bring-Up inspector: actual vs expected rows ─────────────────────
  const bringupStepRows = useMemo(() => {
    const group = bringupTickGroups[bringupStepIndex];
    if (!group) return [];
    const [, signals] = group;
    return signals.map((s) => {
      const ldMatch = s.signal.match(/ld\[?(\d+)\]?/i);
      const rawActual = ldMatch ? String(ioBus.state.ld[Number(ldMatch[1])] ?? '—') : '—';
      const pass = rawActual === s.expected;
      const expectedWord = s.expected === '1' ? 'ON' : 'OFF';
      const actualWord = rawActual === '—' ? '—' : rawActual === '1' ? 'ON' : 'OFF';
      return [
        signalHumanLabel(s.signal),
        expectedWord,
        actualWord,
        <IdeStatusPill key={`${s.signal}-pill`} tone={pass ? 'ok' : 'error'}>
          {pass ? 'MATCH' : 'DIFFER'}
        </IdeStatusPill>,
      ];
    });
  }, [bringupTickGroups, bringupStepIndex, ioBus.state.ld]);

  // ── Live: signal event log from sim trace ───────────────────────────
  const nodeKeyToMeta = useMemo(() => {
    const m = new Map<string, { label: string; direction: 'in' | 'out' }>();
    for (const r of ioBusIoRows) {
      const meta = { label: r.label, direction: r.direction };
      m.set(r.nodeId, meta);
      m.set(`${r.nodeId}.out`, meta);
      m.set(`${r.nodeId}.in`, meta);
    }
    return m;
  }, [ioBusIoRows]);

  interface SignalChangeEvent {
    tick: number;
    label: string;
    from: 0 | 1;
    to: 0 | 1;
    direction: 'in' | 'out';
  }

  const signalChangeFeed = useMemo<SignalChangeEvent[]>(() => {
    if (!sim.trace?.length) return [];
    const events: SignalChangeEvent[] = [];
    let prev: Record<string, 0 | 1> = {};
    for (const sample of sim.trace) {
      for (const [k, v] of Object.entries(sample.signals)) {
        const meta = nodeKeyToMeta.get(k);
        if (!meta) continue;
        const was = prev[k];
        if (was !== undefined && was !== v) {
          events.push({ tick: sample.tick, label: meta.label, from: was, to: v as 0 | 1, direction: meta.direction });
        }
      }
      Object.assign(prev, sample.signals);
    }
    return events.slice(-30).reverse();
  }, [sim.trace, nodeKeyToMeta]);

  // ── Assertions: trace × expected vectors ────────────────────────────
  const traceByTick = useMemo(() => {
    const map = new Map<number, Record<string, 0 | 1>>();
    for (const sample of sim.trace ?? []) {
      map.set(sample.tick, sample.signals);
    }
    return map;
  }, [sim.trace]);

  const hardwareAssertions = useMemo<AssertionEntry[]>(() => {
    return expectedIoRows.map((row) => {
      const ldMatch = row.signal.match(/ld\[?(\d+)\]?/i);
      if (!ldMatch) {
        return { tick: row.tick, signal: row.signal, expected: row.expected, actual: null, pass: false, hasData: false };
      }
      const ldIdx = Number(ldMatch[1]);
      const nodeId = ioBus.meta.ldNodeIds[ldIdx];
      if (!nodeId) {
        return { tick: row.tick, signal: row.signal, expected: row.expected, actual: null, pass: false, hasData: false };
      }
      const signals = traceByTick.get(row.tick);
      if (!signals) {
        return { tick: row.tick, signal: row.signal, expected: row.expected, actual: null, pass: false, hasData: false };
      }
      const rawVal = signals[nodeId] ?? signals[`${nodeId}.out`] ?? signals[`${nodeId}.in`];
      if (rawVal === undefined) {
        return { tick: row.tick, signal: row.signal, expected: row.expected, actual: null, pass: false, hasData: false };
      }
      const actual = String(rawVal);
      return { tick: row.tick, signal: row.signal, expected: row.expected, actual, pass: actual === row.expected, hasData: true };
    });
  }, [expectedIoRows, ioBus.meta.ldNodeIds, traceByTick]);

  const assertionsWithData = useMemo(() => hardwareAssertions.filter((a) => a.hasData), [hardwareAssertions]);
  const assertionFailCount = useMemo(() => assertionsWithData.filter((a) => !a.pass).length, [assertionsWithData]);
  const assertionPassCount = useMemo(() => assertionsWithData.filter((a) => a.pass).length, [assertionsWithData]);
  const hasAssertionData = assertionsWithData.length > 0;

  // ── Confidence score ─────────────────────────────────────────────────
  const confidenceChecks = useMemo(() => [
    { label: 'Clock mapped',        pass: hasClockMapping },
    { label: 'Outputs mapped',      pass: hasOutputMapping },
    { label: 'Vectors generated',   pass: vectorsCount > 0 },
    { label: 'Assertions match',    pass: hasAssertionData && assertionFailCount === 0 },
    { label: 'Compare current',     pass: compareCurrent && !scenarioDrifted },
    { label: 'Export current',      pass: exportReady },
  ], [hasClockMapping, hasOutputMapping, vectorsCount, hasAssertionData, assertionFailCount, compareCurrent, scenarioDrifted, exportReady]);

  const confidenceScore = useMemo(
    () => Math.round((confidenceChecks.filter((c) => c.pass).length / confidenceChecks.length) * 100),
    [confidenceChecks]
  );

  // ── Dock: Bring-Up step table (expected only, compact) ──────────────
  const bringupDockRows = useMemo(() => {
    const group = bringupTickGroups[bringupStepIndex];
    if (!group) return [];
    const [, signals] = group;
    return signals.map((s) => [
      signalHumanLabel(s.signal),
      s.expected === '1' ? 'ON' : 'OFF',
    ]);
  }, [bringupTickGroups, bringupStepIndex]);

  // ── Bring-Up: board highlights for current step ──────────────────────
  const currentStepHighlights = useMemo(() => {
    if (hwMode !== 'bringup' || bringupTickGroups.length === 0) {
      return { sw: [] as number[], ld: [] as number[] };
    }
    const [, signals] = bringupTickGroups[bringupStepIndex] ?? [null, []];
    const sw: number[] = [];
    const ld: number[] = [];
    for (const s of (signals ?? [])) {
      const swM = s.signal.match(/sw\[?(\d+)\]?/i);
      if (swM) sw.push(Number(swM[1]));
      const ldM = s.signal.match(/ld\[?(\d+)\]?/i);
      if (ldM) ld.push(Number(ldM[1]));
    }
    return { sw, ld };
  }, [hwMode, bringupTickGroups, bringupStepIndex]);

  const currentTick = bringupTickGroups[bringupStepIndex]?.[0];

  // ── Dock nodes ──────────────────────────────────────────────────────
  const liveDock = (
    <SurfacePanel className="ide-workbench-placeholder" testId="ide-hw-live-dock">
      <header className="ide-workbench-placeholder-header">
        <h3>Live Monitor</h3>
        <IdeStatusPill tone={sim.running ? 'ok' : 'warn'}>
          {sim.running ? 'Sim running' : 'Sim paused'}
        </IdeStatusPill>
      </header>
      <div className="ide-kv-list">
        <div className="ide-kv-row">
          <span>Sim tick</span>
          <code>{sim.tick}</code>
        </div>
        <div className="ide-kv-row">
          <span>Mapped I/O</span>
          <span>{ioBusIoRows.length}</span>
        </div>
        <div className="ide-kv-row">
          <span>Clock</span>
          <IdeStatusPill tone={hasClockMapping ? 'ok' : 'warn'}>
            {hasClockMapping ? 'Mapped' : 'Missing'}
          </IdeStatusPill>
        </div>
        <div className="ide-kv-row">
          <span>Outputs</span>
          <IdeStatusPill tone={hasOutputMapping ? 'ok' : 'warn'}>
            {hasOutputMapping ? 'Mapped' : 'Missing'}
          </IdeStatusPill>
        </div>
        <div className="ide-kv-row">
          <span>Vectors</span>
          <span>{vectorsCount}</span>
        </div>
      </div>
      <div className="ide-inline-actions">
        <IdeButton tone="secondary" onClick={onOpenVerify}>Run Verify</IdeButton>
        <IdeButton tone="ghost" onClick={onGenerateBringUpVectors}>Gen Vectors</IdeButton>
      </div>
      {onGoToDesign && (
        <div className="ide-hw-live-design-link">
          <IdeButton tone="ghost" onClick={onGoToDesign} testId="ide-hardware-go-design">
            Open in Design
          </IdeButton>
        </div>
      )}
    </SurfacePanel>
  );

  const bringupDock = (
    <SurfacePanel className="ide-workbench-placeholder" testId="ide-hw-bringup-dock">
      <header className="ide-workbench-placeholder-header">
        <h3>Bring-Up</h3>
        <IdeStatusPill
          tone={
            bringupTickGroups.length === 0
              ? 'warn'
              : bringupStepPass
                ? 'ok'
                : 'error'
          }
        >
          {bringupTickGroups.length === 0 ? 'No vectors' : bringupStepPass ? 'MATCH' : 'DIFFER'}
        </IdeStatusPill>
      </header>
      {hasAssertionData && (
        <div className="ide-hw-assert-summary" data-testid="ide-hw-assert-summary">
          <span className={assertionFailCount > 0 ? 'ide-hw-assert-fail-count' : 'ide-hw-assert-pass-count'}>
            {assertionFailCount > 0
              ? `${assertionFailCount} bring-up check${assertionFailCount > 1 ? 's' : ''} differed`
              : `${assertionPassCount} bring-up check${assertionPassCount === 1 ? '' : 's'} matched`}
          </span>
        </div>
      )}
      {bringupTickGroups.length === 0 ? (
        <IdeCallout tone="info" title="No bring-up vectors">
          <p className="ide-copy">Generate vectors first, then run the simulation.</p>
          <div className="ide-inline-actions">
            <IdeButton tone="primary" onClick={onGenerateBringUpVectors}
              testId="ide-hw-bringup-generate">
              Generate
            </IdeButton>
            <IdeButton tone="ghost" onClick={onOpenVerify}>Run Verify</IdeButton>
          </div>
        </IdeCallout>
      ) : (
        <div className="ide-hw-bringup-step" data-testid="ide-hw-bringup-step">
          <div className="ide-hw-step-header">
            <span className="ide-hw-step-counter">
              Step {bringupStepIndex + 1} of {bringupTickGroups.length}
            </span>
            {currentTick !== undefined && (
              <code className="ide-hw-step-tick">t{currentTick}</code>
            )}
          </div>
          {(() => {
            const swSignals = (bringupTickGroups[bringupStepIndex]?.[1] ?? []).filter(s => /sw/i.test(s.signal));
            if (swSignals.length === 0) return null;
            const instructions = swSignals.map(s => {
              const label = signalHumanLabel(s.signal);
              return s.expected === '1' ? `turn ${label} ON` : `turn ${label} OFF`;
            });
            const text = instructions.length === 1
              ? instructions[0].charAt(0).toUpperCase() + instructions[0].slice(1)
              : `${instructions.slice(0, -1).join(', ')}, then ${instructions[instructions.length - 1]}`;
            return (
              <p className="ide-hw-step-instruction" data-testid="ide-hw-step-instruction">
                {text}
              </p>
            );
          })()}
          <IdeDataTable
            columns={['Signal', 'Expected']}
            rows={bringupDockRows}
            testId="ide-hw-bringup-step-table"
          />
          <div className="ide-hw-step-nav">
            <IdeButton
              tone="ghost"
              onClick={() => setBringupStepIndex(Math.max(0, bringupStepIndex - 1))}
              disabled={bringupStepIndex === 0}
              testId="ide-hw-bringup-prev"
            >
              ← Prev
            </IdeButton>
            <IdeButton
              tone="ghost"
              onClick={() =>
                setBringupStepIndex(
                  Math.min(bringupTickGroups.length - 1, bringupStepIndex + 1)
                )
              }
              disabled={bringupStepIndex === bringupTickGroups.length - 1}
              testId="ide-hw-bringup-next"
            >
              Next →
            </IdeButton>
          </div>
        </div>
      )}
    </SurfacePanel>
  );

  const proofDock = (
    <SurfacePanel className="ide-workbench-placeholder" testId="ide-hw-proof-dock">
      <header className="ide-workbench-placeholder-header">
        <h3>Proof Bundle</h3>
        <IdeStatusPill tone={confidenceScore === 100 ? 'ok' : confidenceScore >= 60 ? 'warn' : 'error'}>
          {confidenceScore}%
        </IdeStatusPill>
      </header>
      <div className="ide-hw-confidence-list" data-testid="ide-hw-confidence-list">
        {confidenceChecks.map((check) => (
          <div key={check.label} className={`ide-hw-confidence-row ${check.pass ? 'is-pass' : 'is-pending'}`}>
            <span className="ide-hw-confidence-icon">{check.pass ? '✓' : '○'}</span>
            <span className="ide-hw-confidence-label">{check.label}</span>
          </div>
        ))}
      </div>
      <div className="ide-hw-cert-slab" data-testid="ide-hw-cert-slab">
        <div className="ide-hw-cert-row">
          <span className="ide-hw-cert-key">VERIFY</span>
          <code className="ide-hw-cert-val">{health.lastVerify?.hash?.slice(0, 16) ?? '—'}</code>
        </div>
        <div className="ide-hw-cert-row">
          <span className="ide-hw-cert-key">EXPORT</span>
          <code className="ide-hw-cert-val">{health.lastExport?.hash?.slice(0, 16) ?? '—'}</code>
        </div>
        <div className="ide-hw-cert-row">
          <span className="ide-hw-cert-key">ASSERT</span>
          <code className="ide-hw-cert-val">{hasAssertionData ? `${assertionPassCount}P ${assertionFailCount}F` : '—'}</code>
        </div>
        <div className="ide-hw-cert-row">
          <span className="ide-hw-cert-key">STATUS</span>
          <code className="ide-hw-cert-val">{verifyStatus}/{exportStatus}</code>
        </div>
        <div className="ide-hw-cert-row" data-testid="ide-hardware-cert-scenario">
          <span className="ide-hw-cert-key">SCENARIO</span>
          <code className={`ide-hw-cert-val ${scenarioDrifted ? 'ide-hw-cert-val--warn' : ''}`}>
            {verifyLastRun?.scenarioName ?? '—'}
            {scenarioDrifted ? ' [drift]' : ''}
          </code>
        </div>
      </div>
      <div className="ide-inline-actions">
        {exportReady ? (
          <IdeButton tone="primary" onClick={onOpenExport} testId="ide-hardware-build-export">
            Open Export Bundle
          </IdeButton>
        ) : (
          <IdeButton tone="primary" onClick={onOpenExport} testId="ide-hardware-build-export">
            {hardwareState === 'export-stale' ? 'Re-export Current Bundle' : 'Open Export'}
          </IdeButton>
        )}
      </div>
      {hardwareState === 'ready' && effectiveBlockingIssues.length === 0 && (
        <div className="ide-hw-program-handoff" data-testid="ide-hardware-program-handoff-cta">
          <p className="ide-copy">
            Open the <code>.bit</code> file in{' '}
            <strong>Vivado Hardware Manager</strong> and click{' '}
            <strong>Program Device</strong> to flash the Basys3.
          </p>
        </div>
      )}
    </SurfacePanel>
  );

  const activeDock =
    hwMode === 'live' ? liveDock : hwMode === 'bringup' ? bringupDock : proofDock;

  // ── Inspector nodes ─────────────────────────────────────────────────
  const liveInspector = (
    <IdeInspectorSection title="Signal Log" defaultOpen>
      {signalChangeFeed.length === 0 ? (
        <p className="ide-copy" data-testid="ide-hw-signal-log-empty">
          No trace data — run Verify to record signal transitions.
        </p>
      ) : (
        <div className="ide-hw-event-log" data-testid="ide-hw-signal-log">
          {signalChangeFeed.map((ev, i) => (
            <div key={i} className="ide-hw-event-row">
              <code className="ide-hw-event-tick">t{ev.tick}</code>
              <span className={`ide-hw-event-dir ${ev.direction === 'in' ? 'is-input' : 'is-output'}`}>
                {ev.direction === 'in' ? '▶' : '◀'}
              </span>
              <code className="ide-hw-event-label">{ev.label}</code>
              <span className="ide-hw-event-change">{ev.from}→{ev.to}</span>
            </div>
          ))}
        </div>
      )}
    </IdeInspectorSection>
  );

  const bringupInspector = (
    <>
      <IdeInspectorSection title="Step Result" defaultOpen>
        {bringupStepRows.length === 0 ? (
          <p className="ide-copy">No signals.</p>
        ) : (
          <IdeDataTable
            columns={['Output', 'Expected', 'Observed', '']}
            rows={bringupStepRows}
            testId="ide-hw-bringup-result-table"
          />
        )}
      </IdeInspectorSection>
      <IdeInspectorSection title="Bring-Up Results" defaultOpen>
        {!hasAssertionData ? null : (
          <div className="ide-hw-assert-log" data-testid="ide-hw-assert-log">
            {hardwareAssertions.filter(a => a.hasData && !a.pass).slice(0, 10).map((a, i) => (
              <div
                key={i}
                className="ide-hw-assert-plain-row"
                data-testid={`ide-hw-assert-plain-${a.tick}-${a.signal}`}
              >
                <span className="ide-hw-assert-plain-fail">
                  {formatAssertionPlain(a)}
                </span>
                <span className="ide-hw-assert-plain-action">
                  {`Check whether ${signalHumanLabel(a.signal)} is correctly mapped and connected to the circuit output.`}
                </span>
              </div>
            ))}
            {hardwareAssertions.filter(a => a.hasData && a.pass).length > 0 &&
              hardwareAssertions.filter(a => a.hasData && !a.pass).length === 0 && (
              <p className="ide-copy ide-hw-assert-all-pass" data-testid="ide-hw-assert-all-pass">
                {`All ${assertionPassCount} bring-up check${assertionPassCount === 1 ? '' : 's'} passed.`}
              </p>
            )}
            <details className="ide-hw-assert-raw-details">
              <summary className="ide-hw-assert-raw-summary">Technical details</summary>
              <div className="ide-hw-assert-raw-list">
                {hardwareAssertions.slice(0, 30).map((a, i) => (
                  <code
                    key={i}
                    className={`ide-hw-assert-formal ${a.hasData ? (a.pass ? 'is-pass' : 'is-fail') : 'is-nodata'}`}
                    data-testid={`ide-hw-assert-row-${a.tick}-${a.signal}`}
                  >
                    {`ASSERT t${a.tick} ${a.signal}=${a.expected} \u2192 ${
                      !a.hasData ? 'NO_DATA' : a.pass ? 'PASS' : `FAIL(act=${a.actual})`
                    }`}
                  </code>
                ))}
                {hardwareAssertions.length > 30 && (
                  <code className="ide-hw-assert-formal is-nodata">
                    +{hardwareAssertions.length - 30} more
                  </code>
                )}
              </div>
            </details>
          </div>
        )}
      </IdeInspectorSection>
    </>
  );

  const proofInspector = (
    <>
      <IdeInspectorSection title="Assertion Summary" defaultOpen>
        {!hasAssertionData ? (
          <p className="ide-copy">Awaiting trace.</p>
        ) : assertionFailCount === 0 ? (
          <code
            className="ide-hw-assert-formal ide-hw-proof-assert-ok is-pass"
            data-testid="ide-hw-proof-assert-ok"
          >
            {'\u22A2'} {assertionPassCount} assertion{assertionPassCount === 1 ? '' : 's'} match observed outputs{confidenceScore === 100 ? ' \u220E' : ''}
          </code>
        ) : (
          <div data-testid="ide-hw-proof-assert-failures">
            <p className="ide-copy ide-hw-proof-assert-fail-note">
              {assertionFailCount} assertion{assertionFailCount > 1 ? 's' : ''} differ from observed outputs
            </p>
            <IdeDataTable
              columns={['Step', 'Output', 'Expected', 'Observed']}
              rows={hardwareAssertions
                .filter((a) => !a.pass && a.hasData)
                .slice(0, 10)
                .map((a) => [
                  `Step ${a.tick}`,
                  signalHumanLabel(a.signal),
                  a.expected === '1' ? 'ON' : 'OFF',
                  a.actual == null ? '—' : a.actual === '1' ? 'ON' : 'OFF',
                ])}
              testId="ide-hw-proof-fail-table"
            />
          </div>
        )}
      </IdeInspectorSection>
      <IdeInspectorSection title="Expected Behavior" defaultOpen={false}>
        <p className="ide-copy" data-testid="ide-hardware-expected-behavior">
          {expectedBehavior}
        </p>
      </IdeInspectorSection>
    </>
  );

  const activeInspector =
    hwMode === 'live'
      ? liveInspector
      : hwMode === 'bringup'
        ? bringupInspector
        : proofInspector;
  const liveHardwareRows = useMemo(
    () => [
      ...Array.from({ length: 8 }, (_, index) => [`SW${index}`, String(ioBus.state.sw[index] ?? 0)]),
      ...Array.from({ length: 5 }, (_, index) => [
        ['BTNC', 'BTNU', 'BTND', 'BTNL', 'BTNR'][index],
        String(ioBus.state.btn[index] ?? 0),
      ]),
      ...Array.from({ length: 8 }, (_, index) => [`LD${index}`, String(ioBus.state.ld[index] ?? 0)]),
    ],
    [ioBus.state.btn, ioBus.state.ld, ioBus.state.sw]
  );

  return (
    <IdeSurfaceLayout
      mode="hardware"
      consoleHasBlocking={hasBlocking}
      consoleHasEntries={hasBlocking}
      dock={activeDock}
      inspector={
        <>
          <IdeInspectorSection title="Live Hardware State" defaultOpen>
            <IdeDataTable
              columns={['Signal', 'Value']}
              rows={liveHardwareRows}
              testId="ide-hardware-live-state-table"
            />
          </IdeInspectorSection>
          {activeInspector}
        </>
      }
      console={
        <section className="ide-workbench-console-content" data-testid="ide-hardware-console">
          <header className="ide-workbench-console-header">
            <h3>Hardware Console</h3>
            <span className="ide-workbench-console-mode">Hardware</span>
          </header>
          <IdeCallout
            tone={readinessCallout.tone}
            title={readinessCallout.title}
            testId="ide-hardware-readiness-callout"
          >
            {readinessCallout.message}
          </IdeCallout>
        </section>
      }
    >
      <IdePanel
        title="Hardware"
        description="Basys3 hardware proof."
        right={
          <IdeStatusPill tone={hardwareState === 'ready' ? 'ok' : 'warn'}>
            {hardwareState === 'ready' ? 'Ready' : 'Needs Action'}
          </IdeStatusPill>
        }
        testId="ide-hardware-panel"
      >
        {/* ── Connection callout strip ── */}
        <div className="ide-hw-callout" data-testid="ide-hw-callout">
          <span className="ide-hw-callout-label">Simulating:</span>
          <span className="ide-hw-callout-name">{projectName}</span>
          <span className="ide-hw-callout-sep" aria-hidden="true">·</span>
          <span>{mappingRows.length} pins mapped</span>
          {verifyStatus !== undefined && (
            <>
              <span className="ide-hw-callout-sep" aria-hidden="true">·</span>
              <span className={compareMatches ? 'ide-hw-callout-pass' : compareDiffers ? 'ide-hw-callout-fail' : ''}>
                Compare: {verifyStatus}
              </span>
              <span className="ide-hw-callout-sep" aria-hidden="true">|</span>
              <span data-testid="ide-hardware-export-status">
                Export: {exportStatus}
              </span>
            </>
          )}
        </div>

        {/* ── Scenario provenance strip ── */}
        {verifyLastRun && (
          <div className="ide-hardware-provenance-strip" data-testid="ide-hardware-provenance-strip">
            <span className="ide-hardware-provenance-run-label" data-testid="ide-hardware-provenance-run-label">
              Compared: &ldquo;{verifyLastRun.scenarioName}&rdquo;
            </span>
            <span className="ide-hardware-provenance-sep" aria-hidden="true">·</span>
            <span
              className={`ide-hardware-provenance-axis ide-hardware-provenance-axis--${scenarioDrifted ? 'warn' : 'ok'}`}
              data-testid="ide-hardware-scenario-axis"
            >
              {isDifferentScenario
                ? '⚠ Different scenario selected'
                : isSameScenarioEdited
                  ? '⚠ Scenario edited since run'
                  : '✓ Scenario current'}
            </span>
            {!scenarioDrifted && vectorsAreAutoGenerated && (
              <>
                <span className="ide-hardware-provenance-sep" aria-hidden="true">·</span>
                <span
                  className="ide-hardware-provenance-axis ide-hardware-provenance-axis--warn"
                  data-testid="ide-hardware-seal-axis"
                >
                  ~ Starter scenario
                </span>
              </>
            )}
          </div>
        )}

        {/* ── Mode toggle bar ── */}
        {blockedHero && (
          <SurfacePanel className="ide-hardware-blocked-hero" testId="ide-hardware-blocked-hero">
            <div className="ide-hardware-blocked-hero__copy">
              <strong className="ide-hardware-blocked-hero__title">{blockedHero.title}</strong>
              <p className="ide-copy" style={{ margin: 0 }}>
                {blockedHero.body}
              </p>
            </div>
            <div className="ide-hardware-blocked-hero__actions">
              <IdeButton tone="primary" onClick={blockedHero.primaryAction} testId={blockedHero.primaryTestId}>
                {blockedHero.primaryLabel}
              </IdeButton>
              {onGoToDesign && (
                <IdeButton tone="secondary" onClick={onGoToDesign} testId="ide-hardware-blocked-secondary">
                  Open Design
                </IdeButton>
              )}
            </div>
          </SurfacePanel>
        )}
        <div className="ide-hw-mode-toggle" data-testid="ide-hw-mode-toggle">
          {(['live', 'bringup', 'proof', 'map'] as const).map((m) => (
            <IdeButton
              key={m}
              tone={hwMode === m ? 'primary' : 'ghost'}
              onClick={() => { setHwMode(m); setSelectedMappingRowId(null); }}
              testId={`ide-hw-mode-btn-${m}`}
            >
              {m === 'live' ? 'Live Monitor' : m === 'bringup' ? 'Bring-Up' : m === 'proof' ? 'Proof' : 'Map Pins'}
            </IdeButton>
          ))}
          {sim.tick > 0 && (
            <span className="ide-hw-tick-badge" data-testid="ide-hw-tick-badge">
              t{sim.tick}
            </span>
          )}
        </div>

        {/* ── Scenario drift callout ── */}
        {scenarioDrifted && verifyLastRun && (
          <IdeCallout
            tone="warn"
            title={isDifferentScenario ? 'Different scenario active' : 'Scenario edited since last run'}
            testId="ide-hardware-drift-callout"
          >
            <p className="ide-copy" style={{ margin: 0 }}>
              {isDifferentScenario
                ? `The board view reflects verify results for \u201c${verifyLastRun.scenarioName}\u201d. You have a different scenario active — re-run Verify to get results for the current scenario.`
                : `\u201c${verifyLastRun.scenarioName}\u201d was edited after the last verify run. Re-run Verify to get a current result.`}
            </p>
            <div className="ide-inline-actions" style={{ marginTop: 'var(--ide-space-2)' }}>
              <IdeButton tone="primary" onClick={onOpenVerify} testId="ide-hardware-drift-reverify">
                Re-run Verify
              </IdeButton>
              {isDifferentScenario && switchBackScenario && onSwitchScenario && (
                <IdeButton
                  tone="ghost"
                  onClick={() => onSwitchScenario(verifyLastRun.scenarioId)}
                  testId="ide-hardware-drift-switchback"
                >
                  Switch to &ldquo;{switchBackScenario.name}&rdquo;
                </IdeButton>
              )}
            </div>
          </IdeCallout>
        )}

        {/* ── Starter-seal note — shown when verify is ready but unsealed ── */}
        {compareCurrent && !scenarioDrifted && vectorsAreAutoGenerated && (
          <IdeCallout tone="warn" testId="ide-hardware-starter-seal-note">
            <p className="ide-copy" style={{ margin: 0 }}>
              <strong>Ready — starter scenario only.</strong>{' '}
              The board is backed by a starter scenario only. Author a real test scenario and rerun Compare before relying on this result for lab work.
            </p>
          </IdeCallout>
        )}

        {/* ── SSD guidance callout ── */}
        {hasSsdMapping && (
          <IdeCallout tone="info" title="7-Segment Display" testId="ide-hw-ssd-callout">
            <p className="ide-copy" style={{ margin: 0 }}>
              Your circuit uses 7-segment display outputs. The Basys3 uses <strong>active-low</strong> segment
              lines (0 = segment ON). Digit select (AN0–AN3) are also active-low; AN0 controls the rightmost
              digit. Segment order: CA=seg[0], CB=seg[1], CC=seg[2], CD=seg[3], CE=seg[4], CF=seg[5],
              CG=seg[6], DP=decimal point.
            </p>
          </IdeCallout>
        )}

        {/* ── Debounce guidance callout ── */}
        {hasButtonMapping && !debounceDismissed && (
          <IdeCallout tone="warn" title="Physical buttons bounce" testId="ide-hw-debounce-callout">
            <p className="ide-copy" style={{ margin: 0 }}>
              Physical push buttons produce multiple signal transitions when pressed or released. Add
              synchronizer flip-flops or a debounce delay to ensure reliable edge detection.
            </p>
            <div className="ide-inline-actions" style={{ marginTop: 'var(--ide-space-2)' }}>
              <IdeButton
                tone="ghost"
                onClick={() => setDebounceDismissed(true)}
                testId="ide-hw-debounce-dismiss"
              >
                Got it
              </IdeButton>
            </div>
          </IdeCallout>
        )}

        {/* ── Board / Map ── */}
        {hwMode === 'map' ? (
          <div className="ide-hw-map-mode" data-testid="ide-hw-map-mode">
            <div className="ide-hw-map-table" data-testid="ide-hw-map-table">
              <p className="ide-copy ide-hw-map-instructions">
                {selectedMappingRowId
                  ? 'Click a board region to assign the pin.'
                  : 'Click a signal row, then click a board region to assign its pin.'}
              </p>
              {mapModeGroups.map((group) => (
                <details key={group.label} open>
                  <summary className="ide-hw-map-group-label">{group.label}</summary>
                  <div className="ide-hw-map-group">
                    {group.rows.map((row) => (
                      <button
                        key={row.id}
                        type="button"
                        className={`ide-hw-map-row ${selectedMappingRowId === row.id ? 'is-selected' : ''}`}
                        data-testid={`ide-hw-map-row-${row.id}`}
                        onClick={() =>
                          setSelectedMappingRowId(row.id === selectedMappingRowId ? null : row.id)
                        }
                      >
                        <span className="ide-hw-map-row-label">{getStudentFacingIoLabel(row)}</span>
                        <code className="ide-hw-map-row-pin">{row.pin || '—'}</code>
                      </button>
                    ))}
                  </div>
                </details>
              ))}
            </div>
            <div className="ide-hw-map-board" data-testid="ide-hw-map-board">
              <Basys3BoardView
                mappedAliases={mapModeAliases}
                highlightedAlias={selectedMappingRowPin}
                onSelectAlias={(alias) => {
                  if (selectedMappingRowId && onSetMappingPin) {
                    onSetMappingPin(selectedMappingRowId, alias);
                    setSelectedMappingRowId(null);
                  }
                }}
              />
            </div>
          </div>
        ) : (
        <div className={`ide-hw-board-wrap ${hwMode === 'proof' ? 'is-proof' : ''}`}>
          <div className="ide-hw-board-inner">
            <HardwareBoard2D
              sw={ioBus.state.sw}
              ld={ioBus.state.ld}
              btn={ioBus.state.btn}
              mappedSw={mappedSw}
              mappedLd={mappedLd}
              mismatchedLd={mismatchedLd}
              highlightedSw={currentStepHighlights.sw}
              highlightedLd={currentStepHighlights.ld}
              activeSignal={effectiveBoardSignal}
              onSelectSignal={(sig) => setActiveBoardSignal(sig)}
              onHoverSignal={(sig) => setHoverBoardSignal(sig)}
              onToggleSwitch={(i) => {
                ioBus.actions.toggleSwitch(i);
                setActiveBoardSignal({ type: 'sw', index: i });
              }}
              onSetSwitch={(i, value) => {
                ioBus.actions.setSwitch(i, value);
                setActiveBoardSignal({ type: 'sw', index: i });
              }}
              onPressButton={(i, down) => {
                ioBus.actions.setButton(i, down ? 1 : 0);
                if (down) setActiveBoardSignal({ type: 'btn', index: i });
              }}
            />
          </div>
          {hwMode === 'proof' && (
            <div
              className={`ide-hw-proof-verdict ${
                !hasAssertionData
                  ? 'is-pending'
                  : assertionFailCount === 0
                    ? 'is-valid'
                    : 'is-invalid'
              }`}
              data-testid="ide-hw-proof-verdict"
            >
              <span className="ide-hw-proof-verdict-label" data-testid="ide-hw-proof-verdict-label">
                {!hasAssertionData
                  ? 'PROOF PENDING'
                  : assertionFailCount === 0
                    ? 'PROOF VALID'
                    : 'PROOF INVALID'}
              </span>
              <div className="ide-hw-proof-verdict-meta">
                <div className="ide-hw-proof-verdict-row">
                  <span className="ide-hw-cert-key">CONFIDENCE</span>
                  <code className="ide-hw-cert-val">
                    {confidenceScore}%{confidenceScore === 100 ? ' \u220E' : ''}
                  </code>
                </div>
                <div className="ide-hw-proof-verdict-row">
                  <span className="ide-hw-cert-key">ASSERTIONS</span>
                  <code className="ide-hw-cert-val">
                    {hasAssertionData ? `${assertionPassCount}P ${assertionFailCount}F` : '\u2014'}
                  </code>
                </div>
                <div className="ide-hw-proof-verdict-row">
                  <span className="ide-hw-cert-key">HASH</span>
                  <code className="ide-hw-cert-val">
                    {health.lastVerify?.hash?.slice(0, 16) ?? '\u2014'}
                  </code>
                </div>
                <div className="ide-hw-proof-verdict-row">
                  <span className="ide-hw-cert-key">STATUS</span>
                  <code className="ide-hw-cert-val">
                    {verifyStatus}/{exportStatus}
                  </code>
                </div>
              </div>
            </div>
          )}
        </div>
        )}
      </IdePanel>
    </IdeSurfaceLayout>
  );
};
