import React from 'react';
import { IdeButton, IdeCallout } from '../components/IdePrimitives';
import { SurfacePanel } from '../components/SurfaceLayoutPrimitives';
import { VectorEditor, type CustomTestVector, type VectorEditorField } from '../components/VectorEditor';

export interface VerifyVectorDraftInput {
  id: string;
  label: string;
  pin?: string;
}

export interface VerifyAuthorVector {
  id: string;
  tick: number;
  inputs: Record<string, 0 | 1>;
  expected: Record<string, 0 | 1>;
}

export type SweepPreset = 'binary-count' | 'toggle-sw0' | 'walk-one-hot';

export interface ScenarioBuilderPanelProps {
  // Signal schema
  inputFields: VerifyVectorDraftInput[];
  outputFields: VerifyVectorDraftInput[];
  // Authored vector state
  authoredVectors: VerifyAuthorVector[];
  // Draft form state
  draftTick: number;
  draftInputs: Record<string, '0' | '1'>;
  draftExpected: Record<string, '0' | '1'>;
  onDraftTickChange: (tick: number) => void;
  onDraftInputChange: (fieldId: string, value: '0' | '1') => void;
  onDraftExpectedChange: (fieldId: string, value: '0' | '1') => void;
  // Test case actions
  onAddVector: () => void;
  onGenerateBasics: () => void;
  onRun: () => void;
  onOpenProjectVectors: () => void;
  // Auto-generate
  onAutoGenerate: () => void;
  // Sweep generator
  sweepPreset: SweepPreset;
  sweepSeed: string;
  sweepHoldTicks: number;
  onSweepPresetChange: (preset: SweepPreset) => void;
  onSweepSeedChange: (seed: string) => void;
  onSweepHoldTicksChange: (ticks: number) => void;
  onGenerateSweep: () => void;
  // Hold × N — appends N copies of the current draft at consecutive ticks
  holdN: number;
  onHoldNChange: (n: number) => void;
  onHoldN: (n: number) => void;
  // Pulse — one signal high then low, all others carry forward
  pulseSignal: string;
  onPulseSignalChange: (id: string) => void;
  onPulse: (signalId: string) => void;
  // Custom vector editor
  customVectors: CustomTestVector[];
  onCustomVectorsChange: (vectors: CustomTestVector[]) => void;
  // Auto-vector banner
  vectorsAreAutoGenerated: boolean;
  autoVectorBannerDismissed: boolean;
  onDismissAutoVectorBanner: () => void;
  // Layout: true = first-run hero, false = post-run collapsible
  isFirstRun: boolean;
  // Sequential circuit context
  isSequential?: boolean;
}

function normalizeFieldId(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9_]/g, '_');
}

function toTestId(value: string): string {
  return normalizeFieldId(value);
}

export const ScenarioBuilderPanel: React.FC<ScenarioBuilderPanelProps> = ({
  inputFields,
  outputFields,
  authoredVectors,
  draftTick,
  draftInputs,
  draftExpected,
  onDraftTickChange,
  onDraftInputChange,
  onDraftExpectedChange,
  onAddVector,
  onGenerateBasics,
  onRun,
  onOpenProjectVectors,
  onAutoGenerate,
  sweepPreset,
  sweepSeed,
  sweepHoldTicks,
  onSweepPresetChange,
  onSweepSeedChange,
  onSweepHoldTicksChange,
  onGenerateSweep,
  holdN,
  onHoldNChange,
  onHoldN,
  pulseSignal,
  onPulseSignalChange,
  onPulse,
  customVectors,
  onCustomVectorsChange,
  vectorsAreAutoGenerated,
  autoVectorBannerDismissed,
  onDismissAutoVectorBanner,
  isFirstRun,
  isSequential = false,
}) => {
  const hasVectors = authoredVectors.length > 0;
  const canAutoGenerate = inputFields.length > 0 && inputFields.length <= 6;

  const authoringForm = (
    <div className="ide-verify-vector-form" data-testid="ide-verify-add-vector-form">
      {isSequential && (
        <IdeCallout tone="info" testId="ide-verify-sequential-context">
          <p className="ide-copy">
            <strong>Sequential circuit detected.</strong>{' '}
            Registers only change on clock edges — your test scenario must include clock transitions
            to observe register outputs. Generate Basics creates a starter sequence with alternating
            clock ticks.
          </p>
        </IdeCallout>
      )}
      {vectorsAreAutoGenerated && !autoVectorBannerDismissed && (
        <IdeCallout tone="info" testId="ide-verify-auto-vector-notice">
          <p className="ide-copy">
            These test cases were auto-generated to get you started.
            Edit or replace them to test your specific circuit behavior,
            then click <strong>Run</strong> to verify.
          </p>
          <div className="ide-inline-actions">
            <IdeButton
              tone="ghost"
              onClick={onDismissAutoVectorBanner}
              testId="ide-verify-auto-vector-dismiss"
            >
              Dismiss
            </IdeButton>
          </div>
        </IdeCallout>
      )}

      <p className="ide-verify-section-subheader">Create Test Case</p>
      <label className="ide-verify-field">
        Tick
        <input
          type="number"
          className="ide-export-pin-input"
          value={draftTick}
          min={0}
          step={1}
          onChange={(event) => onDraftTickChange(Number(event.target.value || '0'))}
          data-testid="ide-verify-add-vector-tick"
        />
      </label>
      <div className="ide-verify-vector-grid">
        {inputFields.map((field, index) => (
          <label key={`${field.id || 'field'}-${index}`} className="ide-verify-field">
            <span>
              {field.label}
              {field.pin ? <code className="ide-verify-field-pin"> {field.pin}</code> : null}
            </span>
            <select
              className="ide-export-pin-input"
              value={draftInputs[field.id] ?? '0'}
              onChange={(event) =>
                onDraftInputChange(field.id, event.target.value === '1' ? '1' : '0')
              }
              data-testid={`ide-verify-add-vector-input-${toTestId(field.id)}`}
            >
              <option value="0">0</option>
              <option value="1">1</option>
            </select>
          </label>
        ))}
      </div>
      {outputFields.length > 0 && (
        <>
          <p className="ide-verify-section-subheader">Expected outputs</p>
          <div className="ide-verify-vector-grid ide-verify-vector-grid--expected">
            {outputFields.map((field, index) => (
              <label
                key={`${field.id || 'out'}-${index}`}
                className="ide-verify-field ide-verify-field--expected"
              >
                <span>
                  {field.label}
                  {field.pin ? <code className="ide-verify-field-pin"> {field.pin}</code> : null}
                </span>
                <select
                  className="ide-export-pin-input"
                  value={draftExpected[field.id] ?? '0'}
                  onChange={(event) =>
                    onDraftExpectedChange(field.id, event.target.value === '1' ? '1' : '0')
                  }
                  data-testid={`ide-verify-add-vector-expected-${toTestId(field.id)}`}
                >
                  <option value="0">0</option>
                  <option value="1">1</option>
                </select>
              </label>
            ))}
          </div>
        </>
      )}
      <div className="ide-inline-actions">
        <IdeButton tone="primary" onClick={onAddVector} testId="ide-verify-add-vector-submit">
          Add Case
        </IdeButton>
        <IdeButton
          tone="secondary"
          onClick={onGenerateBasics}
          testId="ide-verify-generate-basic-vectors"
        >
          Generate Basics
        </IdeButton>
      </div>
      <details className="ide-verify-more-actions-details">
        <summary className="ide-verify-more-actions-summary">More options</summary>
        {canAutoGenerate && (
          <IdeButton tone="ghost" onClick={onAutoGenerate} testId="ide-verify-autogen-btn">
            Auto-fill {1 << inputFields.length} combos
          </IdeButton>
        )}
        <IdeButton tone="ghost" onClick={onOpenProjectVectors}>
          Open Project vectors
        </IdeButton>
        {/* ── Hold × N ──────────────────────────────────────────────────── */}
        <div className="ide-verify-hold-n-row" data-testid="ide-verify-hold-n-controls">
          <label className="ide-verify-field ide-verify-hold-n-label">
            Hold ×
            <input
              type="number"
              className="ide-export-pin-input ide-verify-hold-n-input"
              min={1}
              max={64}
              step={1}
              value={holdN}
              onChange={(e) => onHoldNChange(Math.max(1, Math.min(64, Number(e.target.value || '1'))))}
              data-testid="ide-verify-hold-n-count"
            />
          </label>
          <IdeButton
            tone="ghost"
            onClick={() => onHoldN(holdN)}
            testId="ide-verify-hold-n-btn"
          >
            Hold
          </IdeButton>
        </div>
        {/* ── Pulse ─────────────────────────────────────────────────────── */}
        {inputFields.length > 0 && (
          <div className="ide-verify-pulse-row" data-testid="ide-verify-pulse-controls">
            <label className="ide-verify-field ide-verify-pulse-label">
              Pulse signal
              <select
                className="ide-export-pin-input"
                value={pulseSignal}
                onChange={(e) => onPulseSignalChange(e.target.value)}
                data-testid="ide-verify-pulse-signal-select"
              >
                {inputFields.map((f) => (
                  <option key={f.id} value={f.id}>{f.label ?? f.id}</option>
                ))}
              </select>
            </label>
            <IdeButton
              tone="ghost"
              onClick={() => onPulse(pulseSignal || inputFields[0]!.id)}
              testId="ide-verify-pulse-btn"
              disabled={inputFields.length === 0}
            >
              Pulse
            </IdeButton>
          </div>
        )}
      </details>
      <details className="ide-verify-sweep-details">
        <summary className="ide-verify-sweep-summary">Sweep generator</summary>
        <div className="ide-verify-sweep-controls" data-testid="ide-verify-sweep-controls">
          <label className="ide-verify-field">
            Sweep preset
            <select
              className="ide-export-pin-input"
              value={sweepPreset}
              onChange={(event) =>
                onSweepPresetChange(
                  event.target.value === 'toggle-sw0'
                    ? 'toggle-sw0'
                    : event.target.value === 'walk-one-hot'
                      ? 'walk-one-hot'
                      : 'binary-count'
                )
              }
              data-testid="ide-verify-sweep-preset"
            >
              <option value="binary-count">Binary count SW[3:0]</option>
              <option value="toggle-sw0">Toggle SW0</option>
              <option value="walk-one-hot">One-hot walk</option>
            </select>
          </label>
          <label className="ide-verify-field">
            Seed
            <input
              type="number"
              className="ide-export-pin-input"
              value={sweepSeed}
              onChange={(event) => onSweepSeedChange(event.target.value)}
              data-testid="ide-verify-sweep-seed"
            />
          </label>
          <label className="ide-verify-field">
            Hold ticks
            <input
              type="number"
              className="ide-export-pin-input"
              min={1}
              step={1}
              value={sweepHoldTicks}
              onChange={(event) =>
                onSweepHoldTicksChange(Math.max(1, Number(event.target.value || '1')))
              }
              data-testid="ide-verify-sweep-hold"
            />
          </label>
          <IdeButton
            tone="secondary"
            onClick={onGenerateSweep}
            testId="ide-verify-generate-sweep-vectors"
          >
            Generate Sweep
          </IdeButton>
        </div>
      </details>
      <details className="ide-verify-sweep-details" data-testid="ide-verify-custom-vectors-panel">
        <summary className="ide-verify-sweep-summary">Custom test vectors</summary>
        <div style={{ paddingTop: '6px' }}>
          <VectorEditor
            inputFields={inputFields.map((f): VectorEditorField => ({ id: f.id, label: f.label ?? f.id }))}
            outputFields={outputFields.map((f): VectorEditorField => ({ id: f.id, label: f.label ?? f.id }))}
            vectors={customVectors}
            onChange={onCustomVectorsChange}
          />
        </div>
      </details>
    </div>
  );

  if (isFirstRun) {
    const primaryLabel = hasVectors ? 'Run Verification' : 'Generate Basics';
    const primaryAction = hasVectors ? onRun : onGenerateBasics;
    const calloutTitle = hasVectors
      ? 'Run Verify on the current vectors'
      : 'Start with a small vector set';

    return (
      <SurfacePanel className="ide-verify-first-run-hero" testId="ide-verify-empty-state">
        <div className="ide-verify-empty-message" data-testid="ide-verify-empty-message">
          <span className="ide-verify-empty-label">Build your testbench</span>
          <span className="ide-verify-empty-hint">
            {hasVectors
              ? `${authoredVectors.length} vector${authoredVectors.length !== 1 ? 's are' : ' is'} ready. Run verification to compare expected vs. observed outputs.`
              : 'Define the inputs and expected outputs you want to check, then run Verify. Generate Basics to start, or build your own.'}
          </span>
        </div>
        <div className="ide-verify-first-run-hero__actions">
          {hasVectors ? (
            <span data-testid="ide-verify-empty-run">
              <IdeButton tone="primary" onClick={primaryAction} testId="ide-verify-run">
                {primaryLabel}
              </IdeButton>
            </span>
          ) : (
            <IdeButton
              tone="primary"
              onClick={primaryAction}
              testId="ide-verify-empty-generate-basics"
            >
              {primaryLabel}
            </IdeButton>
          )}
          <IdeButton tone="secondary" onClick={onOpenProjectVectors} testId="ide-verify-empty-open-vectors">
            Open Project vectors
          </IdeButton>
        </div>
        <IdeCallout tone="info" title={calloutTitle} testId="ide-verify-first-run-callout">
          <p className="ide-copy" style={{ margin: 0 }}>
            {hasVectors
              ? 'Run verification first. Step-through, waveform inspection, and oracle tools stay available after you have real evidence.'
              : 'Generate a starter set now, then edit expected outputs only if you need a custom test plan.'}
          </p>
        </IdeCallout>
        <details className="ide-verify-scenario-builder-details" open>
          <summary className="ide-verify-scenario-builder-summary">
            Testbench editor
            {authoredVectors.length > 0 && (
              <span className="ide-verify-scenario-builder-count">
                {' '}({authoredVectors.length} case{authoredVectors.length !== 1 ? 's' : ''})
              </span>
            )}
          </summary>
          {authoringForm}
        </details>
      </SurfacePanel>
    );
  }

  // Post-run: open by default above the waveform workbench
  return (
    <details className="ide-verify-scenario-builder-details ide-verify-scenario-builder-details--postrun" open>
      <summary className="ide-verify-scenario-builder-summary">
        Testbench
        {authoredVectors.length > 0 && (
          <span className="ide-verify-scenario-builder-count">
            {' '}({authoredVectors.length} case{authoredVectors.length !== 1 ? 's' : ''})
          </span>
        )}
      </summary>
      {authoringForm}
    </details>
  );
};
