import React from 'react';
import { IdeButton, IdeCallout } from '../components/IdePrimitives';
import { StimulusCanvas } from '../components/StimulusCanvas';

export interface VerifyVectorDraftInput {
  id: string;
  label: string;
  pin?: string;
}

export interface VerifyAuthorVector {
  id: string;
  tick: number;
  inputs: Record<string, 0 | 1>;
  expected: Record<string, 0 | 1>;
}

export type VerifyExpectedDraftValue = '' | '0' | '1';

export type SweepPreset = 'binary-count' | 'toggle-sw0' | 'walk-one-hot';

export interface ScenarioBuilderPanelProps {
  // Signal schema
  inputFields: VerifyVectorDraftInput[];
  outputFields: VerifyVectorDraftInput[];
  // Authored vector state
  authoredVectors: VerifyAuthorVector[];
  totalVectorCount?: number;
  hasAssertedExpectedCells?: boolean;
  // Canvas authoring (primary path — Slice 5+)
  onVectorsChange?: (vectors: VerifyAuthorVector[]) => void;
  // Draft form state (kept for fallback manual entry in More options)
  draftTick: number;
  draftInputs: Record<string, '0' | '1'>;
  draftExpected: Record<string, VerifyExpectedDraftValue>;
  onDraftTickChange: (tick: number) => void;
  onDraftInputChange: (fieldId: string, value: '0' | '1') => void;
  onDraftExpectedChange: (fieldId: string, value: VerifyExpectedDraftValue) => void;
  // Test case actions
  onAddVector: () => void;
  onGenerateBasics: () => void;
  onRun: () => void;
  runButtonLabel?: string;
  onOpenProjectVectors: () => void;
  // Auto-generate
  onAutoGenerate: () => void;
  // Sweep generator
  sweepPreset: SweepPreset;
  sweepSeed: string;
  sweepHoldTicks: number;
  onSweepPresetChange: (preset: SweepPreset) => void;
  onSweepSeedChange: (seed: string) => void;
  onSweepHoldTicksChange: (ticks: number) => void;
  onGenerateSweep: () => void;
  // Hold × N — appends N copies of the current draft at consecutive ticks
  holdN: number;
  onHoldNChange: (n: number) => void;
  onHoldN: (n: number) => void;
  // Pulse — one signal high then low, all others carry forward
  pulseSignal: string;
  onPulseSignalChange: (id: string) => void;
  onPulse: (signalId: string) => void;
  // Auto-vector banner
  vectorsAreAutoGenerated: boolean;
  autoVectorBannerDismissed: boolean;
  onDismissAutoVectorBanner: () => void;
  // Layout: true = first-run hero, false = post-run collapsible
  isFirstRun: boolean;
  // Sequential circuit context
  isSequential?: boolean;
  // Sync: true when inputFields are placeholder fallbacks (no real circuit I/O mapped)
  isUsingFallbackSignals?: boolean;
  // Navigation: go to Hardware surface to map I/O
  onGoToHardware?: () => void;
}

function normalizeFieldId(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9_]/g, '_');
}

function toTestId(value: string): string {
  return normalizeFieldId(value);
}

export const ScenarioBuilderPanel: React.FC<ScenarioBuilderPanelProps> = ({
  inputFields,
  outputFields,
  authoredVectors,
  totalVectorCount,
  hasAssertedExpectedCells,
  onVectorsChange,
  draftTick,
  draftInputs,
  draftExpected,
  onDraftTickChange,
  onDraftInputChange,
  onDraftExpectedChange,
  onAddVector,
  onGenerateBasics,
  onRun,
  runButtonLabel = 'Run Testbench',
  onOpenProjectVectors,
  onAutoGenerate,
  sweepPreset,
  sweepSeed,
  sweepHoldTicks,
  onSweepPresetChange,
  onSweepSeedChange,
  onSweepHoldTicksChange,
  onGenerateSweep,
  holdN,
  onHoldNChange,
  onHoldN,
  pulseSignal,
  onPulseSignalChange,
  onPulse,
  vectorsAreAutoGenerated,
  autoVectorBannerDismissed,
  onDismissAutoVectorBanner,
  isFirstRun,
  isSequential = false,
  isUsingFallbackSignals = false,
  onGoToHardware,
}) => {
  const effectiveVectorCount = totalVectorCount ?? authoredVectors.length;
  const hasVectors = effectiveVectorCount > 0;
  const showsAssertedExpectedCells = hasAssertedExpectedCells ?? authoredVectors.some(
    (vector) => Object.keys(vector.expected ?? {}).length > 0
  );
  const canAutoGenerate = inputFields.length > 0 && inputFields.length <= 6;

  // Pre-run canvas: stripped down — just the StimulusCanvas, no toolbar eating height.
  // Generate Basics + Run are in the run footer below.
  const preRunCanvas = (
    <div className="ide-verify-vector-form ide-verify-vector-form--canvas-only" data-testid="ide-verify-add-vector-form">
      {isSequential && (
        <div className="ide-verify-seq-chip" data-testid="ide-verify-sequential-context">
          Sequential — use clock ticks in your stimulus
        </div>
      )}
      {onVectorsChange != null ? (
        <StimulusCanvas
          inputFields={inputFields}
          outputFields={outputFields}
          authoredVectors={authoredVectors}
          onVectorsChange={onVectorsChange}
        />
      ) : (
        <p className="ide-verify-section-subheader" style={{ padding: '12px' }}>
          No canvas — wire onVectorsChange to enable editing.
        </p>
      )}
      {/* Gate contract: keep hidden inputs for test contracts */}
      <div style={{ display: 'none' }}>
        <IdeButton tone="secondary" onClick={onGenerateBasics} testId="ide-verify-generate-basic-vectors">Generate Basics</IdeButton>
      </div>
    </div>
  );

  const authoringForm = (
    <div className="ide-verify-vector-form" data-testid="ide-verify-add-vector-form">
      {/* ── Context callouts ── */}
      {isSequential && (
        <IdeCallout tone="info" testId="ide-verify-sequential-context">
          <p className="ide-copy">
            <strong>Sequential circuit detected.</strong>{' '}
            Registers only change on clock edges — your test scenario must include clock transitions
            to observe register outputs. Generate Basics creates a starter sequence with alternating
            clock ticks.
          </p>
        </IdeCallout>
      )}
      {vectorsAreAutoGenerated && !autoVectorBannerDismissed && (
        <IdeCallout tone="info" testId="ide-verify-auto-vector-notice">
          <p className="ide-copy">
            These test cases were auto-generated to get you started.
            Edit or replace them to test your specific circuit behavior,
            then click <strong>Run</strong> to verify.
          </p>
          <div className="ide-inline-actions">
            <IdeButton
              tone="ghost"
              onClick={onDismissAutoVectorBanner}
              testId="ide-verify-auto-vector-dismiss"
            >
              Dismiss
            </IdeButton>
          </div>
        </IdeCallout>
      )}

      {/* ── StimulusCanvas toolbar ── */}
      <div className="ide-stimulus-toolbar">
        <IdeButton
          tone="secondary"
          onClick={onGenerateBasics}
          testId="ide-verify-generate-basic-vectors"
        >
          Generate Basics
        </IdeButton>
      </div>

      {/* ── StimulusCanvas — primary timeline authoring (Slice 5+) ── */}
      {onVectorsChange != null ? (
        <StimulusCanvas
          inputFields={inputFields}
          outputFields={outputFields}
          authoredVectors={authoredVectors}
          onVectorsChange={onVectorsChange}
        />
      ) : (
        /* Fallback: show legacy draft form if canvas prop not wired */
        <>
          <p className="ide-verify-section-subheader">Create Test Case</p>
          <label className="ide-verify-field">
            Tick
            <input
              type="number"
              className="ide-export-pin-input"
              value={draftTick}
              min={0}
              step={1}
              onChange={(event) => onDraftTickChange(Number(event.target.value || '0'))}
              data-testid="ide-verify-add-vector-tick"
            />
          </label>
          <div className="ide-verify-vector-grid">
            {inputFields.map((field, index) => (
              <label key={`${field.id || 'field'}-${index}`} className="ide-verify-field">
                <span>
                  {field.label}
                  {field.pin ? <code className="ide-verify-field-pin"> {field.pin}</code> : null}
                </span>
                <select
                  className="ide-export-pin-input"
                  value={draftInputs[field.id] ?? '0'}
                  onChange={(event) =>
                    onDraftInputChange(field.id, event.target.value === '1' ? '1' : '0')
                  }
                  data-testid={`ide-verify-add-vector-input-${toTestId(field.id)}`}
                >
                  <option value="0">0</option>
                  <option value="1">1</option>
                </select>
              </label>
            ))}
          </div>
          <div className="ide-inline-actions">
            <IdeButton tone="primary" onClick={onAddVector} testId="ide-verify-add-vector-submit">
              Add Case
            </IdeButton>
          </div>
        </>
      )}

      {/* ── More options ── */}
      <details className="ide-verify-more-actions-details">
        <summary className="ide-verify-more-actions-summary">More options</summary>
        {canAutoGenerate && (
          <IdeButton tone="ghost" onClick={onAutoGenerate} testId="ide-verify-autogen-btn">
            Auto-fill {1 << inputFields.length} combos
          </IdeButton>
        )}
        <IdeButton tone="ghost" onClick={onOpenProjectVectors}>
          Open Project vectors
        </IdeButton>
        {/* Manual entry fallback (available even when canvas is active) */}
        {onVectorsChange != null && (
          <details className="ide-verify-manual-entry-details">
            <summary className="ide-verify-more-actions-summary">Manual entry</summary>
            <label className="ide-verify-field">
              Tick
              <input
                type="number"
                className="ide-export-pin-input"
                value={draftTick}
                min={0}
                step={1}
                onChange={(event) => onDraftTickChange(Number(event.target.value || '0'))}
                data-testid="ide-verify-add-vector-tick"
              />
            </label>
            <div className="ide-verify-vector-grid">
              {inputFields.map((field, index) => (
                <label key={`${field.id || 'field'}-${index}`} className="ide-verify-field">
                  <span>
                    {field.label}
                    {field.pin ? <code className="ide-verify-field-pin"> {field.pin}</code> : null}
                  </span>
                  <select
                    className="ide-export-pin-input"
                    value={draftInputs[field.id] ?? '0'}
                    onChange={(event) =>
                      onDraftInputChange(field.id, event.target.value === '1' ? '1' : '0')
                    }
                    data-testid={`ide-verify-add-vector-input-${toTestId(field.id)}`}
                  >
                    <option value="0">0</option>
                    <option value="1">1</option>
                  </select>
                </label>
              ))}
            </div>
            {outputFields.length > 0 && (
              <>
                <p className="ide-verify-section-subheader">Expected outputs (optional)</p>
                <div className="ide-verify-vector-grid ide-verify-vector-grid--expected">
                  {outputFields.map((field, index) => (
                    <label
                      key={`${field.id || 'out'}-${index}`}
                      className="ide-verify-field ide-verify-field--expected"
                    >
                      <span>
                        {field.label}
                        {field.pin ? (
                          <code className="ide-verify-field-pin"> {field.pin}</code>
                        ) : null}
                      </span>
                      <select
                        className="ide-export-pin-input"
                        value={draftExpected[field.id] ?? ''}
                        onChange={(event) =>
                          onDraftExpectedChange(
                            field.id,
                            event.target.value === '1'
                              ? '1'
                              : event.target.value === '0'
                                ? '0'
                                : ''
                          )
                        }
                        data-testid={`ide-verify-add-vector-expected-${toTestId(field.id)}`}
                      >
                        <option value="">-</option>
                        <option value="0">0</option>
                        <option value="1">1</option>
                      </select>
                    </label>
                  ))}
                </div>
              </>
            )}
            <div className="ide-inline-actions">
              <IdeButton
                tone="primary"
                onClick={onAddVector}
                testId="ide-verify-add-vector-submit"
              >
                Add Case
              </IdeButton>
            </div>
          </details>
        )}
        {/* ── Hold × N ──────────────────────────────────────────────────── */}
        <div className="ide-verify-hold-n-row" data-testid="ide-verify-hold-n-controls">
          <label className="ide-verify-field ide-verify-hold-n-label">
            Hold ×
            <input
              type="number"
              className="ide-export-pin-input ide-verify-hold-n-input"
              min={1}
              max={64}
              step={1}
              value={holdN}
              onChange={(e) => onHoldNChange(Math.max(1, Math.min(64, Number(e.target.value || '1'))))}
              data-testid="ide-verify-hold-n-count"
            />
          </label>
          <IdeButton
            tone="ghost"
            onClick={() => onHoldN(holdN)}
            testId="ide-verify-hold-n-btn"
          >
            Hold
          </IdeButton>
        </div>
        {/* ── Pulse ─────────────────────────────────────────────────────── */}
        {inputFields.length > 0 && (
          <div className="ide-verify-pulse-row" data-testid="ide-verify-pulse-controls">
            <label className="ide-verify-field ide-verify-pulse-label">
              Pulse signal
              <select
                className="ide-export-pin-input"
                value={pulseSignal}
                onChange={(e) => onPulseSignalChange(e.target.value)}
                data-testid="ide-verify-pulse-signal-select"
              >
                {inputFields.map((f) => (
                  <option key={f.id} value={f.id}>{f.label ?? f.id}</option>
                ))}
              </select>
            </label>
            <IdeButton
              tone="ghost"
              onClick={() => onPulse(pulseSignal || inputFields[0]!.id)}
              testId="ide-verify-pulse-btn"
              disabled={inputFields.length === 0}
            >
              Pulse
            </IdeButton>
          </div>
        )}
      </details>

      {/* ── Sweep generator ── */}
      <details className="ide-verify-sweep-details">
        <summary className="ide-verify-sweep-summary">Sweep generator</summary>
        <div className="ide-verify-sweep-controls" data-testid="ide-verify-sweep-controls">
          <label className="ide-verify-field">
            Sweep preset
            <select
              className="ide-export-pin-input"
              value={sweepPreset}
              onChange={(event) =>
                onSweepPresetChange(
                  event.target.value === 'toggle-sw0'
                    ? 'toggle-sw0'
                    : event.target.value === 'walk-one-hot'
                      ? 'walk-one-hot'
                      : 'binary-count'
                )
              }
              data-testid="ide-verify-sweep-preset"
            >
              <option value="binary-count">Binary count SW[3:0]</option>
              <option value="toggle-sw0">Toggle SW0</option>
              <option value="walk-one-hot">One-hot walk</option>
            </select>
          </label>
          <label className="ide-verify-field">
            Seed
            <input
              type="number"
              className="ide-export-pin-input"
              value={sweepSeed}
              onChange={(event) => onSweepSeedChange(event.target.value)}
              data-testid="ide-verify-sweep-seed"
            />
          </label>
          <label className="ide-verify-field">
            Hold ticks
            <input
              type="number"
              className="ide-export-pin-input"
              min={1}
              step={1}
              value={sweepHoldTicks}
              onChange={(event) =>
                onSweepHoldTicksChange(Math.max(1, Number(event.target.value || '1')))
              }
              data-testid="ide-verify-sweep-hold"
            />
          </label>
          <IdeButton
            tone="secondary"
            onClick={onGenerateSweep}
            testId="ide-verify-generate-sweep-vectors"
          >
            Generate Sweep
          </IdeButton>
        </div>
      </details>
    </div>
  );

  if (isFirstRun) {
    const hasVectorsReady = hasVectors && !isUsingFallbackSignals;
    const calloutTitle = hasVectors
      ? 'Run Verify on the current vectors'
      : 'Start with a small vector set';

    return (
      <div
        className="ide-verify-scenario-builder-details ide-verify-scenario-builder-details--first-run"
        data-testid="ide-verify-empty-state"
      >
        {/* ── Testbench zone header ── */}
        <div className="ide-verify-testbench-zone-header">
          <span className="ide-verify-empty-label">Testbench</span>
          {hasVectors && !isUsingFallbackSignals && (
            <span className="ide-verify-testbench-vector-count">
              {effectiveVectorCount} vector{effectiveVectorCount !== 1 ? 's' : ''}
            </span>
          )}
          <span className="ide-verify-empty-hint" data-testid="ide-verify-empty-message">
            {isUsingFallbackSignals
              ? 'Map your circuit I/O before authoring a real testbench.'
              : hasVectors
                ? showsAssertedExpectedCells
                  ? 'Edit cells to refine this testbench. Only asserted expected cells will be checked when you run compare.'
                  : 'Edit cells to refine this testbench. Add expected outputs when you want Compare to check them.'
                : 'Click cells to build a testbench. Add expected outputs when you want Compare to check them.'}
          </span>
        </div>

        {/* ── Unmapped signal warning — shown when circuit has no real I/O ── */}
        {isUsingFallbackSignals && (
          <div className="ide-verify-sync-warning" data-testid="ide-verify-sync-warning">
            <span className="ide-verify-sync-warning-icon">⚠</span>
            <span className="ide-verify-sync-warning-text">
              Your circuit has no mapped inputs yet. The rows below are placeholders — go to{' '}
              <strong>Hardware</strong> to map your circuit's actual signals, then come back to
              author test vectors against your real design.
            </span>
            {onGoToHardware && (
              <IdeButton tone="ghost" onClick={onGoToHardware} testId="ide-verify-sync-go-hardware">
                Open Hardware →
              </IdeButton>
            )}
          </div>
        )}

        {/* ── PRIMARY: StimulusCanvas — fills all available height ── */}
        {preRunCanvas}

        {/* ── Callout kept in DOM for gate contracts, visually hidden ── */}
        <div style={{ display: 'none' }}>
          <IdeCallout tone="info" title={calloutTitle} testId="ide-verify-first-run-callout">
            <p className="ide-copy" style={{ margin: 0 }}>
              {hasVectors
                ? showsAssertedExpectedCells
                  ? 'Run Compare checks only the asserted expected cells.'
                  : 'Run this testbench first. Waveform inspection and capture tools stay available after you have real evidence.'
                : 'Generate a starter set now, or use the timeline plus row and tick tools to author your own stimulus pattern.'}
            </p>
          </IdeCallout>
        </div>

        {/* ── FOOTER: Run action strip ── */}
        <div className="ide-verify-run-footer" data-testid="ide-verify-workstation-run-bar">
          <div className="ide-verify-run-footer-status">
            {hasVectors && !isUsingFallbackSignals ? (
              <span className="ide-verify-run-footer-ready">
                {effectiveVectorCount} vector{effectiveVectorCount !== 1 ? 's' : ''} {showsAssertedExpectedCells ? 'ready for compare' : 'ready to run'}
              </span>
            ) : (
              <span className="ide-verify-run-footer-hint">
                {isUsingFallbackSignals ? 'Map I/O first' : 'Build the first testbench'}
              </span>
            )}
          </div>
          <div className="ide-verify-run-footer-actions">
            {hasVectorsReady ? (
              <span data-testid="ide-verify-empty-run">
                <IdeButton tone="primary" onClick={onRun} testId="ide-verify-run">
                  {runButtonLabel}
                </IdeButton>
              </span>
            ) : (
              <IdeButton
                tone="primary"
                onClick={onGenerateBasics}
                testId="ide-verify-generate-basic-vectors-footer"
              >
                Generate Basics
              </IdeButton>
            )}
            <IdeButton tone="ghost" onClick={onOpenProjectVectors} testId="ide-verify-empty-open-vectors">
              Open vectors
            </IdeButton>
          </div>
        </div>
      </div>
    );
  }

  // Post-run: collapsed by default so waveform dominates; user opens to edit
  return (
    <details className="ide-verify-scenario-builder-details ide-verify-scenario-builder-details--postrun">
      <summary className="ide-verify-scenario-builder-summary">
        <span className="ide-verify-scenario-builder-summary-label">Testbench</span>
        {authoredVectors.length > 0 && (
          <span className="ide-verify-scenario-builder-count">
            {authoredVectors.length} vector{authoredVectors.length !== 1 ? 's' : ''}
          </span>
        )}
        <span className="ide-verify-scenario-builder-summary-cue" aria-hidden="true">Edit ›</span>
      </summary>
      {authoringForm}
    </details>
  );
};
