import React from 'react';
import { IdeButton, IdeCallout } from '../components/IdePrimitives';
import {
  StimulusCanvas,
  type StimulusClockLaneConfig,
} from '../components/StimulusCanvas';

export interface VerifyVectorDraftInput {
  id: string;
  label: string;
  pin?: string;
}

export interface VerifyAuthorVector {
  id: string;
  tick: number;
  inputs: Record<string, 0 | 1>;
  expected: Record<string, 0 | 1>;
}

export type VerifyExpectedDraftValue = '' | '0' | '1';
export type SweepPreset = 'binary-count' | 'toggle-sw0' | 'walk-one-hot';

export interface ScenarioBuilderPanelProps {
  inputFields: VerifyVectorDraftInput[];
  outputFields: VerifyVectorDraftInput[];
  authoredVectors: VerifyAuthorVector[];
  totalVectorCount?: number;
  hasAssertedExpectedCells?: boolean;
  selectedTick?: number | null;
  onSelectedTickChange?: (tick: number) => void;
  onVectorsChange?: (vectors: VerifyAuthorVector[]) => void;
  draftTick: number;
  draftInputs: Record<string, '0' | '1'>;
  draftExpected: Record<string, VerifyExpectedDraftValue>;
  onDraftTickChange: (tick: number) => void;
  onDraftInputChange: (fieldId: string, value: '0' | '1') => void;
  onDraftExpectedChange: (fieldId: string, value: VerifyExpectedDraftValue) => void;
  onAddVector: () => void;
  onGenerateBasics: () => void;
  onRun?: () => void;
  runButtonLabel?: string;
  onOpenProjectVectors: () => void;
  onAutoGenerate: () => void;
  sweepPreset: SweepPreset;
  sweepSeed: string;
  sweepHoldTicks: number;
  onSweepPresetChange: (preset: SweepPreset) => void;
  onSweepSeedChange: (seed: string) => void;
  onSweepHoldTicksChange: (ticks: number) => void;
  onGenerateSweep: () => void;
  holdN: number;
  onHoldNChange: (n: number) => void;
  onHoldN: (n: number) => void;
  pulseSignal: string;
  onPulseSignalChange: (id: string) => void;
  onPulse: (signalId: string) => void;
  vectorsAreAutoGenerated: boolean;
  autoVectorBannerDismissed: boolean;
  onDismissAutoVectorBanner: () => void;
  isFirstRun: boolean;
  isSequential?: boolean;
  isUsingFallbackSignals?: boolean;
  onGoToHardware?: () => void;
  detailsRef?: React.RefObject<HTMLElement | null>;
  initialExpanded?: boolean;
  workbenchExpanded?: boolean;
  onWorkbenchExpandedChange?: (expanded: boolean) => void;
  allowWorkbenchCollapse?: boolean;
  clockLane?: StimulusClockLaneConfig;
  stimulusAssist?: React.ReactNode;
  runSummary?: React.ReactNode;
}

export const ScenarioBuilderPanel: React.FC<ScenarioBuilderPanelProps> = ({
  inputFields,
  outputFields,
  authoredVectors,
  totalVectorCount,
  hasAssertedExpectedCells,
  selectedTick,
  onSelectedTickChange,
  onVectorsChange,
  onGenerateBasics,
  onOpenProjectVectors,
  onAutoGenerate,
  sweepPreset,
  sweepSeed,
  sweepHoldTicks,
  onSweepPresetChange,
  onSweepSeedChange,
  onSweepHoldTicksChange,
  onGenerateSweep,
  vectorsAreAutoGenerated,
  autoVectorBannerDismissed,
  onDismissAutoVectorBanner,
  isFirstRun,
  isUsingFallbackSignals = false,
  onGoToHardware,
  detailsRef,
  initialExpanded,
  workbenchExpanded,
  onWorkbenchExpandedChange,
  allowWorkbenchCollapse = true,
  clockLane,
  stimulusAssist,
  runSummary,
}) => {
  const effectiveVectorCount = totalVectorCount ?? authoredVectors.length;
  const hasVectors = effectiveVectorCount > 0;
  const starterInputCount = inputFields.filter((field) => field.id !== clockLane?.fieldId).length;
  const showsAssertedExpectedCells =
    hasAssertedExpectedCells ??
    authoredVectors.some((vector) => Object.keys(vector.expected ?? {}).length > 0);
  const canAutoGenerate = starterInputCount > 0 && starterInputCount <= 6;
  const selectedTickLabel = selectedTick != null ? `t${selectedTick}` : 'No case selected';
  const hasVectorsReady = hasVectors && !isUsingFallbackSignals;

  const secondaryTools = (
    <>
      <div className="ide-stimulus-toolbar-group" data-testid="ide-stimulus-project-vectors-tools">
        <span className="ide-stimulus-toolbar-label">Project vectors</span>
        <button
          type="button"
          className="ide-stimulus-mini-btn"
          onClick={onOpenProjectVectors}
          data-testid="ide-verify-open-project-vectors"
        >
          Open vectors
        </button>
      </div>
      {canAutoGenerate ? (
        <div className="ide-stimulus-toolbar-group" data-testid="ide-stimulus-starter-tools">
          <span className="ide-stimulus-toolbar-label">Starter</span>
          <button
            type="button"
            className="ide-stimulus-mini-btn"
            onClick={onAutoGenerate}
            data-testid="ide-verify-autogen-btn"
          >
            Auto-fill {1 << starterInputCount} combos
          </button>
        </div>
      ) : null}
      <div className="ide-stimulus-toolbar-group" data-testid="ide-stimulus-sweep-tools">
        <span className="ide-stimulus-toolbar-label">Sweep</span>
        <select
          className="ide-stimulus-target-select"
          value={sweepPreset}
          onChange={(event) =>
            onSweepPresetChange(
              event.target.value === 'toggle-sw0'
                ? 'toggle-sw0'
                : event.target.value === 'walk-one-hot'
                  ? 'walk-one-hot'
                  : 'binary-count'
            )
          }
          data-testid="ide-verify-sweep-preset"
        >
          <option value="binary-count">Binary count SW[3:0]</option>
          <option value="toggle-sw0">Toggle SW0</option>
          <option value="walk-one-hot">One-hot walk</option>
        </select>
        <input
          type="number"
          className="ide-stimulus-target-select"
          value={sweepSeed}
          onChange={(event) => onSweepSeedChange(event.target.value)}
          data-testid="ide-verify-sweep-seed"
          aria-label="Sweep seed"
        />
        <input
          type="number"
          className="ide-stimulus-target-select"
          min={1}
          step={1}
          value={sweepHoldTicks}
          onChange={(event) =>
            onSweepHoldTicksChange(Math.max(1, Number(event.target.value || '1')))
          }
          data-testid="ide-verify-sweep-hold"
          aria-label="Sweep hold ticks"
        />
        <button
          type="button"
          className="ide-stimulus-mini-btn"
          onClick={onGenerateSweep}
          data-testid="ide-verify-generate-sweep-vectors"
        >
          Generate sweep
        </button>
      </div>
    </>
  );

  const stimulusCanvas = (
    <div
      className="ide-verify-vector-form ide-verify-vector-form--canvas-only"
      data-testid="ide-verify-add-vector-form"
    >
      {onVectorsChange != null ? (
        <StimulusCanvas
          inputFields={inputFields}
          outputFields={outputFields}
          authoredVectors={authoredVectors}
          onVectorsChange={onVectorsChange}
          initialScrollTarget="top"
          selectedTick={selectedTick ?? undefined}
          onSelectedTickChange={onSelectedTickChange}
          hasSavedExpectedOutputs={showsAssertedExpectedCells}
          clockLane={clockLane}
          secondaryTools={secondaryTools}
        />
      ) : (
        <p className="ide-verify-section-subheader" style={{ padding: '12px' }}>
          No canvas — wire onVectorsChange to enable editing.
        </p>
      )}
      <div style={{ display: 'none' }}>
        <IdeButton
          tone="secondary"
          onClick={onGenerateBasics}
          testId="ide-verify-generate-basic-vectors"
        >
          Generate starter testbench
        </IdeButton>
      </div>
    </div>
  );

  if (isFirstRun) {
    const calloutTitle = hasVectors
      ? 'Run Verify on the current vectors'
      : 'Start with a small vector set';

    return (
      <div
        className="ide-verify-scenario-builder-details ide-verify-scenario-builder-details--first-run"
        data-testid="ide-verify-empty-state"
      >
        <div className="ide-verify-testbench-zone-header">
          <span className="ide-verify-empty-label">Build testbench</span>
          {hasVectors && !isUsingFallbackSignals ? (
            <span className="ide-verify-testbench-vector-count">
              {effectiveVectorCount} vector{effectiveVectorCount !== 1 ? 's' : ''}
            </span>
          ) : null}
          <span className="ide-verify-empty-hint" data-testid="ide-verify-empty-message">
            {isUsingFallbackSignals
              ? 'Map your circuit I/O before authoring a real testbench.'
              : hasVectors
                ? 'Edit input stimulus, clock edges, and expected outputs in one table.'
                : 'Click cells to build input stimulus, add a rising edge, and set expected outputs inline.'}
          </span>
        </div>

        {stimulusAssist ? (
          <div className="ide-verify-stimulus-assist-slot">{stimulusAssist}</div>
        ) : null}
        {runSummary ? <div className="ide-verify-run-summary-slot">{runSummary}</div> : null}

        {isUsingFallbackSignals ? (
          <div className="ide-verify-sync-warning" data-testid="ide-verify-sync-warning">
            <span className="ide-verify-sync-warning-icon">⚠</span>
            <span className="ide-verify-sync-warning-text">
              Your circuit has no mapped inputs yet. The rows below are placeholders — go to{' '}
              <strong>Hardware</strong> to map your circuit&apos;s actual signals, then come back to
              author test vectors against your real design.
            </span>
            {onGoToHardware ? (
              <IdeButton
                tone="ghost"
                onClick={onGoToHardware}
                testId="ide-verify-sync-go-hardware"
              >
                Open Hardware →
              </IdeButton>
            ) : null}
          </div>
        ) : null}

        {stimulusCanvas}

        <div style={{ display: 'none' }}>
          <IdeCallout tone="info" title={calloutTitle} testId="ide-verify-first-run-callout">
            <p className="ide-copy" style={{ margin: 0 }}>
              {hasVectors
                ? showsAssertedExpectedCells
                  ? 'Run the current stimulus and inspect outputs on the waveform. Compare only checks the expected-output cells you filled in.'
                  : 'Run this stimulus first. Waveform inspection and capture tools stay available after you have real evidence.'
                : 'Generate a starter set now, or use the timeline plus row and tick tools to author input stimulus first.'}
            </p>
          </IdeCallout>
        </div>

        <div className="ide-verify-run-footer" data-testid="ide-verify-workstation-run-bar">
          <div className="ide-verify-run-footer-status">
            {hasVectorsReady ? (
              <span className="ide-verify-run-footer-ready">
                {effectiveVectorCount} vector{effectiveVectorCount !== 1 ? 's' : ''}{' '}
                {showsAssertedExpectedCells ? 'ready for stimulus or checks' : 'ready for stimulus'}
              </span>
            ) : (
              <span className="ide-verify-run-footer-hint">
                {isUsingFallbackSignals ? 'Map I/O first' : 'Build the first testbench'}
              </span>
            )}
          </div>
          <div className="ide-verify-run-footer-actions">
            {!hasVectorsReady ? (
              <IdeButton
                tone="primary"
                onClick={onGenerateBasics}
                testId="ide-verify-generate-basic-vectors-footer"
              >
                Generate starter testbench
              </IdeButton>
            ) : null}
            <IdeButton
              tone="ghost"
              onClick={onOpenProjectVectors}
              testId="ide-verify-empty-open-vectors"
            >
              Open Project vectors
            </IdeButton>
          </div>
        </div>
      </div>
    );
  }

  const [uncontrolledWorkbenchExpanded, setUncontrolledWorkbenchExpanded] = React.useState(
    () => initialExpanded ?? !isFirstRun
  );
  const usesControlledWorkbenchState = typeof workbenchExpanded === 'boolean';
  const controlledWorkbenchExpanded = usesControlledWorkbenchState
    ? workbenchExpanded
    : uncontrolledWorkbenchExpanded;
  const effectiveWorkbenchExpanded = allowWorkbenchCollapse
    ? controlledWorkbenchExpanded
    : true;

  const updateWorkbenchExpanded = React.useCallback(
    (expanded: boolean) => {
      if (!usesControlledWorkbenchState) {
        setUncontrolledWorkbenchExpanded(expanded);
      }
      onWorkbenchExpandedChange?.(expanded);
    },
    [onWorkbenchExpandedChange, usesControlledWorkbenchState]
  );

  React.useEffect(() => {
    if (!usesControlledWorkbenchState) {
      setUncontrolledWorkbenchExpanded(initialExpanded ?? !isFirstRun);
    }
  }, [initialExpanded, isFirstRun, usesControlledWorkbenchState]);

  const handleWorkbenchHeaderToggle = () => {
    if (!allowWorkbenchCollapse) return;
    updateWorkbenchExpanded(!effectiveWorkbenchExpanded);
  };

  const handleWorkbenchHeaderKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key !== 'Enter' && event.key !== ' ') return;
    event.preventDefault();
    handleWorkbenchHeaderToggle();
  };

  const collapsedWorkbenchSummary = showsAssertedExpectedCells
    ? 'Stimulus is tucked away. Reopen to edit cases, clock edges, or saved checks.'
    : 'Stimulus is tucked away. Reopen to edit cases or bring in project vectors without leaving the waveform.';

  return (
    <section
      className="ide-verify-scenario-builder-details ide-verify-scenario-builder-details--postrun ide-verify-workbench-live"
      data-testid="ide-verify-stimulus-workbench"
      data-state={effectiveWorkbenchExpanded ? 'expanded' : 'collapsed'}
      ref={detailsRef}
    >
      <div
        className="ide-verify-scenario-builder-summary ide-verify-workbench-header"
        data-testid="ide-verify-workbench-toggle"
        role={allowWorkbenchCollapse ? 'button' : undefined}
        tabIndex={allowWorkbenchCollapse ? 0 : undefined}
        aria-expanded={allowWorkbenchCollapse ? effectiveWorkbenchExpanded : undefined}
        onClick={(event) => {
          event.preventDefault();
          if (allowWorkbenchCollapse) {
            handleWorkbenchHeaderToggle();
          }
        }}
        onKeyDown={handleWorkbenchHeaderKeyDown}
      >
        <div className="ide-verify-workbench-header-main">
          <span className="ide-verify-workbench-toggle-arrow" aria-hidden="true">
            {effectiveWorkbenchExpanded ? '▼' : '▸'}
          </span>
          <div className="ide-verify-workbench-title-group">
            <span className="ide-verify-workbench-toggle-label">Build testbench</span>
            <span
              className="ide-verify-workbench-toggle-copy"
              data-testid="ide-verify-workbench-summary-copy"
            >
              Clock, stimulus, checks, then run Compare.
            </span>
          </div>
        </div>
        <div className="ide-verify-workbench-header-meta">
          {authoredVectors.length > 0 ? (
            <span className="ide-verify-workbench-count">
              {authoredVectors.length} vector{authoredVectors.length !== 1 ? 's' : ''}
            </span>
          ) : null}
          <span
            className="ide-verify-workbench-count is-selected"
            data-testid="ide-verify-workbench-selected-tick"
          >
            {selectedTickLabel}
          </span>
        </div>
      </div>

      {!effectiveWorkbenchExpanded ? (
        <div
          className="ide-verify-workbench-collapsed-strip"
          data-testid="ide-verify-workbench-collapsed-strip"
        >
          <div className="ide-verify-workbench-collapsed-copy">
            <span className="ide-verify-workbench-collapsed-label">Waveform focus</span>
            <p className="ide-verify-workbench-collapsed-summary">{collapsedWorkbenchSummary}</p>
          </div>
          <div className="ide-verify-workbench-collapsed-actions">
            <IdeButton
              tone="secondary"
              onClick={() => updateWorkbenchExpanded(true)}
              testId="ide-verify-workbench-reopen"
            >
              Edit cases
            </IdeButton>
            <IdeButton
              tone="ghost"
              onClick={onOpenProjectVectors}
              testId="ide-verify-workbench-open-vectors"
            >
              Project vectors
            </IdeButton>
          </div>
        </div>
      ) : null}

      {effectiveWorkbenchExpanded && vectorsAreAutoGenerated && !autoVectorBannerDismissed ? (
        <div className="ide-verify-workbench-banner-row">
          <span
            className="ide-verify-auto-vector-pill"
            data-testid="ide-verify-auto-vector-notice"
          >
            auto-generated starter cases
            <button
              type="button"
              className="ide-verify-auto-vector-pill-dismiss"
              data-testid="ide-verify-auto-vector-dismiss"
              onClick={(event) => {
                event.preventDefault();
                event.stopPropagation();
                onDismissAutoVectorBanner();
              }}
            >
              Dismiss
            </button>
          </span>
        </div>
      ) : null}

      {effectiveWorkbenchExpanded ? (
        <div className="ide-verify-workbench-body" data-testid="ide-verify-workbench-body">
          {stimulusAssist ? (
            <div className="ide-verify-stimulus-assist-slot ide-verify-stimulus-assist-slot--inline">
              {stimulusAssist}
            </div>
          ) : null}
          {runSummary ? (
            <div className="ide-verify-run-summary-slot ide-verify-run-summary-slot--inline">
              {runSummary}
            </div>
          ) : null}
          {stimulusCanvas}
        </div>
      ) : null}
    </section>
  );
};
