/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./packages/*/src/**/*.{js,ts,jsx,tsx}",
    "./apps/*/src/**/*.{js,ts,jsx,tsx}"
  ],
  safelist: [
    // Ensure core utilities are always included
    {
      pattern: /(bg|text|border)-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)/,
    },
    {
      pattern: /(bg|text|border)-(black|white|transparent)/,
    },
    {
      pattern: /(inset|top|right|bottom|left)-(0|1|2|3|4|5|6|8|10|12|16|20|24|32|40|48|56|64)/,
    },
    {
      pattern: /w-(full|screen|1\/2|auto|px|0|1|2|3|4|5|6|8|10|12|16|20|24|32|40|48|56|64)/,
    },
    {
      pattern: /h-(full|screen|auto|px|0|1|2|3|4|5|6|8|10|12|16|20|24|32|40|48|56|64)/,
    },
    {
      pattern: /(p|m|px|py|mx|my|mt|mb|ml|mr|pt|pb|pl|pr)-(0|1|2|3|4|5|6|8|10|12|16|20|24|32)/,
    },
    'absolute',
    'relative',
    'fixed',
    'inset-0',
    'flex',
    'flex-col',
    'flex-row',
    'items-center',
    'items-start',
    'items-end',
    'justify-center',
    'justify-between',
    'justify-start',
    'justify-end',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'space-x-2',
    'space-y-2',
    'rounded',
    'rounded-lg',
    'rounded-md',
    'rounded-full',
    'shadow',
    'shadow-lg',
    'shadow-xl',
    'pointer-events-none',
    'cursor-pointer',
    'cursor-move',
    'select-none',
    'transition-transform',
    'transition-colors',
    'duration-150',
    'duration-200',
    'scale-105',
    'opacity-50',
    'opacity-70',
    'opacity-80',
    'text-white',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'overflow-hidden',
    'overflow-auto',
    'truncate',
    'whitespace-nowrap',
    'bg-gradient-to-b',
    'from-transparent',
    'via-black/10',
    'to-black/30',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
