import React, { useMemo, useState } from 'react';
import { IdeButton } from '../../components/IdePrimitives';

// Case Lab — the combinational simulation instrument. A single editable
// truth-table grid: one row per test case, input columns, expected/observed
// output columns, and a per-case verdict. This replaces the card-per-event
// composition: the shape of the data is a table, so the instrument is a table.

type Field = { readonly id: string; readonly label?: string };
type Vector = {
  readonly id?: string;
  readonly tick: number;
  readonly inputs: Record<string, number>;
  readonly expected?: Record<string, unknown>;
};
export type CaseEvidence = 'not-run' | 'stale' | 'observed' | 'pass' | 'fail';

export interface CaseLabProps {
  readonly inputFields: readonly Field[];
  readonly outputFields: readonly Field[];
  readonly vectors: readonly Vector[];
  readonly observedByTick: Record<number, Record<string, string>>;
  readonly caseEvidenceByTick: Record<number, CaseEvidence>;
  readonly selectedTick: number | null;
  readonly onSelectCase: (tick: number) => void;
  readonly onSetExpected: (tick: number, signalId: string, next: 0 | 1 | null) => void;
  readonly onGenerateExhaustive?: () => void;
  readonly onAddCase?: () => void;
  readonly onDuplicateCase?: (tick: number) => void;
  readonly onDeleteCase?: (tick: number) => void;
  readonly onRun?: () => void;
  readonly runLabel?: string;
  readonly runDisabled?: boolean;
  readonly onTraceCase?: (tick: number) => void;
  /** The cases were generated from the circuit's inputs, not authored by hand. */
  readonly vectorsAreAutoGenerated?: boolean;
  readonly autoVectorNoticeDismissed?: boolean;
  readonly onDismissAutoVectorNotice?: () => void;
  /** No mapped inputs exist yet: the input columns are placeholders until Board maps real signals. */
  readonly isUsingFallbackSignals?: boolean;
  readonly onGoToHardware?: () => void;
}

const VERDICT_LABEL: Record<CaseEvidence, string> = {
  'not-run': '—',
  stale: 'stale',
  observed: 'observed',
  pass: 'pass',
  fail: 'fail',
};

function asBit(value: unknown): '0' | '1' | '' {
  if (value === 1 || value === '1') return '1';
  if (value === 0 || value === '0') return '0';
  return '';
}

/** Numeric value of a case's inputs, MSB = first input field, for stable ordering. */
function comboValue(vector: Vector, inputFields: readonly Field[]): number {
  return inputFields.reduce(
    (acc, field, index) => acc + ((vector.inputs[field.id] ? 1 : 0) << (inputFields.length - 1 - index)),
    0
  );
}

export const CaseLab: React.FC<CaseLabProps> = ({
  inputFields,
  outputFields,
  vectors,
  observedByTick,
  caseEvidenceByTick,
  selectedTick,
  onSelectCase,
  onSetExpected,
  onGenerateExhaustive,
  onAddCase,
  onDuplicateCase,
  onDeleteCase,
  onRun,
  runLabel,
  runDisabled,
  onTraceCase,
  vectorsAreAutoGenerated,
  autoVectorNoticeDismissed,
  onDismissAutoVectorNotice,
  isUsingFallbackSignals,
  onGoToHardware,
}) => {
  const [failuresOnly, setFailuresOnly] = useState(false);
  const orderedTicks = useMemo(() => [...vectors].map((vector) => vector.tick).sort((a, b) => a - b), [vectors]);
  const failingTicks = useMemo(() => orderedTicks.filter((tick) => caseEvidenceByTick[tick] === 'fail'), [caseEvidenceByTick, orderedTicks]);
  const stepCase = (direction: 1 | -1) => {
    if (orderedTicks.length === 0) return;
    const index = selectedTick == null ? -1 : orderedTicks.indexOf(selectedTick);
    const next = orderedTicks[Math.min(orderedTicks.length - 1, Math.max(0, index + direction))];
    if (next != null && next !== selectedTick) onSelectCase(next);
  };
  const stepFailure = (direction: 1 | -1) => {
    if (failingTicks.length === 0) return;
    const index = selectedTick == null ? -1 : failingTicks.indexOf(selectedTick);
    const next = failingTicks[(index + direction + failingTicks.length) % failingTicks.length] ?? failingTicks[0];
    onSelectCase(next);
  };

  const failCount = useMemo(
    () => vectors.filter((v) => caseEvidenceByTick[v.tick] === 'fail').length,
    [vectors, caseEvidenceByTick]
  );

  const rows = useMemo(() => {
    const sorted = [...vectors].sort(
      (a, b) => comboValue(a, inputFields) - comboValue(b, inputFields) || a.tick - b.tick
    );
    return failuresOnly ? sorted.filter((v) => caseEvidenceByTick[v.tick] === 'fail') : sorted;
  }, [vectors, inputFields, failuresOnly, caseEvidenceByTick]);

  const cycleExpected = (tick: number, signalId: string, current: '0' | '1' | '') => {
    // First click asserts the common case (1), second flips to 0, third clears the check.
    onSetExpected(tick, signalId, current === '' ? 1 : current === '1' ? 0 : null);
  };

  return (
    <section className="ide-case-lab" data-testid="ide-case-lab">
      <header className="ide-case-lab-bar" data-testid="ide-case-lab-bar">
        <span className="ide-case-lab-title" data-testid="ide-case-lab-title">Test cases</span>
        <span className="ide-case-lab-count" data-testid="ide-case-lab-count">
          {vectors.length} case{vectors.length === 1 ? '' : 's'}
          {failCount ? ` · ${failCount} failing` : ''}
        </span>
        <span className="ide-case-lab-spacer" />
        {onAddCase ? (
          <IdeButton tone="ghost" onClick={onAddCase} testId="ide-case-lab-add">
            Add case
          </IdeButton>
        ) : null}
        {onGenerateExhaustive ? (
          <IdeButton tone="ghost" onClick={onGenerateExhaustive} testId="ide-case-lab-generate">
            Generate all
          </IdeButton>
        ) : null}
        <button
          type="button"
          className={`ide-case-lab-filter${failuresOnly ? ' is-active' : ''}`}
          onClick={() => setFailuresOnly((prev) => !prev)}
          disabled={failCount === 0}
          aria-pressed={failuresOnly}
          data-testid="ide-case-lab-failures-only"
        >
          Failures only
        </button>
        <button
          type="button"
          className="wb-btn wb-btn--ghost"
          onClick={() => stepFailure(-1)}
          disabled={failingTicks.length === 0}
          data-testid="ide-case-lab-prev-failure"
          title="Select the previous failing case"
        >
          ‹ Fail
        </button>
        <button
          type="button"
          className="wb-btn wb-btn--ghost"
          onClick={() => stepFailure(1)}
          disabled={failingTicks.length === 0}
          data-testid="ide-case-lab-next-failure"
          title="Select the next failing case"
        >
          Fail ›
        </button>
      </header>

      {vectorsAreAutoGenerated && !autoVectorNoticeDismissed ? (
        <div className="ide-case-lab-note" data-testid="ide-verify-auto-vector-notice">
          <span>auto-generated starter cases</span>
          {onDismissAutoVectorNotice ? (
            <button type="button" className="ide-case-lab-note-dismiss" data-testid="ide-verify-auto-vector-dismiss" onClick={onDismissAutoVectorNotice}>
              Dismiss
            </button>
          ) : null}
        </div>
      ) : null}
      {isUsingFallbackSignals ? (
        <div className="ide-case-lab-note is-warn" data-testid="ide-verify-sync-warning">
          <span>No mapped inputs yet — these input columns are placeholders until Board &amp; Constraints maps the circuit's signals.</span>
          {onGoToHardware ? (
            <button type="button" className="ide-case-lab-note-dismiss" data-testid="ide-verify-sync-go-hardware" onClick={onGoToHardware}>
              Open Board
            </button>
          ) : null}
        </div>
      ) : null}
      <div className="ide-case-lab-scroll">
        <table
          className="ide-case-lab-table"
          data-testid="ide-case-lab-table"
          tabIndex={0}
          aria-label="Test cases — arrow keys move the selected case, F steps to the next failure"
          onKeyDown={(event) => {
            if (event.key === 'ArrowDown') { event.preventDefault(); stepCase(1); }
            else if (event.key === 'ArrowUp') { event.preventDefault(); stepCase(-1); }
            else if (event.key === 'Home') { event.preventDefault(); if (orderedTicks[0] != null) onSelectCase(orderedTicks[0]); }
            else if (event.key === 'End') { event.preventDefault(); const last = orderedTicks[orderedTicks.length - 1]; if (last != null) onSelectCase(last); }
            else if (event.key === 'f' || event.key === 'F') { event.preventDefault(); stepFailure(event.shiftKey ? -1 : 1); }
          }}
        >
          <thead>
            <tr className="ide-case-lab-grouphead">
              <th className="ide-case-lab-num" rowSpan={2} scope="col">#</th>
              <th className="ide-case-lab-group ide-case-lab-group--in" colSpan={inputFields.length} scope="colgroup">
                Inputs
              </th>
              {outputFields.map((field) => (
                <th
                  key={field.id}
                  className="ide-case-lab-group ide-case-lab-group--out"
                  colSpan={2}
                  scope="colgroup"
                >
                  {field.label ?? field.id}
                </th>
              ))}
              <th className="ide-case-lab-result" rowSpan={2} scope="col">Result</th>
            </tr>
            <tr className="ide-case-lab-colhead">
              {inputFields.map((field) => (
                <th key={field.id} className="ide-case-lab-in" scope="col">{field.label ?? field.id}</th>
              ))}
              {outputFields.map((field) => (
                <React.Fragment key={field.id}>
                  <th className="ide-case-lab-exp" scope="col">exp</th>
                  <th className="ide-case-lab-obs" scope="col">obs</th>
                </React.Fragment>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.length === 0 ? (
              <tr>
                <td className="ide-case-lab-empty" colSpan={2 + inputFields.length + outputFields.length * 2}>
                  {failuresOnly ? 'No failing cases.' : 'No cases yet — Generate all to enumerate every input combination.'}
                </td>
              </tr>
            ) : (
              rows.map((vector, index) => {
                const evidence = caseEvidenceByTick[vector.tick] ?? 'not-run';
                const isSelected = vector.tick === selectedTick;
                return (
                  <tr
                    key={vector.id ?? vector.tick}
                    className={`ide-case-lab-row is-${evidence}${isSelected ? ' is-selected' : ''}`}
                    data-testid={`ide-case-lab-row-${vector.tick}`}
                    aria-selected={isSelected}
                    onClick={() => onSelectCase(vector.tick)}
                  >
                    <td className="ide-case-lab-num">{index}</td>
                    {inputFields.map((field) => (
                      <td key={field.id} className="ide-case-lab-in">
                        <code>{asBit(vector.inputs[field.id]) || '0'}</code>
                      </td>
                    ))}
                    {outputFields.map((field) => {
                      const exp = asBit(vector.expected?.[field.id]);
                      const obs = asBit(observedByTick[vector.tick]?.[field.id]);
                      const cellFail = evidence === 'fail' && exp !== '' && obs !== '' && exp !== obs;
                      return (
                        <React.Fragment key={field.id}>
                          <td className="ide-case-lab-exp">
                            <button
                              type="button"
                              className={`ide-case-lab-exp-btn${exp ? ' is-set' : ''}`}
                              data-testid={`ide-case-lab-exp-${vector.tick}-${field.id}`}
                              title={`Expected ${field.label ?? field.id} — click to set 0 / 1 / none`}
                              onClick={(event) => {
                                event.stopPropagation();
                                cycleExpected(vector.tick, field.id, exp);
                              }}
                            >
                              <code>{exp || '·'}</code>
                            </button>
                          </td>
                          <td className={`ide-case-lab-obs${cellFail ? ' is-fail' : ''}`}>
                            <code>{obs || '·'}</code>
                          </td>
                        </React.Fragment>
                      );
                    })}
                    <td className="ide-case-lab-result">
                      <span className={`ide-case-lab-verdict is-${evidence}`}>{VERDICT_LABEL[evidence]}</span>
                      {evidence === 'fail' && onTraceCase ? (
                        <button
                          type="button"
                          className="ide-case-lab-trace"
                          data-testid={`ide-case-lab-trace-${vector.tick}`}
                          onClick={(event) => {
                            event.stopPropagation();
                            onTraceCase(vector.tick);
                          }}
                        >
                          Trace
                        </button>
                      ) : null}
                      <span className="ide-case-lab-row-actions">
                        {onDuplicateCase ? (
                          <button
                            type="button"
                            className="ide-case-lab-rowbtn"
                            data-testid={`ide-case-lab-duplicate-${vector.tick}`}
                            title="Duplicate this case"
                            aria-label={`Duplicate case ${index + 1}`}
                            onClick={(event) => {
                              event.stopPropagation();
                              onDuplicateCase(vector.tick);
                            }}
                          >
                            ⧉
                          </button>
                        ) : null}
                        {onDeleteCase ? (
                          <button
                            type="button"
                            className="ide-case-lab-rowbtn ide-case-lab-rowbtn--danger"
                            data-testid={`ide-case-lab-delete-${vector.tick}`}
                            title="Delete this case"
                            aria-label={`Delete case ${index + 1}`}
                            onClick={(event) => {
                              event.stopPropagation();
                              onDeleteCase(vector.tick);
                            }}
                          >
                            ✕
                          </button>
                        ) : null}
                      </span>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
};
