import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  getToolchainBackend,
  getToolchainBackendId,
  type BuildLogEntry,
  type ToolchainBackendId,
  type ToolchainPreflightStatus,
  type ToolProbeResult,
  type ToolchainProjectInput,
  type SynthRunDoneSummary,
  type SynthArtifactRef,
  type ImplementRunDoneSummary,
  type ImplementArtifactRef,
  type ProgramRunDoneSummary,
  type ToolchainBuildPath,
} from '../fpga/toolchainBackend';
import type { RBFpgaConfig } from '../export/projectFormat';
import { stableStringify } from '../export/stableStringify';
import { basys3XdcPresets, getBasys3XdcPresetText, type Basys3XdcPresetId } from '../fpga/boards/basys3/presets';
import { basys3TopModuleContract } from '../fpga/boards/basys3/basys3Contract';
import {
  basys3VerilogExamples,
  getBasys3VerilogExample,
  type Basys3ExampleId,
} from '../fpga/boards/basys3/examples';
import { EmptyStateCard } from './EmptyStateCard';
import { SignalLegend } from './SignalLegend';
import { NEO_STATUS } from '../ui/neoGlossary';
import styles from './HdlEditorPanel.module.css';

interface HdlEditorPanelProps {
  project: ToolchainProjectInput;
  onProjectChange: (next: ToolchainProjectInput) => void;
  fpga?: RBFpgaConfig;
  onFpgaChange?: (next: RBFpgaConfig) => void;
  backendId?: ToolchainBackendId;
  beginnerView?: boolean;
}

function upsertSource(
  project: ToolchainProjectInput,
  path: string,
  patch: { language?: 'verilog' | 'vhdl'; text?: string }
): ToolchainProjectInput {
  const sources = Array.isArray(project.sources) ? project.sources : [];
  const idx = sources.findIndex((s) => s.path === path);
  const nextSources =
    idx >= 0
      ? sources.map((s, i) => (i === idx ? { ...s, ...patch } : s))
      : [
          ...sources,
          {
            path,
            language: patch.language ?? 'verilog',
            text: patch.text ?? '',
          },
        ];

  nextSources.sort((a, b) => a.path.localeCompare(b.path));
  return { ...project, sources: nextSources };
}

function normalizeXdcText(value: string): string {
  return value.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
}

function normalizeHdlSourcePath(value: string): string {
  const normalized = value.trim();
  return normalized.length > 0 ? normalized : 'top.v';
}

type SetupPlatformId = 'windows' | 'macos' | 'linux';

function normalizeSetupPlatform(value: string): SetupPlatformId {
  const lower = value.toLowerCase();
  if (lower.includes('win')) return 'windows';
  if (lower.includes('darwin') || lower.includes('mac')) return 'macos';
  return 'linux';
}

function getSetupCommands(platform: SetupPlatformId): Array<{ tool: string; command: string }> {
  if (platform === 'windows') {
    return [
      { tool: 'Vivado (stable backend)', command: 'Install Vivado WebPACK and ensure `vivado` is on PATH.' },
      { tool: 'Yosys', command: 'winget install YosysHQ.Yosys' },
      { tool: 'openFPGALoader', command: 'winget install trabucayre.openFPGALoader' },
    ];
  }
  if (platform === 'macos') {
    return [
      { tool: 'Vivado (stable backend)', command: 'Install Vivado WebPACK and export XILINX_VIVADO in your shell profile.' },
      { tool: 'Yosys', command: 'brew install yosys' },
      { tool: 'openFPGALoader', command: 'brew install openfpgaloader' },
    ];
  }
  return [
    { tool: 'Vivado (stable backend)', command: 'Install Vivado WebPACK and source settings64.sh before launching RedByte.' },
    { tool: 'Yosys', command: 'sudo apt-get install -y yosys' },
    { tool: 'openFPGALoader', command: 'sudo apt-get install -y openfpgaloader' },
  ];
}

const BASYS3_PART = 'xc7a35tcpg236-1';

function getVivadoAutoCandidates(platform: SetupPlatformId): string[] {
  if (platform === 'windows') {
    return [
      'vivado',
      'C:/Xilinx/Vivado/2025.1/bin/vivado.bat',
      'C:/Xilinx/Vivado/2024.2/bin/vivado.bat',
      'C:/Xilinx/Vivado/2024.1/bin/vivado.bat',
      'C:/Xilinx/Vivado/2023.2/bin/vivado.bat',
    ];
  }
  if (platform === 'macos') {
    return [
      'vivado',
      '/Applications/Xilinx/Vivado/2025.1/bin/vivado',
      '/Applications/Xilinx/Vivado/2024.2/bin/vivado',
      '/Applications/Xilinx/Vivado/2024.1/bin/vivado',
      '/Applications/Xilinx/Vivado/2023.2/bin/vivado',
    ];
  }
  return [
    'vivado',
    '/tools/Xilinx/Vivado/2025.1/bin/vivado',
    '/tools/Xilinx/Vivado/2024.2/bin/vivado',
    '/opt/Xilinx/Vivado/2024.2/bin/vivado',
    '/opt/Xilinx/Vivado/2024.1/bin/vivado',
  ];
}

function buildVivadoSynthCheckTcl(input: {
  part: string;
  topModule: string;
  topVhdlPath: string;
  xdcPath: string;
  outDir: string;
  projectName: string;
}): string {
  return [
    '# RedByte Vivado handoff (deterministic)',
    '# Generated by HdlEditorPanel',
    `set part "${input.part}"`,
    `set project_name "${input.projectName}"`,
    `set top_module "${input.topModule}"`,
    `set top_vhdl "${input.topVhdlPath}"`,
    `set top_xdc "${input.xdcPath}"`,
    `set out_dir "${input.outDir}"`,
    'set project_dir "$out_dir/project"',
    'set report_dir "$out_dir/reports"',
    'file mkdir $out_dir',
    'file mkdir $project_dir',
    'file mkdir $report_dir',
    'create_project -force $project_name $project_dir -part $part',
    'set_property target_language VHDL [current_project]',
    'add_files -norecurse [list $top_vhdl]',
    'set_property file_type {VHDL 2008} [get_files $top_vhdl]',
    'add_files -fileset constrs_1 -norecurse [list $top_xdc]',
    'set_property top $top_module [current_fileset]',
    'update_compile_order -fileset sources_1',
    'launch_runs synth_1 -jobs 4',
    'wait_on_run synth_1',
    'open_run synth_1',
    'report_utilization -file "$report_dir/utilization.rpt"',
    'report_timing_summary -file "$report_dir/timing.rpt"',
    'report_messages -file "$report_dir/messages.rpt"',
    'report_drc -file "$report_dir/drc.rpt"',
    'close_project',
    'exit',
    '',
  ].join('\n');
}

function extractXdcPorts(xdcText: string): string[] {
  return Array.from(
    new Set(
      [...xdcText.matchAll(/\[get_ports\s*\{([^}]+)\}\]/g)].map((match) => String(match[1] ?? '').trim()).filter(Boolean),
    ),
  );
}

function extractVhdlEntityPorts(vhdlText: string, entityName: string): string[] {
  const escapedEntity = entityName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const entityPattern = new RegExp(`entity\\s+${escapedEntity}\\s+is[\\s\\S]*?Port\\s*\\(([^]*?)\\);\\s*end\\s+entity`, 'i');
  const entityBlockMatch = vhdlText.match(entityPattern);
  if (!entityBlockMatch) return [];
  return Array.from(
    new Set(
      entityBlockMatch[1]
        .split(';')
        .map((entry) => entry.trim())
        .filter(Boolean)
        .map((entry) => entry.split(':')[0]?.trim() ?? '')
        .filter(Boolean),
    ),
  );
}

export const HdlEditorPanel: React.FC<HdlEditorPanelProps> = ({
  project,
  onProjectChange,
  fpga,
  onFpgaChange,
  backendId,
  beginnerView = false,
}) => {
  const resolvedBackendId = backendId ?? getToolchainBackendId();
  const backend = useMemo(() => getToolchainBackend(resolvedBackendId), [resolvedBackendId]);
  const [logs, setLogs] = useState<BuildLogEntry[]>([]);
  const [lastProbe, setLastProbe] = useState<ToolProbeResult | null>(null);
  const [lastPreflight, setLastPreflight] = useState<ToolchainPreflightStatus | null>(null);
  const [lastBuildPath, setLastBuildPath] = useState<ToolchainBuildPath | null>(null);
  const [isBuilding, setIsBuilding] = useState(false);
  const [isSynthesizing, setIsSynthesizing] = useState(false);
  const [isImplementing, setIsImplementing] = useState(false);
  const [isPlanningImplement, setIsPlanningImplement] = useState(false);
  const [isProbing, setIsProbing] = useState(false);
  const [isPreflighting, setIsPreflighting] = useState(false);
  const [synthRunId, setSynthRunId] = useState<string | null>(null);
  const [synthStatus, setSynthStatus] = useState<'idle' | 'running' | 'success' | 'failed' | 'canceled'>('idle');
  const [synthArtifact, setSynthArtifact] = useState<SynthArtifactRef | null>(null);
  const [synthArtifactId, setSynthArtifactId] = useState<string | null>(null);
  const [isSynthCanceling, setIsSynthCanceling] = useState(false);
  const [implementRunId, setImplementRunId] = useState<string | null>(null);
  const [implementStatus, setImplementStatus] = useState<'idle' | 'running' | 'success' | 'failed' | 'canceled'>('idle');
  const [implementArtifact, setImplementArtifact] = useState<ImplementArtifactRef | null>(null);
  const [implementArtifactId, setImplementArtifactId] = useState<string | null>(null);
  const [isImplementCanceling, setIsImplementCanceling] = useState(false);
  const [programRunId, setProgramRunId] = useState<string | null>(null);
  const [programArtifactId, setProgramArtifactId] = useState<string | null>(null);
  const [programStatus, setProgramStatus] = useState<'idle' | 'running' | 'success' | 'failed' | 'canceled'>('idle');
  const [isProgramCanceling, setIsProgramCanceling] = useState(false);
  const [isSetupVerifying, setIsSetupVerifying] = useState(false);
  const [includeSourcesInZip, setIncludeSourcesInZip] = useState(false);
  const [vivadoCommand, setVivadoCommand] = useState('vivado');
  const [vivadoCommandDirty, setVivadoCommandDirty] = useState(false);
  const [xdcBeforeDemoMismatch, setXdcBeforeDemoMismatch] = useState<string | null>(null);
  const buildRunSeqRef = useRef(0);
  const isMountedRef = useRef(true);
  const synthOffsetRef = useRef(0);
  const synthPollTimerRef = useRef<number | null>(null);
  const synthStreamRef = useRef<{ close: () => void } | null>(null);
  const synthPollingBusyRef = useRef(false);
  const implementOffsetRef = useRef(0);
  const implementPollTimerRef = useRef<number | null>(null);
  const implementStreamRef = useRef<{ close: () => void } | null>(null);
  const implementPollingBusyRef = useRef(false);
  const programOffsetRef = useRef(0);
  const programPollTimerRef = useRef<number | null>(null);
  const programStreamRef = useRef<{ close: () => void } | null>(null);
  const programPollingBusyRef = useRef(false);
  const [presetToApply, setPresetToApply] = useState<Basys3XdcPresetId | ''>('');

  const fileName = useMemo(() => {
    const names = (project.sources ?? []).map((s) => s.path).filter(Boolean).sort();
    const topName = normalizeHdlSourcePath(project.top ?? '');
    const topCandidates = [topName, `${topName}.v`, `${topName}.sv`, `${topName}.vhd`, `${topName}.vhdl`];
    const topFile = topCandidates.find((candidate) => names.includes(candidate));
    if (topFile) return topFile;
    return names[0] ?? 'top.v';
  }, [project.sources, project.top]);

  const activeSource = useMemo(() => {
    return (project.sources ?? []).find((s) => s.path === fileName) ?? null;
  }, [project.sources, fileName]);

  const fileText = activeSource?.text ?? '';
  const fileLanguage = activeSource?.language ?? 'verilog';
  const hasTopModule = typeof project.top === 'string' && project.top.trim().length > 0;
  const hasAnySource = Array.isArray(project.sources) && project.sources.length > 0;
  const hasActiveSource = activeSource !== null;

  const resolvedFpga: RBFpgaConfig = fpga ?? { board: 'basys3' };
  const xdcText = resolvedFpga.constraints?.text ?? '';
  const activePreset = resolvedFpga.preset ?? '';
  const buildSnapshot = useCallback(
    () => ({
      hdl: project,
      fpga: {
        board: 'basys3' as const,
        constraints: resolvedFpga.constraints,
        preset: resolvedFpga.preset,
        top: resolvedFpga.top,
      },
    }),
    [project, resolvedFpga.constraints, resolvedFpga.preset, resolvedFpga.top]
  );

  const readinessChecks = useMemo(() => {
    const preflight = lastPreflight;
    const hasTop = Boolean(preflight?.project.top?.trim());
    const hasXdc = Boolean(preflight?.project.hasXdc);
    const portsOk = Boolean(preflight?.lint.ok);
    const probeReady = (preflight?.tools ?? []).some((tool) => tool.ok) || Boolean(lastProbe?.ok);

    return [
      {
        id: 'top',
        label: 'Top',
        ok: hasTop,
        detail: hasTop
          ? preflight?.project.top ?? basys3TopModuleContract.topModule
          : `Set top module (${basys3TopModuleContract.topModule})`,
      },
      {
        id: 'xdc',
        label: 'XDC',
        ok: hasXdc,
        detail: hasXdc ? 'constraints loaded' : 'load a Basys3 preset',
      },
      {
        id: 'ports',
        label: 'Ports',
        ok: portsOk,
        detail: portsOk ? 'preflight lint ok' : 'run preflight or review lint',
      },
      {
        id: 'probe',
        label: 'Probe',
        ok: probeReady,
        detail: probeReady ? 'toolchain available' : 'run Probe Toolchain',
      },
    ] as const;
  }, [lastPreflight, lastProbe?.ok]);

  const implementHasBitstreamOutput = useMemo(() => {
    if (!implementArtifact) return false;
    const outputs = Array.isArray(implementArtifact.outputs) ? implementArtifact.outputs : [];
    return outputs.some((output) => {
      const kind = typeof output?.kind === 'string' ? output.kind.toLowerCase() : '';
      if (kind === 'bitstream') return true;
      const pathHint = String(output?.pathHint || '').toLowerCase();
      const storedPath = String(output?.storedPath || '').toLowerCase();
      const name = String(output?.name || '').toLowerCase();
      return pathHint.endsWith('.bit') || storedPath.endsWith('.bit') || name.includes('bitstream');
    });
  }, [implementArtifact]);
  const isProgramRunning = programStatus === 'running';
  const setupPlatform = useMemo(() => {
    const probePlatform = lastProbe?.env?.platform;
    if (typeof probePlatform === 'string' && probePlatform.trim().length > 0) {
      return normalizeSetupPlatform(probePlatform);
    }
    const navPlatform =
      typeof navigator !== 'undefined' && typeof navigator.platform === 'string'
        ? navigator.platform
        : 'linux';
    return normalizeSetupPlatform(navPlatform);
  }, [lastProbe?.env?.platform]);
  const setupCommands = useMemo(() => getSetupCommands(setupPlatform), [setupPlatform]);
  const vivadoAutoCandidates = useMemo(() => getVivadoAutoCandidates(setupPlatform), [setupPlatform]);
  const detectedVivadoPath = useMemo(() => {
    const tool = (lastProbe?.tools ?? []).find((entry) => entry.name === 'vivado' && entry.ok && typeof entry.path === 'string');
    return tool?.path?.trim() || null;
  }, [lastProbe?.tools]);
  const vivadoCommandCandidates = useMemo(() => {
    const next = [
      ...(detectedVivadoPath ? [detectedVivadoPath] : []),
      ...vivadoAutoCandidates,
    ];
    return Array.from(new Set(next.filter((value) => value.trim().length > 0)));
  }, [detectedVivadoPath, vivadoAutoCandidates]);
  const synthCheckTclText = useMemo(() => {
    const topModule = (project.top ?? resolvedFpga.top ?? 'top').trim() || 'top';
    return buildVivadoSynthCheckTcl({
      part: BASYS3_PART,
      topModule,
      topVhdlPath: './top.vhd',
      xdcPath: './top.xdc',
      outDir: './vivado_out',
      projectName: 'rb_handoff_top',
    });
  }, [project.top, resolvedFpga.top]);
  const vivadoBatchCommand = useMemo(() => {
    const cmd = vivadoCommand.trim().length > 0 ? vivadoCommand.trim() : 'vivado';
    return `${cmd} -mode batch -source synth_check.tcl -notrace -nojournal -log vivado_out/vivado.log`;
  }, [vivadoCommand]);
  const vivadoReportOutputs = useMemo(() => {
    if (!implementArtifact) return [];
    const preferred = ['utilization', 'timing', 'messages'];
    const outputs = Array.isArray(implementArtifact.outputs) ? implementArtifact.outputs : [];
    const filtered = outputs.filter((output) => {
      const name = String(output?.name ?? '').toLowerCase();
      const pathHint = String(output?.pathHint ?? '').toLowerCase();
      const kind = String(output?.kind ?? '').toLowerCase();
      return kind === 'report' || preferred.some((token) => name.includes(token) || pathHint.includes(token));
    });
    return filtered;
  }, [implementArtifact]);
  const requiredDemoTools = useMemo(() => {
    const tools = Array.isArray(lastProbe?.tools) ? lastProbe.tools : [];
    const find = (name: string) => tools.find((tool) => tool.name === name);
    const backendTool = find('vivado');
    const synthTool = find('yosys');
    const programTool = find('openFPGALoader');
    return [
      {
        name: 'vivado',
        label: 'Implement backend (stable)',
        ok: backendTool?.ok === true,
        detail:
          backendTool?.status === 'found_not_in_path'
            ? `source:${backendTool?.source ?? 'found_not_in_path'} found_not_in_path`
            : backendTool?.ok
              ? `source:${backendTool?.source ?? 'system'} ${backendTool.version || 'detected'}`
              : `source:${backendTool?.source ?? 'not_found'} ${backendTool?.error || 'missing'}`,
        suggestedFix: backendTool?.suggestedFix,
      },
      {
        name: 'yosys',
        label: 'Synthesis',
        ok: synthTool?.ok === true,
        detail:
          synthTool?.status === 'found_not_in_path'
            ? `source:${synthTool?.source ?? 'found_not_in_path'} found_not_in_path`
            : synthTool?.ok
              ? `source:${synthTool?.source ?? 'system'} ${synthTool.version || 'detected'}`
              : `source:${synthTool?.source ?? 'not_found'} ${synthTool?.error || 'missing'}`,
        suggestedFix: synthTool?.suggestedFix,
      },
      {
        name: 'openFPGALoader',
        label: 'Programming',
        ok: programTool?.ok === true,
        detail:
          programTool?.status === 'found_not_in_path'
            ? `source:${programTool?.source ?? 'found_not_in_path'} found_not_in_path`
            : programTool?.ok
              ? `source:${programTool?.source ?? 'system'} ${programTool.version || 'detected'}`
              : `source:${programTool?.source ?? 'not_found'} ${programTool?.error || 'missing'}`,
        suggestedFix: programTool?.suggestedFix,
      },
    ] as const;
  }, [lastProbe?.tools]);

  useEffect(() => {
    if (vivadoCommandDirty) return;
    const next = detectedVivadoPath ?? 'vivado';
    setVivadoCommand(next);
  }, [detectedVivadoPath, vivadoCommandDirty]);

  const appendLog = useCallback((entry: BuildLogEntry) => {
    setLogs((prev) => [...prev, entry]);
  }, []);
  const appendLogs = useCallback((entries: BuildLogEntry[]) => {
    if (!entries.length) return;
    setLogs((prev) => [...prev, ...entries]);
  }, []);

  const clearSynthMonitoring = useCallback(() => {
    if (synthStreamRef.current) {
      synthStreamRef.current.close();
      synthStreamRef.current = null;
    }
    if (synthPollTimerRef.current !== null) {
      window.clearInterval(synthPollTimerRef.current);
      synthPollTimerRef.current = null;
    }
    synthPollingBusyRef.current = false;
  }, []);

  const clearImplementMonitoring = useCallback(() => {
    if (implementStreamRef.current) {
      implementStreamRef.current.close();
      implementStreamRef.current = null;
    }
    if (implementPollTimerRef.current !== null) {
      window.clearInterval(implementPollTimerRef.current);
      implementPollTimerRef.current = null;
    }
    implementPollingBusyRef.current = false;
  }, []);

  const clearProgramMonitoring = useCallback(() => {
    if (programStreamRef.current) {
      programStreamRef.current.close();
      programStreamRef.current = null;
    }
    if (programPollTimerRef.current !== null) {
      window.clearInterval(programPollTimerRef.current);
      programPollTimerRef.current = null;
    }
    programPollingBusyRef.current = false;
  }, []);

  const finalizeSynthRun = useCallback(
    (summary: SynthRunDoneSummary) => {
      if (!isMountedRef.current) return;
      clearSynthMonitoring();
      synthOffsetRef.current = summary.nextOffset;
      setIsSynthesizing(false);
      setSynthRunId(summary.runId);
      setSynthArtifactId(summary.artifactId);
      setIsSynthCanceling(false);
      if (summary.artifact) {
        setSynthArtifact(summary.artifact);
      }
      if (summary.state === 'done' && summary.ok) {
        setSynthStatus('success');
        return;
      }
      if (summary.state === 'canceled') {
        setSynthStatus('canceled');
        return;
      }
      setSynthStatus('failed');
    },
    [clearSynthMonitoring]
  );

  const finalizeImplementRun = useCallback(
    (summary: ImplementRunDoneSummary) => {
      if (!isMountedRef.current) return;
      clearImplementMonitoring();
      implementOffsetRef.current = summary.nextOffset;
      setIsImplementing(false);
      setImplementRunId(summary.runId);
      setImplementArtifactId(summary.artifactId);
      if (summary.artifact) {
        setImplementArtifact(summary.artifact);
      }
      if (summary.state === 'done' && summary.ok) {
        setImplementStatus('success');
        return;
      }
      if (summary.state === 'canceled') {
        setImplementStatus('canceled');
        return;
      }
      setImplementStatus('failed');
    },
    [clearImplementMonitoring]
  );

  const finalizeProgramRun = useCallback(
    (summary: ProgramRunDoneSummary) => {
      if (!isMountedRef.current) return;
      clearProgramMonitoring();
      programOffsetRef.current = summary.nextOffset;
      setProgramRunId(summary.runId);
      setProgramArtifactId(summary.artifactId);
      setIsProgramCanceling(false);
      if (summary.state === 'done' && summary.ok) {
        setProgramStatus('success');
        return;
      }
      if (summary.state === 'canceled') {
        setProgramStatus('canceled');
        return;
      }
      setProgramStatus('failed');
    },
    [clearProgramMonitoring]
  );

  const runPreflight = useCallback(
    async (options?: { refreshProbe?: boolean; snapshot?: ReturnType<typeof buildSnapshot> }) => {
      const status = await backend.preflight(options?.snapshot ?? buildSnapshot(), {
        refreshProbe: options?.refreshProbe,
      });
      setLastPreflight(status);
      return status;
    },
    [backend, buildSnapshot]
  );

  useEffect(() => {
    isMountedRef.current = true;
    return () => {
      isMountedRef.current = false;
      clearSynthMonitoring();
      clearImplementMonitoring();
      clearProgramMonitoring();
    };
  }, [clearImplementMonitoring, clearProgramMonitoring, clearSynthMonitoring]);

  useEffect(() => {
    let cancelled = false;
    setIsPreflighting(true);
    runPreflight()
      .catch(() => {
        if (!cancelled) setLastPreflight(null);
      })
      .finally(() => {
        if (!cancelled) setIsPreflighting(false);
      });
    return () => {
      cancelled = true;
    };
  }, [runPreflight]);

  const pollSynthRunStatus = useCallback(
    async (runId: string) => {
      if (!isMountedRef.current || synthPollingBusyRef.current) return;
      synthPollingBusyRef.current = true;
      try {
        const status = await backend.getSynthRunStatus(runId, synthOffsetRef.current);
        if (!isMountedRef.current) return;
        appendLogs(status.logs ?? []);
        synthOffsetRef.current = status.nextOffset;
        if (status.state !== 'running') {
          finalizeSynthRun({
            runId: status.runId,
            artifactId: status.artifactId,
            state: status.state === 'done' || status.state === 'error' || status.state === 'canceled' ? status.state : 'error',
            ok: status.ok === true,
            exitCode: status.exitCode,
            nextOffset: status.nextOffset,
            ...(status.error ? { error: status.error } : {}),
            ...(status.artifact ? { artifact: status.artifact } : {}),
          });
        }
      } catch (error) {
        if (!isMountedRef.current) return;
        const message = error instanceof Error ? error.message : 'synth_status_failed';
        appendLog({
          run_id: runId,
          ts: synthOffsetRef.current,
          step: 'synth',
          level: 'error',
          msg: `[${backend.id}] synth: poll failed: ${message}`,
        });
        clearSynthMonitoring();
        setIsSynthesizing(false);
        setSynthStatus('failed');
      } finally {
        synthPollingBusyRef.current = false;
      }
    },
    [appendLog, appendLogs, backend.id, clearSynthMonitoring, finalizeSynthRun]
  );

  const startSynthPolling = useCallback(
    (runId: string, offset: number) => {
      if (!isMountedRef.current) return;
      clearSynthMonitoring();
      synthOffsetRef.current = Math.max(0, offset);
      void pollSynthRunStatus(runId);
      synthPollTimerRef.current = window.setInterval(() => {
        void pollSynthRunStatus(runId);
      }, 500);
    },
    [clearSynthMonitoring, pollSynthRunStatus]
  );

  const startSynthStreaming = useCallback(
    (runId: string, offset: number) => {
      clearSynthMonitoring();
      synthOffsetRef.current = Math.max(0, offset);
      const subscription = backend.openSynthRunStream(
        runId,
        {
          onLog(entry) {
            if (!isMountedRef.current) return;
            appendLog(entry);
            synthOffsetRef.current = Math.max(synthOffsetRef.current, entry.ts + 1);
          },
          onDone(summary) {
            if (!isMountedRef.current) return;
            finalizeSynthRun(summary);
          },
          onError() {
            if (!isMountedRef.current) return;
            startSynthPolling(runId, synthOffsetRef.current);
          },
        },
        { offset: synthOffsetRef.current }
      );
      if (!subscription) {
        startSynthPolling(runId, synthOffsetRef.current);
        return;
      }
      synthStreamRef.current = subscription;
    },
    [appendLog, backend, clearSynthMonitoring, finalizeSynthRun, startSynthPolling]
  );

  const pollImplementRunStatus = useCallback(
    async (runId: string) => {
      if (!isMountedRef.current || implementPollingBusyRef.current) return;
      implementPollingBusyRef.current = true;
      try {
        const status = await backend.getImplementRunStatus(runId, implementOffsetRef.current);
        if (!isMountedRef.current) return;
        appendLogs(status.logs ?? []);
        implementOffsetRef.current = status.nextOffset;
        if (status.state !== 'running') {
          finalizeImplementRun({
            runId: status.runId,
            artifactId: status.artifactId,
            state: status.state === 'done' || status.state === 'error' || status.state === 'canceled' ? status.state : 'error',
            ok: status.ok === true,
            exitCode: status.exitCode,
            nextOffset: status.nextOffset,
            ...(status.error ? { error: status.error } : {}),
            ...(status.artifact ? { artifact: status.artifact } : {}),
          });
        }
      } catch (error) {
        if (!isMountedRef.current) return;
        const message = error instanceof Error ? error.message : 'implement_status_failed';
        appendLog({
          run_id: runId,
          ts: implementOffsetRef.current,
          step: 'implement',
          level: 'error',
          msg: `[${backend.id}] implement: poll failed: ${message}`,
        });
        clearImplementMonitoring();
        setIsImplementing(false);
        setImplementStatus('failed');
      } finally {
        implementPollingBusyRef.current = false;
      }
    },
    [appendLog, appendLogs, backend.id, clearImplementMonitoring, finalizeImplementRun]
  );

  const startImplementPolling = useCallback(
    (runId: string, offset: number) => {
      if (!isMountedRef.current) return;
      clearImplementMonitoring();
      implementOffsetRef.current = Math.max(0, offset);
      void pollImplementRunStatus(runId);
      implementPollTimerRef.current = window.setInterval(() => {
        void pollImplementRunStatus(runId);
      }, 500);
    },
    [clearImplementMonitoring, pollImplementRunStatus]
  );

  const startImplementStreaming = useCallback(
    (runId: string, offset: number) => {
      clearImplementMonitoring();
      implementOffsetRef.current = Math.max(0, offset);
      const subscription = backend.openImplementRunStream(
        runId,
        {
          onLog(entry) {
            if (!isMountedRef.current) return;
            appendLog(entry);
            implementOffsetRef.current = Math.max(implementOffsetRef.current, entry.ts + 1);
          },
          onDone(summary) {
            if (!isMountedRef.current) return;
            finalizeImplementRun(summary);
          },
          onError() {
            if (!isMountedRef.current) return;
            startImplementPolling(runId, implementOffsetRef.current);
          },
        },
        { offset: implementOffsetRef.current }
      );
      if (!subscription) {
        startImplementPolling(runId, implementOffsetRef.current);
        return;
      }
      implementStreamRef.current = subscription;
    },
    [appendLog, backend, clearImplementMonitoring, finalizeImplementRun, startImplementPolling]
  );

  const pollProgramRunStatus = useCallback(
    async (runId: string) => {
      if (!isMountedRef.current || programPollingBusyRef.current) return;
      programPollingBusyRef.current = true;
      try {
        const status = await backend.getRunStatus(runId, programOffsetRef.current);
        if (!isMountedRef.current) return;
        appendLogs(status.logs ?? []);
        programOffsetRef.current = status.nextOffset;
        if (status.state !== 'running') {
          finalizeProgramRun({
            runId: status.runId,
            artifactId: status.artifactId,
            state: status.state === 'done' || status.state === 'error' || status.state === 'canceled' ? status.state : 'error',
            ok: status.ok === true,
            exitCode: status.exitCode,
            nextOffset: status.nextOffset,
            ...(status.error ? { error: status.error } : {}),
          });
        }
      } catch (error) {
        if (!isMountedRef.current) return;
        const message = error instanceof Error ? error.message : 'program_status_failed';
        appendLog({
          run_id: runId,
          ts: programOffsetRef.current,
          step: 'program',
          level: 'error',
          msg: `[${backend.id}] program: poll failed: ${message}`,
        });
        clearProgramMonitoring();
        setProgramStatus('failed');
      } finally {
        programPollingBusyRef.current = false;
      }
    },
    [appendLog, appendLogs, backend.id, clearProgramMonitoring, finalizeProgramRun]
  );

  const startProgramPolling = useCallback(
    (runId: string, offset: number) => {
      if (!isMountedRef.current) return;
      clearProgramMonitoring();
      programOffsetRef.current = Math.max(0, offset);
      void pollProgramRunStatus(runId);
      programPollTimerRef.current = window.setInterval(() => {
        void pollProgramRunStatus(runId);
      }, 500);
    },
    [clearProgramMonitoring, pollProgramRunStatus]
  );

  const startProgramStreaming = useCallback(
    (runId: string, offset: number) => {
      clearProgramMonitoring();
      programOffsetRef.current = Math.max(0, offset);
      const subscription = backend.openRunStream(
        runId,
        {
          onLog(entry) {
            if (!isMountedRef.current) return;
            appendLog(entry);
            programOffsetRef.current = Math.max(programOffsetRef.current, entry.ts + 1);
          },
          onDone(summary) {
            if (!isMountedRef.current) return;
            finalizeProgramRun(summary);
          },
          onError() {
            if (!isMountedRef.current) return;
            startProgramPolling(runId, programOffsetRef.current);
          },
        },
        { offset: programOffsetRef.current }
      );
      if (!subscription) {
        startProgramPolling(runId, programOffsetRef.current);
        return;
      }
      programStreamRef.current = subscription;
    },
    [appendLog, backend, clearProgramMonitoring, finalizeProgramRun, startProgramPolling]
  );

  const handleInsertExample = useCallback(
    (exampleId: Basys3ExampleId) => {
      const example = getBasys3VerilogExample(exampleId);
      if (!example) return;
      const nextProject = upsertSource(project, example.defaultPath, {
        language: example.language,
        text: example.text,
      });
      onProjectChange({
        ...nextProject,
        top: example.top,
      });
      if (onFpgaChange) {
        onFpgaChange({
          ...resolvedFpga,
          top: example.top,
        });
      }
    },
    [onFpgaChange, onProjectChange, project, resolvedFpga]
  );

  const handleSynthesize = useCallback(async () => {
    if (isSynthesizing) return;
    setLogs([]);
    setSynthArtifact(null);
    setSynthArtifactId(null);
    setSynthRunId(null);
    setSynthStatus('running');
    setIsSynthCanceling(false);
    setIsSynthesizing(true);

    const run_id = `ui-synth-${buildRunSeqRef.current++}`;
    let ts = 0;
    const emitLocal = (level: 'info' | 'warn' | 'error', msg: string, data?: Record<string, unknown>) => {
      appendLog({
        run_id,
        ts: ts++,
        step: 'synth',
        level,
        msg,
        ...(data ? { data } : {}),
      });
    };

    try {
      setIsPreflighting(true);
      const preflight = await runPreflight();
      setIsPreflighting(false);
      appendLogs([...(preflight.lint.warnings ?? []), ...(preflight.lint.errors ?? [])]);
      if (!preflight.overallOk) {
        emitLocal('error', `[${backend.id}] synth: blocked by preflight (${preflight.lint.errors.length} error(s))`);
        setSynthStatus('failed');
        setIsSynthesizing(false);
        return;
      }

      const resolvedBuildPath = lastBuildPath ?? (await backend.resolveBuildPath(buildSnapshot(), { refreshProbe: false }));
      setLastBuildPath(resolvedBuildPath);
      emitLocal('info', `[${backend.id}] synth: using build-path ${resolvedBuildPath.planId} (${resolvedBuildPath.backend})`, {
        planId: resolvedBuildPath.planId,
        backend: resolvedBuildPath.backend,
      });

      const top = (project.top ?? resolvedFpga.top ?? basys3TopModuleContract.topModule).trim();
      const verilogSources = (project.sources ?? [])
        .filter((source) => source.language === 'verilog')
        .map((source) => ({
          path: source.path,
          language: 'verilog' as const,
          text: source.text,
        }));

      const result = await backend.synth({
        board: 'basys3',
        top,
        sources: verilogSources,
        buildPath: {
          planId: resolvedBuildPath.planId,
          backend: resolvedBuildPath.backend,
        },
      });
      setSynthRunId(result.runId);
      setSynthArtifactId(result.artifactId);
      appendLogs(result.logs ?? []);
      synthOffsetRef.current = result.nextOffset ?? 0;
      if (result.artifact) {
        setSynthArtifact(result.artifact);
      }

      if (result.state !== 'running') {
        finalizeSynthRun({
          runId: result.runId,
          artifactId: result.artifactId,
          state: result.state === 'done' || result.state === 'error' || result.state === 'canceled' ? result.state : 'error',
          ok: result.ok === true,
          exitCode: result.exitCode,
          nextOffset: result.nextOffset,
          ...(result.error ? { error: result.error } : {}),
          ...(result.artifact ? { artifact: result.artifact } : {}),
        });
        return;
      }

      startSynthStreaming(result.runId, result.nextOffset);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'synth_failed';
      emitLocal('error', `[${backend.id}] synth: failed: ${message}`);
      setIsSynthesizing(false);
      setSynthStatus('failed');
      setIsSynthCanceling(false);
      clearSynthMonitoring();
    } finally {
      setIsPreflighting(false);
    }
  }, [
    appendLog,
    appendLogs,
    backend,
    buildSnapshot,
    clearSynthMonitoring,
    finalizeSynthRun,
    isSynthesizing,
    lastBuildPath,
    project.sources,
    project.top,
    resolvedFpga.top,
    runPreflight,
    startSynthStreaming,
  ]);

  const handleCancelSynthRun = useCallback(async () => {
    if (!synthRunId || isSynthCanceling) return;
    setIsSynthCanceling(true);
    try {
      const canceled = await backend.cancelRun(synthRunId);
      appendLogs(canceled.logs ?? []);
      if (canceled.state !== 'running') {
        finalizeSynthRun({
          runId: canceled.runId,
          artifactId: canceled.artifactId,
          state: canceled.state === 'done' || canceled.state === 'error' || canceled.state === 'canceled' ? canceled.state : 'error',
          ok: canceled.ok === true,
          exitCode: canceled.exitCode,
          nextOffset: canceled.nextOffset,
          ...(canceled.error ? { error: canceled.error } : {}),
        });
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'synth_cancel_failed';
      appendLog({
        run_id: synthRunId,
        ts: synthOffsetRef.current,
        step: 'synth',
        level: 'error',
        msg: `[${backend.id}] synth cancel failed: ${message}`,
      });
      setIsSynthCanceling(false);
    }
  }, [appendLog, appendLogs, backend, finalizeSynthRun, isSynthCanceling, synthRunId]);

  const handleImplementRun = useCallback(async (snapshotOverride?: unknown) => {
    if (isImplementing) return;
    setLogs([]);
    setImplementArtifact(null);
    setImplementArtifactId(null);
    setImplementRunId(null);
    setImplementStatus('running');
    setIsImplementing(true);
    setProgramRunId(null);
    setProgramArtifactId(null);
    setProgramStatus('idle');
    setIsProgramCanceling(false);
    clearProgramMonitoring();

    const run_id = `ui-implement-${buildRunSeqRef.current++}`;
    let ts = 0;
    const snapshot =
      snapshotOverride &&
      typeof snapshotOverride === 'object' &&
      'hdl' in snapshotOverride &&
      'fpga' in snapshotOverride
        ? (snapshotOverride as ReturnType<typeof buildSnapshot>)
        : buildSnapshot();
    const emitLocal = (level: 'info' | 'warn' | 'error', msg: string, data?: Record<string, unknown>) => {
      appendLog({
        run_id,
        ts: ts++,
        step: 'implement',
        level,
        msg,
        ...(data ? { data } : {}),
      });
    };

    try {
      setIsPreflighting(true);
      const preflight = await runPreflight({ snapshot });
      setIsPreflighting(false);
      appendLogs([...(preflight.lint.warnings ?? []), ...(preflight.lint.errors ?? [])]);
      if (!preflight.overallOk) {
        emitLocal('error', `[${backend.id}] implement: blocked by preflight (${preflight.lint.errors.length} error(s))`);
        setImplementStatus('failed');
        setIsImplementing(false);
        return;
      }

      const resolvedBuildPath = lastBuildPath ?? (await backend.resolveBuildPath(snapshot, { refreshProbe: false }));
      setLastBuildPath(resolvedBuildPath);
      emitLocal('info', `[${backend.id}] implement: using build-path ${resolvedBuildPath.planId} (${resolvedBuildPath.backend})`, {
        planId: resolvedBuildPath.planId,
        backend: resolvedBuildPath.backend,
      });
      if (resolvedBuildPath.backend === 'nextpnr-xilinx' || resolvedBuildPath.backend === 'f4pga') {
        emitLocal('warn', `[${backend.id}] implement: experimental backend selected; expect failures and download artifacts for debugging.`);
      }

      const result = await backend.implementRun({
        board: 'basys3',
        project: {
          hdl: {
            sources: snapshot.hdl.sources.map((source) => ({
              path: source.path,
              language: source.language,
              text: source.text,
            })),
            top: snapshot.hdl.top ?? null,
          },
          fpga: {
            board: 'basys3',
            constraints: snapshot.fpga.constraints
              ? {
                  type: 'xdc',
                  text: snapshot.fpga.constraints.text,
                }
              : null,
            preset: snapshot.fpga.preset ?? null,
            top: snapshot.fpga.top ?? null,
          },
        },
        buildPath: {
          planId: resolvedBuildPath.planId,
          backend: resolvedBuildPath.backend,
        },
      });
      setImplementRunId(result.runId);
      setImplementArtifactId(result.artifactId);
      appendLogs(result.logs ?? []);
      implementOffsetRef.current = result.nextOffset ?? 0;
      if (result.artifact) {
        setImplementArtifact(result.artifact);
      }

      if (result.state !== 'running') {
        finalizeImplementRun({
          runId: result.runId,
          artifactId: result.artifactId,
          state: result.state === 'done' || result.state === 'error' || result.state === 'canceled' ? result.state : 'error',
          ok: result.ok === true,
          exitCode: result.exitCode,
          nextOffset: result.nextOffset,
          ...(result.error ? { error: result.error } : {}),
          ...(result.artifact ? { artifact: result.artifact } : {}),
        });
        return;
      }

      startImplementStreaming(result.runId, result.nextOffset);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'implement_run_failed';
      emitLocal('error', `[${backend.id}] implement: failed: ${message}`);
      setIsImplementing(false);
      setImplementStatus('failed');
      clearImplementMonitoring();
    } finally {
      setIsPreflighting(false);
    }
  }, [
    appendLog,
    appendLogs,
    backend,
    buildSnapshot,
    clearImplementMonitoring,
    clearProgramMonitoring,
    finalizeImplementRun,
    isImplementing,
    lastBuildPath,
    runPreflight,
    startImplementStreaming,
  ]);

  const handleCancelImplementRun = useCallback(async () => {
    if (!implementRunId || isImplementCanceling) return;
    setIsImplementCanceling(true);
    try {
      const canceled = await backend.cancelRun(implementRunId);
      appendLogs(canceled.logs ?? []);
      if (canceled.state !== 'running') {
        finalizeImplementRun({
          runId: canceled.runId,
          artifactId: canceled.artifactId,
          state: canceled.state === 'done' || canceled.state === 'error' || canceled.state === 'canceled' ? canceled.state : 'error',
          ok: canceled.ok === true,
          exitCode: canceled.exitCode,
          nextOffset: canceled.nextOffset,
          ...(canceled.error ? { error: canceled.error } : {}),
        });
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'implement_cancel_failed';
      appendLog({
        run_id: implementRunId,
        ts: implementOffsetRef.current,
        step: 'implement',
        level: 'error',
        msg: `[${backend.id}] implement cancel failed: ${message}`,
      });
    } finally {
      setIsImplementCanceling(false);
    }
  }, [appendLog, appendLogs, backend, finalizeImplementRun, implementRunId, isImplementCanceling]);

  const handleGoldenDemo = useCallback(() => {
    const example = getBasys3VerilogExample('basys3-switches-to-leds');
    if (!example) return;
    const nextProject = upsertSource(project, example.defaultPath, {
      language: example.language,
      text: example.text,
    });
    const nextHdlProject: ToolchainProjectInput = {
      ...nextProject,
      top: example.top,
    };
    const preset = example.recommendedPreset;
    const nextFpga: RBFpgaConfig = {
      ...resolvedFpga,
      board: 'basys3',
      top: example.top,
      preset,
      constraints: {
        type: 'xdc',
        text: getBasys3XdcPresetText(preset),
      },
    };

    onProjectChange(nextHdlProject);
    if (onFpgaChange) {
      onFpgaChange(nextFpga);
    }
    setPresetToApply(preset);

    void handleImplementRun({
      hdl: nextHdlProject,
      fpga: {
        board: 'basys3',
        constraints: nextFpga.constraints,
        preset: nextFpga.preset,
        top: nextFpga.top,
      },
    });
  }, [handleImplementRun, onFpgaChange, onProjectChange, project, resolvedFpga]);

  const handleBuild = useCallback(async () => {
    setLogs([]);
    setIsBuilding(true);

    const run_id = `ui-build-${buildRunSeqRef.current++}`;
    let ts = 0;
    const sink = {
      log: (entry: BuildLogEntry) => {
        appendLog({ ...entry, run_id, ts: ts++ });
      },
    };

    try {
      setIsPreflighting(true);
      const preflight = await runPreflight();
      setIsPreflighting(false);
      const preflightLogs = [...(preflight.lint.warnings ?? []), ...(preflight.lint.errors ?? [])];
      for (const entry of preflightLogs) {
        sink.log({
          step: entry.step,
          level: entry.level,
          msg: entry.msg,
          data: entry.data,
        });
      }

      if (!preflight.overallOk) {
        sink.log({
          step: 'preflight',
          level: 'error',
          msg: `[${backend.id}] build: blocked by preflight (${preflight.lint.errors.length} error(s))`,
        });
        return;
      }

      const netlist = await backend.synthesize(project, sink);
      const implemented = await backend.implement(netlist, sink);
      await backend.bitgen(implemented, sink);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'build_failed';
      appendLog({
        run_id,
        ts: ts++,
        step: 'synth',
        level: 'error',
        msg: `[${backend.id}] build: failed: ${message}`,
      });
    } finally {
      setIsPreflighting(false);
      setIsBuilding(false);
    }
  }, [appendLog, backend, project, runPreflight]);

  const handleProbe = useCallback(async () => {
    setLogs([]);
    setIsProbing(true);

    try {
      const result = await backend.probeTools();
      setLastProbe(result);
      setLogs(result.logs ?? []);
      setIsPreflighting(true);
      try {
        const preflight = await runPreflight({ refreshProbe: false });
        setLastPreflight(preflight);
      } finally {
        setIsPreflighting(false);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : 'probe_failed';
      setLastProbe(null);
      setLogs([
        {
          run_id: 'ui-probe',
          ts: 0,
          step: 'probe',
          level: 'error',
          msg: `[${backend.id}] probe: failed: ${message}`,
        },
      ]);
    } finally {
      setIsProbing(false);
    }
  }, [backend, runPreflight]);

  const handlePlanImplementation = useCallback(async () => {
    setLogs([]);
    setIsPlanningImplement(true);
    try {
      const buildPath = await backend.resolveBuildPath(buildSnapshot(), { refreshProbe: false });
      setLastBuildPath(buildPath);
      setLogs([...(buildPath.warnings ?? []), {
        run_id: `ui-build-path-${buildPath.planId}`,
        ts: buildPath.warnings.length,
        step: 'pnr',
        level: 'info',
        msg: `[${backend.id}] build-path: selected ${buildPath.backend} (${buildPath.planId})`,
      }]);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'implement_plan_failed';
      setLogs([
        {
          run_id: 'ui-implement-plan',
          ts: 0,
          step: 'pnr',
          level: 'error',
          msg: `[${backend.id}] implement-plan: failed: ${message}`,
        },
      ]);
      setLastBuildPath(null);
    } finally {
      setIsPlanningImplement(false);
    }
  }, [backend, buildSnapshot]);

  const handleVerifySetup = useCallback(() => {
    void (async () => {
      setIsSetupVerifying(true);
      setLogs([]);
      const snapshot = buildSnapshot();
      try {
        const probe = await backend.probeTools();
        setLastProbe(probe);
        const preflight = await runPreflight({ snapshot, refreshProbe: false });
        setLastPreflight(preflight);
        const buildPath = await backend.resolveBuildPath(snapshot, { refreshProbe: false });
        setLastBuildPath(buildPath);
        const mergedLogs: BuildLogEntry[] = [
          ...(probe.logs ?? []),
          ...(preflight.lint.warnings ?? []),
          ...(preflight.lint.errors ?? []),
          ...(buildPath.warnings ?? []),
          {
            run_id: `ui-setup-${buildPath.planId}`,
            ts: 0,
            step: 'preflight',
            level: 'info',
            msg: `[${backend.id}] setup verify: backend=${buildPath.backend} plan=${buildPath.planId}`,
          },
        ];
        setLogs(mergedLogs);
      } catch (error) {
        const message = error instanceof Error ? error.message : 'setup_verify_failed';
        setLogs([
          {
            run_id: 'ui-setup',
            ts: 0,
            step: 'preflight',
            level: 'error',
            msg: `[${backend.id}] setup verify failed: ${message}`,
          },
        ]);
      } finally {
        setIsSetupVerifying(false);
      }
    })();
  }, [backend, buildSnapshot, runPreflight]);

  const handleExportSetupReport = useCallback(() => {
    void (async () => {
      const snapshot = buildSnapshot();
      const probe = lastProbe ?? (await backend.probeTools());
      if (!lastProbe) setLastProbe(probe);
      const preflight = lastPreflight ?? (await runPreflight({ snapshot, refreshProbe: false }));
      if (!lastPreflight) setLastPreflight(preflight);
      const buildPath = lastBuildPath ?? (await backend.resolveBuildPath(snapshot, { refreshProbe: false }));
      if (!lastBuildPath) setLastBuildPath(buildPath);
      const report = await backend.doctorReport(snapshot, {
        logs,
        probe,
        preflight,
        buildPath,
      });
      const json = stableStringify(report);
      const fileTag = report.reportId ? `-${report.reportId}` : '';
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `rb-toolchain-setup-report${fileTag}.json`;
      link.click();
      URL.revokeObjectURL(url);
    })().catch((error) => {
      const message = error instanceof Error ? error.message : 'setup_report_export_failed';
      setLogs((prev) => [
        ...prev,
        {
          run_id: 'ui-setup-report',
          ts: prev.length,
          step: 'preflight',
          level: 'error',
          msg: `[${backend.id}] setup report export failed: ${message}`,
        },
      ]);
    });
  }, [backend, buildSnapshot, lastBuildPath, lastPreflight, lastProbe, logs, runPreflight]);

  const handleExportReport = useCallback(() => {
    void (async () => {
      const report = await backend.doctorReport(buildSnapshot(), {
        logs,
        probe: lastProbe,
        preflight: lastPreflight,
        buildPath: lastBuildPath,
      });
      const json = stableStringify(report);
      const fileTag = report.reportId ? `-${report.reportId}` : lastProbe?.run_id ? `-${lastProbe.run_id}` : '';
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `rb-toolchain-report${fileTag}.json`;
      link.click();
      URL.revokeObjectURL(url);
    })().catch((error) => {
      const message = error instanceof Error ? error.message : 'report_export_failed';
      setLogs((prev) => [
        ...prev,
        {
          run_id: 'ui-report',
          ts: prev.length,
          step: 'preflight',
          level: 'error',
          msg: `[${backend.id}] doctor report export failed: ${message}`,
        },
      ]);
    });
  }, [backend, buildSnapshot, lastBuildPath, lastPreflight, lastProbe, logs]);

  const handleDownloadSynthCheckTcl = useCallback(() => {
    const blob = new Blob([synthCheckTclText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'synth_check.tcl';
    link.click();
    URL.revokeObjectURL(url);
  }, [synthCheckTclText]);

  const handleDemoReset = useCallback(() => {
    clearSynthMonitoring();
    clearImplementMonitoring();
    clearProgramMonitoring();
    setLogs([]);
    setIsBuilding(false);
    setIsSynthesizing(false);
    setIsImplementing(false);
    setIsPlanningImplement(false);
    setIsProbing(false);
    setIsPreflighting(false);
    setSynthRunId(null);
    setSynthStatus('idle');
    setSynthArtifact(null);
    setSynthArtifactId(null);
    setIsSynthCanceling(false);
    setImplementRunId(null);
    setImplementStatus('idle');
    setImplementArtifact(null);
    setImplementArtifactId(null);
    setIsImplementCanceling(false);
    setProgramRunId(null);
    setProgramArtifactId(null);
    setProgramStatus('idle');
    setIsProgramCanceling(false);
    setLastBuildPath(null);
    setXdcBeforeDemoMismatch(null);
  }, [clearImplementMonitoring, clearProgramMonitoring, clearSynthMonitoring]);

  const handleInjectDemoMismatch = useCallback(() => {
    if (!onFpgaChange) return;
    const current = resolvedFpga.constraints?.text ?? '';
    if (current.includes('demo_bad_port')) return;
    setXdcBeforeDemoMismatch(current);
    const next = `${current.trimEnd()}\nset_property -dict { PACKAGE_PIN U16 IOSTANDARD LVCMOS33 } [get_ports {demo_bad_port}]\n`;
    onFpgaChange({
      ...resolvedFpga,
      constraints: { type: 'xdc', text: next },
    });
  }, [onFpgaChange, resolvedFpga]);

  const handleRestoreDemoMismatch = useCallback(() => {
    if (!onFpgaChange) return;
    const fallback = resolvedFpga.constraints?.text ?? '';
    const restored = xdcBeforeDemoMismatch ?? fallback.replace(/^.*\[get_ports\s*\{demo_bad_port\}\].*\n?/gm, '').trimEnd();
    onFpgaChange({
      ...resolvedFpga,
      constraints: { type: 'xdc', text: restored.length > 0 ? `${restored}\n` : '' },
    });
    setXdcBeforeDemoMismatch(null);
  }, [onFpgaChange, resolvedFpga, xdcBeforeDemoMismatch]);

  const handleRunVivadoBatch = useCallback(() => {
    const xdcPorts = extractXdcPorts(xdcText);
    const vhdlPorts = extractVhdlEntityPorts(fileText, project.top ?? resolvedFpga.top ?? 'top');
    const xdcSet = new Set(xdcPorts);
    const vhdlSet = new Set(vhdlPorts);
    const missingInVhdl = [...xdcSet].filter((port) => !vhdlSet.has(port));
    const extraInVhdl = [...vhdlSet].filter((port) => !xdcSet.has(port));

    if (missingInVhdl.length > 0 || extraInVhdl.length > 0) {
      setLogs((prev) => [
        ...prev,
        {
          run_id: 'ui-vivado-guard',
          ts: prev.length,
          step: 'preflight',
          level: 'error',
          msg: `[${backend.id}] vivado guard: XDC/VHDL port mismatch blocked`,
          data: {
            missingInVhdl,
            extraInVhdl,
          },
        },
        {
          run_id: 'ui-vivado-guard',
          ts: prev.length + 1,
          step: 'preflight',
          level: 'error',
          msg: `[${backend.id}] vivado guard: missing_in_vhdl=${missingInVhdl.join(',') || '<none>'}; extra_in_vhdl=${extraInVhdl.join(',') || '<none>'}`,
        },
      ]);
      return;
    }

    void handleImplementRun();
  }, [backend.id, fileText, handleImplementRun, project.top, resolvedFpga.top, xdcText]);

  const handleDownloadSynthArtifacts = useCallback(() => {
    if (!synthRunId) return;
    void (async () => {
      const result = await backend.downloadSynthArtifacts(synthRunId, { includeSources: includeSourcesInZip });
      const artifactTagRaw = (synthArtifactId ?? synthArtifact?.artifactId ?? synthRunId).trim();
      const artifactTag = artifactTagRaw.length > 0 ? artifactTagRaw.replace(/[^a-zA-Z0-9._-]/g, '_') : synthRunId;
      const fileName = `rb-synth-${artifactTag}.zip`;
      const blob = new Blob([result.bytes], { type: 'application/zip' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      link.click();
      URL.revokeObjectURL(url);
    })().catch((error) => {
      const message = error instanceof Error ? error.message : 'synth_artifact_download_failed';
      setLogs((prev) => [
        ...prev,
        {
          run_id: synthRunId,
          ts: prev.length,
          step: 'synth',
          level: 'error',
          msg: `[${backend.id}] synth artifact download failed: ${message}`,
        },
      ]);
    });
  }, [backend, includeSourcesInZip, synthArtifact?.artifactId, synthArtifactId, synthRunId]);

  const handleDownloadImplementArtifacts = useCallback(() => {
    if (!implementRunId) return;
    void (async () => {
      const result = await backend.downloadImplementArtifacts(implementRunId, { includeSources: includeSourcesInZip });
      const artifactTagRaw = (implementArtifactId ?? implementArtifact?.artifactId ?? implementRunId).trim();
      const artifactTag = artifactTagRaw.length > 0 ? artifactTagRaw.replace(/[^a-zA-Z0-9._-]/g, '_') : implementRunId;
      const fileName = `rb-implement-${artifactTag}.zip`;
      const blob = new Blob([result.bytes], { type: 'application/zip' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      link.click();
      URL.revokeObjectURL(url);
    })().catch((error) => {
      const message = error instanceof Error ? error.message : 'implement_artifact_download_failed';
      setLogs((prev) => [
        ...prev,
        {
          run_id: implementRunId,
          ts: prev.length,
          step: 'implement',
          level: 'error',
          msg: `[${backend.id}] implement artifact download failed: ${message}`,
        },
      ]);
    });
  }, [backend, implementArtifact?.artifactId, implementArtifactId, implementRunId, includeSourcesInZip]);

  const handleProgramGeneratedBitstream = useCallback(() => {
    if (!implementRunId || programStatus === 'running') return;
    setProgramRunId(null);
    setProgramArtifactId(null);
    setProgramStatus('running');
    setIsProgramCanceling(false);

    const run_id = `ui-program-${buildRunSeqRef.current++}`;
    let ts = 0;
    const emitLocal = (level: 'info' | 'warn' | 'error', msg: string, data?: Record<string, unknown>) => {
      appendLog({
        run_id,
        ts: ts++,
        step: 'program',
        level,
        msg,
        ...(data ? { data } : {}),
      });
    };

    void (async () => {
      try {
        emitLocal('info', `[${backend.id}] program: requesting generated bitstream from ${implementRunId}`);
        const result = await backend.programImplementBitstream(implementRunId, {
          board: 'basys3',
          mode: 'sram',
        });
        setProgramRunId(result.runId);
        setProgramArtifactId(result.artifactId);
        appendLogs(result.logs ?? []);
        programOffsetRef.current = result.nextOffset ?? 0;

        if (result.state === 'running') {
          startProgramStreaming(result.runId, result.nextOffset ?? 0);
          return;
        }

        finalizeProgramRun({
          runId: result.runId,
          artifactId: result.artifactId,
          state:
            result.state === 'done' || result.state === 'error' || result.state === 'canceled'
              ? result.state
              : 'error',
          ok: result.ok === true,
          exitCode: null,
          nextOffset: result.nextOffset ?? programOffsetRef.current,
          ...(result.error ? { error: result.error } : {}),
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : 'program_generated_bitstream_failed';
        emitLocal('error', `[${backend.id}] program generated bitstream failed: ${message}`);
        clearProgramMonitoring();
        setProgramStatus('failed');
        setIsProgramCanceling(false);
      }
    })();
  }, [
    appendLog,
    appendLogs,
    backend,
    clearProgramMonitoring,
    finalizeProgramRun,
    implementRunId,
    programStatus,
    startProgramStreaming,
  ]);

  const handleCancelProgramRun = useCallback(async () => {
    if (!programRunId || isProgramCanceling) return;
    setIsProgramCanceling(true);
    try {
      const canceled = await backend.cancelRun(programRunId);
      appendLogs(canceled.logs ?? []);
      if (canceled.state !== 'running') {
        finalizeProgramRun({
          runId: canceled.runId,
          artifactId: canceled.artifactId,
          state:
            canceled.state === 'done' || canceled.state === 'error' || canceled.state === 'canceled'
              ? canceled.state
              : 'error',
          ok: canceled.ok === true,
          exitCode: canceled.exitCode,
          nextOffset: canceled.nextOffset,
          ...(canceled.error ? { error: canceled.error } : {}),
        });
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : 'program_cancel_failed';
      appendLog({
        run_id: programRunId,
        ts: programOffsetRef.current,
        step: 'program',
        level: 'error',
        msg: `[${backend.id}] program cancel failed: ${message}`,
      });
      setIsProgramCanceling(false);
    }
  }, [appendLog, appendLogs, backend, finalizeProgramRun, isProgramCanceling, programRunId]);

  const displayLogs = useMemo(() => logs.map((l) => l.msg).join('\n'), [logs]);
  const showAdvancedControls = !beginnerView;

  const toStandardStatus = useCallback((value: string): 'READY' | 'NOT READY' | 'RUNNING' | 'DONE' | 'ERROR' | 'WARNING' => {
    const normalized = value.trim().toLowerCase();
    if (normalized === 'running') return NEO_STATUS.RUNNING;
    if (normalized === 'success' || normalized === 'pass' || normalized === 'done') return NEO_STATUS.DONE;
    if (normalized === 'failed' || normalized === 'error' || normalized === 'errors') return NEO_STATUS.ERROR;
    if (normalized === 'warn' || normalized === 'warning' || normalized === 'canceled') return NEO_STATUS.WARNING;
    if (normalized === 'ok' || normalized === 'ready') return NEO_STATUS.READY;
    return NEO_STATUS.NOT_READY;
  }, []);

  const buildStatusIndicator = useMemo(() => {
    if (isSynthesizing || isImplementing || isProgramRunning || isPreflighting || isProbing) return NEO_STATUS.RUNNING;
    if (synthStatus === 'failed' || implementStatus === 'failed' || programStatus === 'failed') return NEO_STATUS.ERROR;
    if (synthStatus === 'success' || implementStatus === 'success' || programStatus === 'success') return NEO_STATUS.DONE;
    if (synthStatus === 'canceled' || implementStatus === 'canceled' || programStatus === 'canceled') return NEO_STATUS.WARNING;
    return NEO_STATUS.NOT_READY;
  }, [implementStatus, isImplementing, isPreflighting, isProbing, isProgramRunning, isSynthesizing, programStatus, synthStatus]);

  return (
    <div className={`${styles.panelRoot} rb-ui-lab-panel-frame`}>
      <div className={styles.panelHeader}>
        <div className="flex items-start justify-between gap-2">
          <div>
            <div className="text-sm font-semibold text-[#E6EDF3]">HDL Editor</div>
            <div className="text-[10px] text-[#6E7681]">
              Backend: <span className="font-mono text-[#8B949E]">{resolvedBackendId}</span>
            </div>
            <div className="text-[10px] text-[#6E7681]">
              Board: <span className="font-mono text-[#8B949E]">basys3</span>
            </div>
            <div className="text-[10px] text-[#6E7681]" data-testid="hdl-build-path-status">
              Build Path:{' '}
              <span className="font-mono text-[#8B949E]">
                {lastBuildPath ? `${lastBuildPath.backend}:${lastBuildPath.planId}` : 'unresolved'}
              </span>
            </div>
            <div className="text-[10px] text-[#6E7681]" data-testid="hdl-preflight-status">
              Preflight:{' '}
              <span className="font-mono text-[#8B949E]">
                {isPreflighting
                  ? 'running'
                  : lastPreflight
                    ? lastPreflight.overallOk
                      ? 'ok'
                      : 'errors'
                    : 'unknown'}
              </span>
            </div>
            <div className="text-[10px] text-[#6E7681]" data-testid="hdl-synth-status">
              Synth:{' '}
              <span className="font-mono text-[#8B949E]">
                {isSynthesizing ? 'running' : synthStatus === 'canceled' ? 'Canceled' : synthStatus}
              </span>
              {synthRunId ? (
                <span className="ml-2 text-[#8B949E]">
                  run: <span className="font-mono">{synthRunId}</span>
                </span>
              ) : null}
            </div>
            <div className="text-[10px] text-[#6E7681]" data-testid="hdl-implement-status">
              Implement:{' '}
              <span className="font-mono text-[#8B949E]">
                {isImplementing ? 'running' : implementStatus === 'canceled' ? 'Canceled' : implementStatus}
              </span>
              {implementRunId ? (
                <span className="ml-2 text-[#8B949E]">
                  run: <span className="font-mono">{implementRunId}</span>
                </span>
              ) : null}
            </div>
            <div className="text-[10px] text-[#6E7681]" data-testid="hdl-program-status">
              Program:{' '}
              <span className="font-mono text-[#8B949E]">
                {isProgramRunning ? 'running' : programStatus === 'canceled' ? 'Canceled' : programStatus}
              </span>
              {programRunId ? (
                <span className="ml-2 text-[#8B949E]">
                  run: <span className="font-mono">{programRunId}</span>
                </span>
              ) : null}
              {programArtifactId ? (
                <span className="ml-2 text-[#8B949E]">
                  artifact: <span className="font-mono">{programArtifactId}</span>
                </span>
              ) : null}
            </div>
          </div>

          <div className="flex items-center gap-2">
            <span
              className="px-2 py-1 text-[10px] rounded border border-[#8B949E]/30 text-[#E6EDF3]"
              data-testid="hdl-build-status-indicator"
            >
              {buildStatusIndicator}
            </span>
            {showAdvancedControls ? (
              <>
                <button
                  onClick={handleExportReport}
                  className="px-2 py-1 text-[10px] rounded border border-[#8B949E]/30 text-[#8B949E] hover:bg-[#161B22] disabled:opacity-50 disabled:cursor-not-allowed"
                  type="button"
                  disabled={!lastProbe || isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
                  data-testid="hdl-export-report-button"
                  title={!lastProbe ? 'Run Probe Toolchain first' : 'Download a JSON doctor report'}
                >
                  Export Report
                </button>
                <button
                  onClick={handleProbe}
                  className="px-2 py-1 text-[10px] rounded border border-[#8B949E]/30 text-[#8B949E] hover:bg-[#161B22] disabled:opacity-50 disabled:cursor-not-allowed"
                  type="button"
                  disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
                  data-testid="hdl-probe-button"
                >
                  {isProbing ? 'Verifying...' : 'Verify Toolchain'}
                </button>
                <button
                  onClick={handlePlanImplementation}
                  className="px-2 py-1 text-[10px] rounded border border-[#A78BFA]/40 text-[#A78BFA] hover:bg-[#A78BFA]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                  type="button"
                  disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
                  data-testid="hdl-implement-plan-button"
                >
                  {isPlanningImplement ? 'Planning...' : 'Plan Implementation'}
                </button>
                <button
                  onClick={handleGoldenDemo}
                  className="px-2 py-1 text-[10px] rounded border border-[#38BDF8]/40 text-[#38BDF8] hover:bg-[#38BDF8]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                  type="button"
                  disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
                  data-testid="hdl-golden-demo-button"
                >
                  Golden Demo: Switches → LEDs
                </button>
              </>
            ) : null}
            <button
              onClick={handleSynthesize}
              className="px-2 py-1 text-[10px] rounded border border-[#22C55E]/40 text-[#22C55E] hover:bg-[#22C55E]/10 disabled:opacity-50 disabled:cursor-not-allowed"
              type="button"
              disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
              data-testid="hdl-synth-button"
            >
              {isSynthesizing ? 'Synthesizing...' : 'Synthesize (Yosys)'}
            </button>
            {isSynthesizing && synthRunId ? (
              <button
                onClick={handleCancelSynthRun}
                className="px-2 py-1 text-[10px] rounded border border-[#EF4444]/40 text-[#FCA5A5] hover:bg-[#EF4444]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                type="button"
                disabled={isSynthCanceling}
                data-testid="hdl-synth-cancel-button"
              >
                {isSynthCanceling ? 'Canceling...' : 'Cancel Synthesis'}
              </button>
            ) : null}
            <button
              onClick={handleImplementRun}
              className="px-2 py-1 text-[10px] rounded border border-[#F59E0B]/40 text-[#F59E0B] hover:bg-[#F59E0B]/10 disabled:opacity-50 disabled:cursor-not-allowed"
              type="button"
              disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
              data-testid="hdl-implement-run-button"
            >
              {isImplementing ? 'Implementing...' : 'Implement (P&R)'}
            </button>
            {isImplementing && implementRunId ? (
              <button
                onClick={handleCancelImplementRun}
                className="px-2 py-1 text-[10px] rounded border border-[#EF4444]/40 text-[#FCA5A5] hover:bg-[#EF4444]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                type="button"
                disabled={isImplementCanceling}
                data-testid="hdl-implement-cancel-button"
              >
                {isImplementCanceling ? 'Canceling...' : 'Cancel Implement'}
              </button>
            ) : null}
            {showAdvancedControls ? (
              <>
                <button
                  onClick={handleBuild}
                  className="px-2 py-1 text-[10px] rounded border border-[#22D3EE]/40 text-[#22D3EE] hover:bg-[#22D3EE]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                  type="button"
                  disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
                  data-testid="hdl-build-button"
                >
                  {isBuilding ? 'Building...' : 'Build (stub)'}
                </button>
                <button
                  onClick={() => setLogs([])}
                  className="px-2 py-1 text-[10px] rounded border border-[#8B949E]/30 text-[#8B949E] hover:bg-[#161B22]"
                  type="button"
                  disabled={logs.length === 0}
                >
                  Clear
                </button>
              </>
            ) : null}
          </div>
        </div>

        <div className="mt-3 flex items-center justify-between gap-2">
          <div className="text-[10px] text-[#6E7681]">
            File: <span className="font-mono text-[#8B949E]">{fileName}</span>
          </div>
          <div className="flex items-center gap-2">
            <label className="flex items-center gap-2 text-[10px] text-[#6E7681]">
              <span>Top</span>
              <input
                value={project.top ?? ''}
                onChange={(e) => {
                  const nextTop = e.target.value.trim();
                  onProjectChange({
                    ...project,
                    top: nextTop.length > 0 ? nextTop : undefined,
                  });
                  if (onFpgaChange) {
                    onFpgaChange({
                      ...resolvedFpga,
                      top: nextTop.length > 0 ? nextTop : undefined,
                    });
                  }
                }}
                className="bg-[#0B0F14] border border-[#1B2028] rounded px-2 py-1 text-[10px] text-[#E6EDF3] outline-none w-24"
                placeholder={basys3TopModuleContract.topModule}
                data-testid="hdl-top-input"
              />
            </label>
            {showAdvancedControls ? (
              <label className="flex items-center gap-2 text-[10px] text-[#6E7681]">
                <span>Language</span>
                <select
                  className="bg-[#0B0F14] border border-[#1B2028] rounded px-2 py-1 text-[10px] text-[#E6EDF3] outline-none"
                  value={fileLanguage}
                  onChange={(e) => {
                    const nextLanguage = e.target.value === 'vhdl' ? 'vhdl' : 'verilog';
                    onProjectChange(upsertSource(project, fileName, { language: nextLanguage }));
                  }}
                  data-testid="hdl-language-select"
                >
                  <option value="verilog">Verilog</option>
                  <option value="vhdl">VHDL</option>
                </select>
              </label>
            ) : null}
          </div>
        </div>

        {!hasTopModule ? (
          <div className="mt-2" data-testid="hdl-empty-no-top-module">
            <EmptyStateCard
              headline="Top module not selected"
              description="Set your top module before preflight and simulation so toolchain checks can resolve the correct entry point."
              primaryLabel="Set Top Module"
              onPrimaryClick={() => {
                const target = document.querySelector('[data-testid="hdl-top-input"]');
                if (target instanceof HTMLInputElement) target.focus();
              }}
              secondaryLabel="Why this matters"
            />
          </div>
        ) : null}

        {showAdvancedControls ? (
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <div className="text-[10px] text-[#6E7681]">Examples</div>
          {basys3VerilogExamples.map((example) => (
            <button
              key={example.id}
              onClick={() => handleInsertExample(example.id)}
              className="px-2 py-1 text-[10px] rounded border border-[#8B949E]/30 text-[#8B949E] hover:bg-[#161B22]"
              type="button"
              disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
              data-testid={`hdl-example-${example.id}`}
              title={example.description}
            >
              {example.label}
            </button>
          ))}
        </div>
        ) : null}

        <div className="mt-2 flex items-center justify-between gap-2">
          <div className="text-[10px] text-[#6E7681]">
            Constraints:{' '}
            {xdcText.trim().length > 0 ? (
              <span className="text-[#22D3EE]">loaded</span>
            ) : (
              <span className="text-[#D29922]">none</span>
            )}
            {activePreset ? (
              <span className="ml-2 text-[#8B949E]">
                preset: <span className="font-mono">{activePreset}</span>
              </span>
            ) : null}
          </div>

          <div className="flex items-center gap-2">
            <label className="flex items-center gap-2 text-[10px] text-[#6E7681]">
              <span>Preset</span>
              <select
                className="bg-[#0B0F14] border border-[#1B2028] rounded px-2 py-1 text-[10px] text-[#E6EDF3] outline-none"
                value={presetToApply}
                onChange={(e) => {
                  const next = e.target.value as Basys3XdcPresetId | '';
                  setPresetToApply(next);
                }}
                data-testid="hdl-xdc-preset-select"
              >
                <option value="">Select...</option>
                {basys3XdcPresets.map((preset) => (
                  <option key={preset.id} value={preset.id}>
                    {preset.label}
                  </option>
                ))}
              </select>
            </label>
            <button
              onClick={() => {
                if (!onFpgaChange || !presetToApply) return;
                const nextText = getBasys3XdcPresetText(presetToApply);
                onFpgaChange({
                  ...resolvedFpga,
                  preset: presetToApply,
                  constraints: { type: 'xdc', text: nextText },
                });
              }}
              className="px-2 py-1 text-[10px] rounded border border-[#8B949E]/30 text-[#8B949E] hover:bg-[#161B22] disabled:opacity-50 disabled:cursor-not-allowed"
              type="button"
              disabled={!onFpgaChange || !presetToApply || isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
              data-testid="hdl-xdc-apply-preset-button"
              title={!onFpgaChange ? 'FPGA project data not available' : undefined}
            >
              Apply Preset
            </button>
          </div>
        </div>

        <div className="mt-2 grid grid-cols-2 gap-2" data-testid="hdl-readiness-checklist">
          {readinessChecks.map((item) => (
            <div
              key={item.id}
              className={`rounded border px-2 py-1 text-[10px] ${
                item.ok
                  ? 'border-green-500/40 bg-green-500/10 text-green-200'
                  : 'border-yellow-500/40 bg-yellow-500/10 text-yellow-100'
              }`}
              data-testid={`hdl-readiness-${item.id}`}
            >
              <span className="font-semibold">{item.label}:</span> {item.detail}
            </div>
          ))}
        </div>

        {showAdvancedControls ? (
        <div className="mt-2 rounded border border-[#38BDF8]/30 bg-[#38BDF8]/10 px-2 py-2 text-[10px] text-[#BAE6FD]" data-testid="hdl-toolchain-setup">
          <div className="flex items-center justify-between gap-2">
            <div>
              setup platform: <span className="font-mono">{setupPlatform}</span>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handleVerifySetup}
                type="button"
                className="px-2 py-1 text-[10px] rounded border border-[#38BDF8]/40 text-[#38BDF8] hover:bg-[#38BDF8]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={isSetupVerifying || isBuilding || isSynthesizing || isImplementing || isProgramRunning}
                data-testid="hdl-setup-verify-button"
              >
                {isSetupVerifying ? 'Verifying...' : 'Verify Setup'}
              </button>
              <button
                onClick={handleExportSetupReport}
                type="button"
                className="px-2 py-1 text-[10px] rounded border border-[#38BDF8]/40 text-[#38BDF8] hover:bg-[#38BDF8]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={isSetupVerifying || isBuilding || isSynthesizing || isImplementing || isProgramRunning}
                data-testid="hdl-setup-export-button"
              >
                Export Setup Report
              </button>
            </div>
          </div>
          <div className="mt-1 grid grid-cols-1 gap-1" data-testid="hdl-setup-required-tools">
            {requiredDemoTools.map((tool) => (
              <div key={tool.name} data-testid={`hdl-setup-tool-${tool.name}`}>
                {tool.label}: <span className="font-mono">{tool.ok ? 'ok' : 'missing'}</span>
                {' · '}
                <span className="font-mono">{tool.detail}</span>
                {tool.suggestedFix ? (
                  <>
                    {' · '}
                    <span className="font-mono">{tool.suggestedFix}</span>
                  </>
                ) : null}
              </div>
            ))}
          </div>
          <div className="mt-1 text-[10px] text-[#93C5FD]" data-testid="hdl-setup-open-app-hint">
            Verify setup in Studio, then continue with build, compare, and package.
          </div>
          <pre className="mt-1 whitespace-pre-wrap text-[10px] text-[#93C5FD]" data-testid="hdl-setup-install-commands">
            {setupCommands.map((entry) => `${entry.tool}: ${entry.command}`).join('\n')}
          </pre>
        </div>
        ) : null}

        {showAdvancedControls ? (
          <div className="mt-2 rounded border border-[#22D3EE]/30 bg-[#22D3EE]/10 px-2 py-2 text-[10px] text-[#CFFAFE]" data-testid="hdl-vivado-handoff">
            <div className="flex items-center justify-between gap-2">
              <div>
                <span className="font-semibold">Vivado Handoff</span>
                <span className="ml-2 text-[#93C5FD]">part: <span className="font-mono">{BASYS3_PART}</span></span>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownloadSynthCheckTcl}
                  type="button"
                  className="px-2 py-1 text-[10px] rounded border border-[#22D3EE]/40 text-[#67E8F9] hover:bg-[#22D3EE]/10"
                  data-testid="hdl-vivado-download-tcl-button"
                >
                  Download TCL
                </button>
                <button
                  onClick={handleRunVivadoBatch}
                  type="button"
                  className="px-2 py-1 text-[10px] rounded border border-[#F59E0B]/40 text-[#FDE68A] hover:bg-[#F59E0B]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                  disabled={isBuilding || isProbing || isSynthesizing || isImplementing || isPlanningImplement || isProgramRunning}
                  data-testid="hdl-vivado-run-batch-button"
                >
                  {isImplementing ? 'Running Vivado Batch...' : 'Run Vivado Batch'}
                </button>
              </div>
            </div>
            <div className="mt-2 flex items-center gap-2">
              <span className="text-[#93C5FD]">Vivado</span>
              <input
                value={vivadoCommand}
                onChange={(event) => {
                  setVivadoCommand(event.target.value);
                  setVivadoCommandDirty(true);
                }}
                list="hdl-vivado-command-candidates"
                className="bg-[#0B0F14] border border-[#1B2028] rounded px-2 py-1 text-[10px] text-[#E6EDF3] outline-none flex-1"
                placeholder="vivado or C:/Xilinx/Vivado/2025.1/bin/vivado.bat"
                data-testid="hdl-vivado-command-input"
              />
              <datalist id="hdl-vivado-command-candidates">
                {vivadoCommandCandidates.map((candidate) => (
                  <option key={candidate} value={candidate} />
                ))}
              </datalist>
            </div>
            <div className="mt-1 text-[#93C5FD]" data-testid="hdl-vivado-command-preview">
              command: <span className="font-mono">{vivadoBatchCommand}</span>
            </div>
            <div className="mt-1 text-[#93C5FD]" data-testid="hdl-vivado-demo-reset-hint">
              demo reset command: <span className="font-mono">Remove-Item -Recurse -Force .\vivado_out -ErrorAction SilentlyContinue</span>
            </div>
            <pre className="mt-1 whitespace-pre-wrap text-[10px] text-[#93C5FD]" data-testid="hdl-vivado-tcl-preview">
              {synthCheckTclText}
            </pre>
            <div className="mt-1 flex items-center gap-2">
              <button
                onClick={handleDemoReset}
                type="button"
                className="px-2 py-1 text-[10px] rounded border border-[#8B949E]/40 text-[#CBD5E1] hover:bg-[#161B22]"
                data-testid="hdl-vivado-demo-reset-button"
              >
                Demo Reset
              </button>
              <button
                onClick={handleInjectDemoMismatch}
                type="button"
                className="px-2 py-1 text-[10px] rounded border border-[#F59E0B]/40 text-[#FDE68A] hover:bg-[#F59E0B]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={!onFpgaChange}
                data-testid="hdl-vivado-inject-mismatch-button"
              >
                Inject XDC Mismatch
              </button>
              <button
                onClick={handleRestoreDemoMismatch}
                type="button"
                className="px-2 py-1 text-[10px] rounded border border-[#22C55E]/40 text-[#86EFAC] hover:bg-[#22C55E]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={!onFpgaChange}
                data-testid="hdl-vivado-restore-mismatch-button"
              >
                Restore XDC
              </button>
            </div>
            {vivadoReportOutputs.length > 0 ? (
              <div className="mt-1" data-testid="hdl-vivado-report-links">
                reports:{' '}
                {vivadoReportOutputs.map((output) => {
                  const label = output.name || output.pathHint || 'report';
                  const href = output.storedPath ? `file://${output.storedPath}` : undefined;
                  return href ? (
                    <a key={`${label}:${output.pathHint}`} href={href} className="ml-2 underline" target="_blank" rel="noreferrer">
                      {label}
                    </a>
                  ) : (
                    <span key={`${label}:${output.pathHint}`} className="ml-2 font-mono">{label}</span>
                  );
                })}
              </div>
            ) : null}
          </div>
        ) : null}

        {showAdvancedControls && lastBuildPath ? (
          <div className="mt-2 rounded border border-[#A78BFA]/30 bg-[#A78BFA]/10 px-2 py-2 text-[10px] text-[#DDD6FE]" data-testid="hdl-implement-plan-summary">
            <div>
              backend: <span className="font-mono">{lastBuildPath.backend}</span>
              {' · '}plan: <span className="font-mono">{lastBuildPath.planId}</span>
            </div>
            {lastBuildPath.buildpack ? (
              <div className="mt-1">
                buildpack:{' '}
                <span className="font-mono">
                  {lastBuildPath.buildpack.name}@{lastBuildPath.buildpack.version}
                </span>
              </div>
            ) : null}
            <div className="mt-1">
              required tools:{' '}
              <span className="font-mono">
                {lastBuildPath.requiredTools
                  .map((tool) => `${tool.name}:${tool.ok ? 'ok' : 'missing'}`)
                  .join(', ')}
              </span>
            </div>
            <pre className="mt-1 whitespace-pre-wrap text-[10px] text-[#C4B5FD]" data-testid="hdl-implement-plan-commands">
              {lastBuildPath.commands
                .map((command) => `${command.step}: ${command.argv.join(' ')}`)
                .join('\n')}
            </pre>
          </div>
        ) : null}

        {showAdvancedControls && synthArtifact ? (
          <div className="mt-2 rounded border border-[#22C55E]/30 bg-[#22C55E]/10 px-2 py-1 text-[10px] text-[#86EFAC]" data-testid="hdl-synth-artifact-summary">
            artifact: <span className="font-mono">{synthArtifact.artifactId}</span> - netlist{' '}
            <span className="font-mono">{synthArtifact.outputs.netlistVerilog}</span>
          </div>
        ) : null}
        {showAdvancedControls && implementArtifact ? (
          <div className="mt-2 rounded border border-[#F59E0B]/30 bg-[#F59E0B]/10 px-2 py-1 text-[10px] text-[#FCD34D]" data-testid="hdl-implement-artifact-summary">
            artifact: <span className="font-mono">{implementArtifact.artifactId}</span> - backend{' '}
            <span className="font-mono">{implementArtifact.backend}</span>
            {' · '}outputs: <span className="font-mono">{implementArtifact.outputs.length}</span>
          </div>
        ) : null}
        {showAdvancedControls && synthRunId && synthStatus !== 'idle' && synthStatus !== 'running' ? (
          <div className="mt-2 flex items-center gap-3">
            <label className="flex items-center gap-2 text-[10px] text-[#8B949E]" data-testid="hdl-synth-include-sources-label">
              <input
                type="checkbox"
                checked={includeSourcesInZip}
                onChange={(event) => setIncludeSourcesInZip(event.target.checked)}
                data-testid="hdl-synth-include-sources-checkbox"
              />
              Include sources in ZIP
            </label>
            <button
              onClick={handleDownloadSynthArtifacts}
              type="button"
              className="px-2 py-1 text-[10px] rounded border border-[#22D3EE]/40 text-[#22D3EE] hover:bg-[#22D3EE]/10 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={isSynthesizing}
              data-testid="hdl-synth-download-button"
            >
              Download Synth Artifacts
            </button>
          </div>
        ) : null}
        {showAdvancedControls && implementRunId && implementStatus !== 'idle' && implementStatus !== 'running' ? (
          <div className="mt-2 flex items-center gap-3">
            <label className="flex items-center gap-2 text-[10px] text-[#8B949E]" data-testid="hdl-implement-include-sources-label">
              <input
                type="checkbox"
                checked={includeSourcesInZip}
                onChange={(event) => setIncludeSourcesInZip(event.target.checked)}
                data-testid="hdl-implement-include-sources-checkbox"
              />
              Include sources in ZIP
            </label>
            <button
              onClick={handleDownloadImplementArtifacts}
              type="button"
              className="px-2 py-1 text-[10px] rounded border border-[#F59E0B]/40 text-[#F59E0B] hover:bg-[#F59E0B]/10 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={isImplementing}
              data-testid="hdl-implement-download-button"
            >
              Download Implement Artifacts
            </button>
          </div>
        ) : null}
        {implementRunId && implementStatus !== 'idle' && implementStatus !== 'running' && implementHasBitstreamOutput ? (
          <div className="mt-2 flex items-center gap-3" data-testid="hdl-implement-program-actions">
            <button
              onClick={handleProgramGeneratedBitstream}
              type="button"
              className="px-2 py-1 text-[10px] rounded border border-[#22C55E]/40 text-[#22C55E] hover:bg-[#22C55E]/10 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={isProgramRunning || isSynthesizing || isImplementing || isPlanningImplement || isBuilding || isProbing}
              data-testid="hdl-implement-program-button"
            >
              {isProgramRunning ? 'Programming...' : 'Program Generated Bitstream'}
            </button>
            {isProgramRunning && programRunId ? (
              <button
                onClick={handleCancelProgramRun}
                type="button"
                className="px-2 py-1 text-[10px] rounded border border-[#EF4444]/40 text-[#FCA5A5] hover:bg-[#EF4444]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={isProgramCanceling}
                data-testid="hdl-implement-program-cancel-button"
              >
                {isProgramCanceling ? 'Canceling...' : 'Cancel Program'}
              </button>
            ) : null}
          </div>
        ) : null}
      </div>

      <div className={styles.contentArea}>
        <div className={styles.editorPane}>
          <div className="mb-1 flex items-center justify-between">
            <div className="text-[10px] uppercase tracking-wide text-[#6E7681]">HDL</div>
            <button
              onClick={() => {
                navigator.clipboard.writeText(fileText).catch((err) => console.error('Copy failed:', err));
              }}
              className="px-2 py-1 text-[10px] rounded border border-[#22D3EE]/40 text-[#22D3EE] hover:bg-[#22D3EE]/10 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={!fileText.trim()}
              title="Copy VHDL to clipboard"
              type="button"
              data-testid="hdl-copy-vhdl-button"
            >
              Copy VHDL
            </button>
          </div>
          {!hasAnySource || !hasActiveSource ? (
            <div className="mb-2" data-testid="hdl-empty-no-file">
              <EmptyStateCard
                headline={hasAnySource ? 'No file selected' : 'No project file loaded'}
                description={hasAnySource
                  ? 'Choose a source file to continue editing, then run preflight and simulation from this panel.'
                  : 'Create or open an HDL file to begin build/simulate flow in this workspace.'}
                primaryLabel="Open Editor"
                onPrimaryClick={() => {
                  onProjectChange(upsertSource(project, fileName, { language: fileLanguage, text: fileText }));
                }}
                secondaryLabel="Why this matters"
              />
            </div>
          ) : null}
          <textarea
            value={fileText}
            onChange={(e) => {
              const nextText = e.target.value;
              onProjectChange(upsertSource(project, fileName, { text: nextText, language: fileLanguage }));
            }}
            className="w-full h-full resize-none rounded bg-[#0B0F14] border border-[#1B2028] p-2 font-mono text-xs text-[#E6EDF3] outline-none focus:border-[#22D3EE]/40"
            spellCheck={false}
            data-testid="hdl-editor-textarea"
          />
        </div>

        <div className={styles.constraintsPane}>
          <div className="mb-1 flex items-center justify-between">
            <div className="text-[10px] uppercase tracking-wide text-[#6E7681]">XDC Constraints</div>
            <button
              onClick={() => {
                navigator.clipboard.writeText(xdcText).catch((err) => console.error('Copy failed:', err));
              }}
              className="px-2 py-1 text-[10px] rounded border border-[#22D3EE]/40 text-[#22D3EE] hover:bg-[#22D3EE]/10 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={!xdcText.trim()}
              title="Copy XDC to clipboard"
              type="button"
              data-testid="hdl-copy-xdc-button"
            >
              Copy XDC
            </button>
          </div>
          {xdcText.trim().length === 0 ? (
            <div className="text-[10px] text-[#6E7681] mb-1">No constraints loaded</div>
          ) : null}
          <textarea
            value={xdcText}
            onChange={(e) => {
              if (!onFpgaChange) return;
              const nextText = normalizeXdcText(e.target.value);
              const nextConstraints = nextText.trim().length > 0 ? { type: 'xdc' as const, text: nextText } : undefined;
              onFpgaChange({
                ...resolvedFpga,
                preset: undefined,
                constraints: nextConstraints,
              });
            }}
            className="w-full h-full resize-none rounded bg-[#0B0F14] border border-[#1B2028] p-2 font-mono text-xs text-[#E6EDF3] outline-none focus:border-[#22D3EE]/40 disabled:opacity-60 disabled:cursor-not-allowed"
            spellCheck={false}
            disabled={!onFpgaChange}
            data-testid="hdl-xdc-textarea"
          />
        </div>
      </div>

      <div className={styles.consoleWrap}>
        <div className={styles.consoleTitle}>
          Build Console
        </div>
        <div style={{ padding: '0 1rem 0.5rem' }} data-testid="hdl-waveform-signal-legend">
          <SignalLegend
            title="Waveform Signal Legend"
            hint="Pinned and collapsible"
            showExpectedVsActual
            showDebounce
            collapsible
            defaultOpen={false}
            compact
          />
        </div>
        <div className={styles.consoleBody}>
          {logs.length === 0 ? (
            <EmptyStateCard
              testId="hdl-empty-no-sim"
              headline="Simulation not run yet"
              description="Run simulation once to populate waveform/probe evidence and build console output for this project."
              primaryLabel="Run Simulation"
              onPrimaryClick={() => {
                void handleSynthesize();
              }}
              secondaryLabel="Why this matters"
            />
          ) : (
            <pre className="text-xs text-[#E6EDF3] whitespace-pre-wrap" data-testid="hdl-build-logs">
              {displayLogs}
            </pre>
          )}
        </div>
      </div>
    </div>
  );
};
