export const UnoPinMap = {
    name: 'Arduino UNO',
    pins: {
        'D0': { id: 'D0', type: 'digital', direction: 'io', description: 'RX' },
        'D1': { id: 'D1', type: 'digital', direction: 'io', description: 'TX' },
        'D2': { id: 'D2', type: 'digital', direction: 'io' },
        'D3': { id: 'D3', type: 'digital', direction: 'io', pwm: true },
        'D4': { id: 'D4', type: 'digital', direction: 'io' },
        'D5': { id: 'D5', type: 'digital', direction: 'io', pwm: true },
        'D6': { id: 'D6', type: 'digital', direction: 'io', pwm: true },
        'D7': { id: 'D7', type: 'digital', direction: 'io' },
        'D8': { id: 'D8', type: 'digital', direction: 'io' },
        'D9': { id: 'D9', type: 'digital', direction: 'io', pwm: true },
        'D10': { id: 'D10', type: 'digital', direction: 'io', pwm: true },
        'D11': { id: 'D11', type: 'digital', direction: 'io', pwm: true },
        'D12': { id: 'D12', type: 'digital', direction: 'io' },
        'D13': { id: 'D13', type: 'digital', direction: 'io', internalLed: true },
        'A0': { id: 'A0', type: 'analog', direction: 'input' },
        'A1': { id: 'A1', type: 'analog', direction: 'input' },
        'A2': { id: 'A2', type: 'analog', direction: 'input' },
        'A3': { id: 'A3', type: 'analog', direction: 'input' },
        'A4': { id: 'A4', type: 'analog', direction: 'input' },
        'A5': { id: 'A5', type: 'analog', direction: 'input' },
        'GND': { id: 'GND', type: 'ground' },
        '5V': { id: '5V', type: 'power' },
    }
};
