import { compareCodepoint } from '../../../export/codepointSort';

const BASYS3_PART = 'xc7a35tcpg236-1';

export interface VivadoImportTclInput {
  projectName: string;
  topEntity: string;
  sourcePaths: string[];
  constraintsPath: string;
  simulationPath?: string;
  part?: string;
}

export function generateVivadoImportTcl(input: VivadoImportTclInput): string {
  const projectName = sanitizeProjectName(input.projectName);
  const topEntity = sanitizeIdentifier(input.topEntity, 'top');
  const part = (input.part ?? BASYS3_PART).trim() || BASYS3_PART;
  const sourcePaths = normalizePaths(input.sourcePaths);
  const constraintsPath = normalizePath(input.constraintsPath, 'top.xdc');
  const simulationPath = normalizePath(input.simulationPath, '');
  const sourceList = toTclFileList(sourcePaths);
  const constraintsList = toTclFileList([constraintsPath]);

  const lines: string[] = [
    '# RedByte Vivado import script (deterministic)',
    '# Generated by RedByte IDE export pipeline',
    '',
    'set script_dir [file normalize [file dirname [info script]]]',
    `set project_name "${escapeTclString(projectName)}"`,
    `set top_module "${escapeTclString(topEntity)}"`,
    `set part "${escapeTclString(part)}"`,
    'set run_synth 0',
    'set project_dir [file join $script_dir "${project_name}_vivado"]',
    '',
    'create_project -force $project_name $project_dir -part $part',
    'set_property target_language VHDL [current_project]',
    `add_files -norecurse ${sourceList}`,
    `add_files -fileset constrs_1 -norecurse ${constraintsList}`,
    'set_property top $top_module [current_fileset]',
    'update_compile_order -fileset sources_1',
  ];

  if (simulationPath.length > 0) {
    lines.push(
      '',
      `set tb_file [file join $script_dir "${escapeTclString(simulationPath)}"]`,
      'if {[file exists $tb_file]} {',
      '  add_files -fileset sim_1 -norecurse [list $tb_file]',
      '}'
    );
  }

  lines.push(
    '',
    'if {$run_synth} {',
    '  launch_runs synth_1 -jobs 4',
    '  wait_on_run synth_1',
    '}',
    '',
    'puts "RedByte Vivado import complete."',
    ''
  );

  return lines.join('\n');
}

function normalizePaths(paths: string[]): string[] {
  const normalized = new Set<string>();
  for (const path of paths) {
    const value = normalizePath(path, '');
    if (value.length === 0) continue;
    normalized.add(value);
  }
  return Array.from(normalized).sort(compareCodepoint);
}

function normalizePath(path: string | undefined, fallback: string): string {
  const value = (path ?? '').trim().replace(/\\/g, '/');
  if (value.length === 0) return fallback;
  return value;
}

function toTclFileList(paths: string[]): string {
  const entries = paths.map((path) => `[file join $script_dir "${escapeTclString(path)}"]`);
  return `[list ${entries.join(' ')}]`;
}

function sanitizeProjectName(value: string): string {
  const normalized = value
    .trim()
    .replace(/[^A-Za-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return normalized.length > 0 ? normalized : 'redbyte_project';
}

function sanitizeIdentifier(value: string, fallback: string): string {
  const normalized = value
    .trim()
    .replace(/[^A-Za-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return normalized.length > 0 ? normalized : fallback;
}

function escapeTclString(value: string): string {
  return value.replace(/\\/g, '/').replace(/"/g, '\\"');
}
