// @vitest-environment jsdom
import React from 'react';
import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render } from '@testing-library/react';
import { ScenarioBuilderPanel } from '../surfaces/ScenarioBuilderPanel';

function renderPanel() {
  return render(
    <ScenarioBuilderPanel
      inputFields={[{ id: 'sw0', label: 'SW0' }]}
      outputFields={[{ id: 'ld0', label: 'LD0' }]}
      authoredVectors={[
        { id: 'vec-0', tick: 0, inputs: { sw0: 0 }, expected: {} },
      ]}
      totalVectorCount={1}
      hasAssertedExpectedCells={false}
      draftTick={0}
      draftInputs={{ sw0: '0' }}
      draftExpected={{ ld0: '' }}
      onDraftTickChange={vi.fn()}
      onDraftInputChange={vi.fn()}
      onDraftExpectedChange={vi.fn()}
      onAddVector={vi.fn()}
      onGenerateBasics={vi.fn()}
      onRun={vi.fn()}
      onOpenProjectVectors={vi.fn()}
      onAutoGenerate={vi.fn()}
      sweepPreset="binary-count"
      sweepSeed="0"
      sweepHoldTicks={1}
      onSweepPresetChange={vi.fn()}
      onSweepSeedChange={vi.fn()}
      onSweepHoldTicksChange={vi.fn()}
      onGenerateSweep={vi.fn()}
      holdN={2}
      onHoldNChange={vi.fn()}
      onHoldN={vi.fn()}
      pulseSignal="sw0"
      onPulseSignalChange={vi.fn()}
      onPulse={vi.fn()}
      vectorsAreAutoGenerated={false}
      autoVectorBannerDismissed={true}
      onDismissAutoVectorBanner={vi.fn()}
      isFirstRun={false}
      initialExpanded={true}
      onVectorsChange={vi.fn()}
    />
  );
}

describe('ScenarioBuilderPanel progressive disclosure', () => {
  it('keeps advanced authoring helpers hidden until Advanced tools opens', () => {
    const { getByTestId, queryByTestId, queryByText } = renderPanel();

    expect(queryByText('More options')).toBeNull();
    expect(queryByTestId('ide-stimulus-sweep-tools')).toBeNull();
    expect(queryByTestId('ide-stimulus-project-vectors-tools')).toBeNull();

    fireEvent.click(getByTestId('ide-stimulus-advanced-tools-toggle'));

    expect(getByTestId('ide-stimulus-sweep-tools')).toBeTruthy();
    expect(getByTestId('ide-stimulus-project-vectors-tools')).toBeTruthy();
  });

  it('keeps the starter footer visible while project vectors and sweep stay in Advanced tools', () => {
    const { getByTestId, queryByTestId } = renderPanel();

    expect(getByTestId('ide-verify-add-vector-form')).toBeTruthy();
    expect(queryByTestId('ide-verify-open-project-vectors')).toBeNull();

    fireEvent.click(getByTestId('ide-stimulus-advanced-tools-toggle'));

    expect(getByTestId('ide-verify-open-project-vectors')).toBeTruthy();
    expect(getByTestId('ide-verify-sweep-preset')).toBeTruthy();
    expect(getByTestId('ide-verify-generate-sweep-vectors')).toBeTruthy();
  });
});
