// @vitest-environment jsdom
import React from 'react';
import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render } from '@testing-library/react';
import { ScenarioBuilderPanel } from '../surfaces/ScenarioBuilderPanel';

function renderPanel() {
  return render(
    <ScenarioBuilderPanel
      inputFields={[{ id: 'sw0', label: 'SW0' }]}
      outputFields={[{ id: 'ld0', label: 'LD0' }]}
      authoredVectors={[
        { id: 'vec-0', tick: 0, inputs: { sw0: 0 }, expected: {} },
      ]}
      totalVectorCount={1}
      hasAssertedExpectedCells={false}
      draftTick={0}
      draftInputs={{ sw0: '0' }}
      draftExpected={{ ld0: '' }}
      onDraftTickChange={vi.fn()}
      onDraftInputChange={vi.fn()}
      onDraftExpectedChange={vi.fn()}
      onAddVector={vi.fn()}
      onGenerateBasics={vi.fn()}
      onRun={vi.fn()}
      onOpenProjectVectors={vi.fn()}
      onAutoGenerate={vi.fn()}
      sweepPreset="binary-count"
      sweepSeed="0"
      sweepHoldTicks={1}
      onSweepPresetChange={vi.fn()}
      onSweepSeedChange={vi.fn()}
      onSweepHoldTicksChange={vi.fn()}
      onGenerateSweep={vi.fn()}
      holdN={2}
      onHoldNChange={vi.fn()}
      onHoldN={vi.fn()}
      pulseSignal="sw0"
      onPulseSignalChange={vi.fn()}
      onPulse={vi.fn()}
      vectorsAreAutoGenerated={false}
      autoVectorBannerDismissed={true}
      onDismissAutoVectorBanner={vi.fn()}
      isFirstRun={false}
      initialExpanded={true}
      onVectorsChange={vi.fn()}
    />
  );
}

describe('ScenarioBuilderPanel progressive disclosure', () => {
  it('keeps advanced authoring helpers hidden until More options opens', () => {
    const { getByText, getByTestId } = renderPanel();
    const moreActionsDetails = getByText('More options').closest('details');

    expect(moreActionsDetails?.hasAttribute('open')).toBe(false);

    fireEvent.click(getByText('More options'));

    expect(moreActionsDetails?.hasAttribute('open')).toBe(true);
    expect(getByTestId('ide-verify-hold-n-controls')).toBeTruthy();
    expect(getByTestId('ide-verify-pulse-controls')).toBeTruthy();
  });

  it('keeps the sweep generator tucked inside More options until explicitly opened', () => {
    const { getByText, getByTestId } = renderPanel();
    const moreActionsDetails = getByText('More options').closest('details');

    fireEvent.click(getByText('More options'));
    expect(moreActionsDetails?.hasAttribute('open')).toBe(true);
    const sweepDetails = getByText('Sweep generator').closest('details');
    expect(sweepDetails?.hasAttribute('open')).toBe(false);

    fireEvent.click(getByText('Sweep generator'));

    expect(sweepDetails?.hasAttribute('open')).toBe(true);
    expect(getByTestId('ide-verify-sweep-controls')).toBeTruthy();
  });
});