// @vitest-environment jsdom
import React from 'react';
import { describe, expect, it, vi } from 'vitest';
import { render } from '@testing-library/react';
import { ScenarioBuilderPanel } from '../surfaces/ScenarioBuilderPanel';

type RenderPanelOptions = {
  authoringModeSummary?: string;
  authoringModeHint?: string;
  isFirstRun?: boolean;
  isSequential?: boolean;
  clockLane?: {
    fieldId: string;
    badge: string;
    detail?: string;
    count: number;
    onCountChange: (count: number) => void;
    onApplyPattern: (pattern: 'alternating' | 'pulse' | 'hold-low' | 'hold-high') => void;
  };
  inputFields?: Array<{ id: string; label: string }>;
  authoredVectors?: Array<{ id: string; tick: number; inputs: Record<string, 0 | 1>; expected: Record<string, 0 | 1> }>;
};

function renderPanel(options: RenderPanelOptions = {}) {
  return render(
    <ScenarioBuilderPanel
      inputFields={options.inputFields ?? [{ id: 'sw0', label: 'SW0' }]}
      outputFields={[{ id: 'ld0', label: 'LD0' }]}
      authoredVectors={
        options.authoredVectors ?? [
          { id: 'vec-0', tick: 0, inputs: { sw0: 0 }, expected: {} },
        ]
      }
      totalVectorCount={1}
      hasAssertedExpectedCells={false}
      draftTick={0}
      draftInputs={{ sw0: '0' }}
      draftExpected={{ ld0: '' }}
      onDraftTickChange={vi.fn()}
      onDraftInputChange={vi.fn()}
      onDraftExpectedChange={vi.fn()}
      onAddVector={vi.fn()}
      onGenerateBasics={vi.fn()}
      onRun={vi.fn()}
      onOpenProjectVectors={vi.fn()}
      onAutoGenerate={vi.fn()}
      sweepPreset="binary-count"
      sweepSeed="0"
      sweepHoldTicks={1}
      onSweepPresetChange={vi.fn()}
      onSweepSeedChange={vi.fn()}
      onSweepHoldTicksChange={vi.fn()}
      onGenerateSweep={vi.fn()}
      holdN={2}
      onHoldNChange={vi.fn()}
      onHoldN={vi.fn()}
      pulseSignal="sw0"
      onPulseSignalChange={vi.fn()}
      onPulse={vi.fn()}
      vectorsAreAutoGenerated={false}
      autoVectorBannerDismissed={true}
      onDismissAutoVectorBanner={vi.fn()}
      isFirstRun={options.isFirstRun ?? false}
      isSequential={options.isSequential ?? false}
      initialExpanded={true}
      onVectorsChange={vi.fn()}
      authoringModeSummary={options.authoringModeSummary}
      authoringModeHint={options.authoringModeHint}
      clockLane={options.clockLane}
    />
  );
}

describe('ScenarioBuilderPanel authoring workspace', () => {
  it('shows one concise testbench authoring header without duplicate fact strips', () => {
    const { getByTestId, queryByTestId } = renderPanel({
      authoringModeSummary: 'Auto board clock',
      authoringModeHint:
        'CLK100MHZ runs automatically during Verify and stays out of the editable stimulus rows.',
    });

    expect(getByTestId('ide-verify-stimulus-title').textContent).toBe('Testbench cases');
    expect(getByTestId('ide-verify-stimulus-summary').textContent).toContain(
      'CLK100MHZ runs automatically'
    );
    expect(queryByTestId('ide-verify-stimulus-mode-summary')).toBeNull();
    expect(queryByTestId('ide-verify-stimulus-compact-stats')).toBeNull();
    expect(queryByTestId('ide-verify-stimulus-guidance')).toBeNull();
  });

  it('shows the combinational case-table contract directly without a disclosure', () => {
    const { getByTestId, queryByText } = renderPanel();

    const authoringPath = getByTestId('ide-verify-authoring-path');
    expect(authoringPath.dataset.authoringPath).toBe('combinational-case-table');
    expect(authoringPath.textContent).toContain('Combinational case table');
    expect(getByTestId('ide-verify-stimulus-summary').textContent).toContain('Add optional expected outputs');
    expect(queryByText('How this works')).toBeNull();
    expect(authoringPath.querySelector('details')).toBeNull();
  });

  it('shows the sequential timeline contract for clocked circuits', () => {
    const { getByTestId } = renderPanel({
      isSequential: true,
      authoringModeSummary: 'Manual clock timeline',
    });

    const authoringPath = getByTestId('ide-verify-authoring-path');
    expect(authoringPath.dataset.authoringPath).toBe('sequential-timeline');
    expect(authoringPath.textContent).toContain('Sequential timeline');
    expect(getByTestId('ide-verify-stimulus-summary').textContent).toContain('clock/reset');
    expect(getByTestId('ide-verify-stimulus-summary').textContent).toContain('timeline');
  });

  it('removes the Advanced tools disclosure from normal Verify', () => {
    const { getByTestId, queryByTestId, queryByText } = renderPanel();

    expect(queryByText('More options')).toBeNull();
    expect(queryByText('Show advanced tools')).toBeNull();
    expect(queryByTestId('ide-stimulus-advanced-tools-toggle')).toBeNull();
    expect(getByTestId('ide-stimulus-case-actions')).toBeTruthy();
    expect(queryByTestId('ide-stimulus-sweep-tools')).toBeNull();
    expect(queryByTestId('ide-stimulus-project-vectors-tools')).toBeNull();
  });

  it('keeps exactly one case action row above the grid', () => {
    const { getByTestId, queryAllByTestId, queryByTestId } = renderPanel();

    expect(getByTestId('ide-verify-add-vector-form')).toBeTruthy();
    expect(queryAllByTestId('ide-stimulus-case-actions')).toHaveLength(1);
    expect(queryByTestId('ide-verify-open-project-vectors')).toBeNull();
    expect(queryByTestId('ide-verify-sweep-preset')).toBeNull();
  });

  it('shows the first-run stimulus editor when ready vectors already exist', () => {
    const { getByTestId, queryByTestId } = renderPanel({
      isFirstRun: true,
      authoringModeSummary: 'Auto board clock',
    });

    expect(getByTestId('ide-verify-add-vector-form')).toBeTruthy();
    expect(queryByTestId('ide-verify-first-run-collapsed-strip')).toBeNull();
  });

  it('shows a manual clock row only when a clock lane config is provided', () => {
    const autoView = renderPanel({
      authoringModeSummary: 'Auto board clock',
      authoredVectors: [{ id: 'vec-0', tick: 0, inputs: { sw0: 0 }, expected: {} }],
    });
    expect(autoView.queryByTestId('ide-stimulus-clock-row')).toBeNull();
    autoView.unmount();

    const manualView = renderPanel({
      authoringModeSummary: 'Manual pulses',
      inputFields: [
        { id: 'clk', label: 'CLK' },
        { id: 'sw0', label: 'SW0' },
      ],
      authoredVectors: [{ id: 'vec-0', tick: 0, inputs: { clk: 0, sw0: 0 }, expected: {} }],
      clockLane: {
        fieldId: 'clk',
        badge: 'Clock',
        count: 4,
        onCountChange: vi.fn(),
        onApplyPattern: vi.fn(),
      },
    });

    expect(manualView.getByTestId('ide-stimulus-clock-row')).toBeTruthy();
    expect(manualView.getByTestId('ide-stimulus-clock-pattern-pulse')).toBeTruthy();
  });
});
