/**
 * Unit tests for getVerifyHint() fact-grounded selection logic.
 *
 * Each test proves:
 *   1. The triggering context fires the expected hint (non-null, contains key phrase)
 *   2. A minimal baseline context (all flags false/null) fires nothing
 *
 * Priority rule: first matching hint wins. Tests verify the correct hint fires
 * even when multiple conditions could theoretically be true.
 */

import { describe, expect, it } from 'vitest';
import {
  deriveVerifyFailurePattern,
  getVerifyHint,
  type VerifyHintContext,
} from '../verifyHints';

const BASE: VerifyHintContext = {
  hasDff: false,
  mappingComplete: true,
  allTicksFail: false,
  onlyFirstTickFails: false,
  mismatch: null,
  hasFloatingOutputWarning: false,
  pattern: null,
};

describe('getVerifyHint - baseline', () => {
  it('returns null when no condition is triggered', () => {
    expect(getVerifyHint(BASE)).toBeNull();
  });
});

describe('getVerifyHint - Hint 1: unmapped pins', () => {
  it('fires when mappingComplete is false', () => {
    const hint = getVerifyHint({ ...BASE, mappingComplete: false });
    expect(hint).toContain('pins are not mapped');
  });

  it('fires before floating-output hints when both conditions are true', () => {
    const hint = getVerifyHint({
      ...BASE,
      mappingComplete: false,
      hasFloatingOutputWarning: true,
    });
    expect(hint).toContain('pins are not mapped');
  });

  it('fires before pattern hints when mapping is incomplete', () => {
    const hint = getVerifyHint({
      ...BASE,
      mappingComplete: false,
      pattern: {
        kind: 'repeated-output',
        summary: 'This looks localized.',
        nextInspect: 'Trace the output path.',
      },
    });
    expect(hint).toContain('pins are not mapped');
  });
});

describe('getVerifyHint - Hint 2: floating/undriven output', () => {
  it('fires when hasFloatingOutputWarning is true', () => {
    const hint = getVerifyHint({ ...BASE, hasFloatingOutputWarning: true });
    expect(hint).toContain('undriven');
  });

  it('fires before pattern hints when floating output warnings are present', () => {
    const hint = getVerifyHint({
      ...BASE,
      hasFloatingOutputWarning: true,
      pattern: {
        kind: 'delayed',
        summary: 'The circuit diverges later.',
        nextInspect: 'Compare the first failing tick.',
      },
    });
    expect(hint).toContain('undriven');
  });
});

describe('getVerifyHint - legacy all-ticks and first-tick hints', () => {
  it('fires when allTicksFail is true (auto-generated vectors, no DFF — priority-3 fallback)', () => {
    // Priority-3 fires when vectorsAreAutoGenerated=true bypasses the "loaded example" hint (priority-2).
    // Priority-2 fires for user-authored vectors (!vectorsAreAutoGenerated) and catches "wrong example" cases.
    const hint = getVerifyHint({ ...BASE, allTicksFail: true, vectorsAreAutoGenerated: true });
    expect(hint).toContain('Every tick fails');
  });

  it('fires auto-generated-example hint when allTicksFail and vectors are not auto-generated', () => {
    const hint = getVerifyHint({ ...BASE, allTicksFail: true, vectorsAreAutoGenerated: false });
    expect(hint).toContain('All vectors failed');
  });

  it('fires when onlyFirstTickFails is true', () => {
    const hint = getVerifyHint({ ...BASE, onlyFirstTickFails: true });
    expect(hint).toContain('first sampled case fails');
    expect(hint).not.toContain('initial/reset');
  });
});

describe('getVerifyHint - pattern-aware hints', () => {
  it('treats Auto tick 0 as the first sampled cycle, not pre-edge startup', () => {
    const pattern = deriveVerifyFailurePattern({
      totalRows: 2,
      failCount: 1,
      selectedFailure: { tick: 0, signal: 'q' },
      selectedPeerFailCount: 0,
      selectedSignalFailTickCount: 1,
      selectedSignalFirstFailTick: 0,
      firstFailureTick: 0,
      firstRunTick: 0,
      isSequentialRun: true,
      hasResetSignalRole: true,
      tick0Meaning: null,
      samplePoint: 'post-rising-edge',
    });

    expect(pattern?.kind).toBe('selected-case');
    expect(pattern?.summary).not.toContain('startup');
    expect(pattern?.nextInspect).not.toContain('before the first clocked update');
  });

  it('distinguishes repeated single-output failure from grouped peer failure', () => {
    const repeatedHint = getVerifyHint({
      ...BASE,
      pattern: {
        kind: 'repeated-output',
        summary: 'This looks localized to ld0.',
        nextInspect: 'Trace ld0.',
      },
    });
    const groupedHint = getVerifyHint({
      ...BASE,
      pattern: {
        kind: 'grouped-peer',
        summary: 'These failures occur together.',
        nextInspect: 'Inspect shared state.',
      },
    });

    expect(repeatedHint).toContain('localized to one output failing repeatedly');
    expect(groupedHint).toContain('occur together at the same tick');
  });

  it('surfaces startup guidance for startup-oriented failures', () => {
    const hint = getVerifyHint({
      ...BASE,
      hasDff: true,
      pattern: {
        kind: 'startup',
        summary: 'The first mismatch appears immediately at startup.',
        nextInspect: 'Inspect reset.',
      },
    });
    expect(hint).toContain('appears immediately at startup');
  });

  it('surfaces delayed divergence guidance when the circuit passes at first', () => {
    const hint = getVerifyHint({
      ...BASE,
      hasDff: true,
      pattern: {
        kind: 'delayed',
        summary: 'The circuit passes at first, then diverges later at t5.',
        nextInspect: 'Compare the last passing tick.',
      },
    });
    expect(hint).toContain('passes at first, then diverges later');
  });

  it('keeps broad all-run failure ahead of later logic-shape hints', () => {
    const hint = getVerifyHint({
      ...BASE,
      pattern: {
        kind: 'all-run',
        summary: 'Every verify row fails.',
        nextInspect: 'Inspect shared inputs.',
      },
      mismatch: { expected: '1', actual: '0' },
    });
    expect(hint).toContain('Every verify row fails');
  });
});

describe('getVerifyHint - legacy DFF and combinational fallbacks', () => {
  it('fires DFF high-to-low guidance when no pattern override is present', () => {
    const hint = getVerifyHint({
      ...BASE,
      hasDff: true,
      mismatch: { expected: '1', actual: '0' },
    });
    expect(hint).toContain('Output should be HIGH but is LOW');
  });

  it('fires DFF low-to-high guidance when no pattern override is present', () => {
    const hint = getVerifyHint({
      ...BASE,
      hasDff: true,
      mismatch: { expected: '0', actual: '1' },
    });
    expect(hint).toContain('Output should be LOW but is HIGH');
  });

  it('fires combinational mismatch guidance when no pattern override is present', () => {
    const hint = getVerifyHint({
      ...BASE,
      hasDff: false,
      mismatch: { expected: '1', actual: '0' },
    });
    expect(hint).toContain('Combinational mismatch');
  });
});
