import type { IdeExampleDefinition } from './examplesCatalog';

export interface LabStarter {
  id: string;
  labNumber: number;
  title: string;
  description: string;
  difficulty: 'intro' | 'intermediate' | 'advanced';
  estimatedMinutes: number;
  example: IdeExampleDefinition;
}

export const LAB_STARTERS: LabStarter[] = [
  {
    id: 'lab1-gates',
    labNumber: 1,
    title: 'Lab 1 — Basic Logic Gates',
    description: 'Build AND, OR, and NOT circuits. SW inputs drive LED outputs.',
    difficulty: 'intro',
    estimatedMinutes: 30,
    example: {
      id: 'lab1-gates',
      name: 'Lab 1 Starter — Basic Gates',
      summary: 'Two-switch, one-LED scaffold. Wire an AND gate between SW0/SW1 and LD0.',
      course: 'ECE141',
      lab: 'Lab 1',
      concept: 'Combinational Logic',
      tags: ['gates', 'starter', 'lab1'],
      expectedBehavior: 'LD0 lights when both SW0 and SW1 are high (after wiring AND gate).',
      goals: [
        'Wire an AND gate between SW0, SW1 and LD0',
        'Add test vectors and run Verify',
        'Map pins to Basys3 and export',
      ],
      ioRows: [
        { id: 'sw0', nodeId: 'sw0_node', port: 'out', label: 'SW0', direction: 'in',  pin: 'V17', required: true },
        { id: 'sw1', nodeId: 'sw1_node', port: 'out', label: 'SW1', direction: 'in',  pin: 'V16', required: true },
        { id: 'ld0', nodeId: 'ld0_node', port: 'in',  label: 'LD0', direction: 'out', pin: 'U16', required: true },
      ],
      vectors: [],
      circuit: {
        nodes: [
          { id: 'sw0_node', type: 'INPUT',  x: 100, y: 120, label: 'SW0', config: {}, state: {} },
          { id: 'sw1_node', type: 'INPUT',  x: 100, y: 240, label: 'SW1', config: {}, state: {} },
          { id: 'ld0_node', type: 'OUTPUT', x: 500, y: 180, label: 'LD0', config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
  {
    id: 'lab2-combinational',
    labNumber: 2,
    title: 'Lab 2 — Combinational Logic',
    description: 'Implement a sum-of-products Boolean expression using gate primitives.',
    difficulty: 'intro',
    estimatedMinutes: 45,
    example: {
      id: 'lab2-combinational',
      name: 'Lab 2 Starter — Combinational Logic',
      summary: 'Three-switch, two-LED scaffold for a Boolean expression circuit.',
      course: 'ECE141',
      lab: 'Lab 2',
      concept: 'Boolean Algebra',
      tags: ['combinational', 'starter', 'lab2'],
      expectedBehavior: 'Implement the required Boolean expression. LD0 and LD1 driven by gate logic.',
      goals: [
        'Build the sum-of-products circuit from your truth table',
        'Add all 8 input combinations as test vectors',
        'Run Verify — all vectors must pass',
      ],
      ioRows: [
        { id: 'sw0', nodeId: 'sw0_node', port: 'out', label: 'SW0', direction: 'in',  pin: 'V17', required: true },
        { id: 'sw1', nodeId: 'sw1_node', port: 'out', label: 'SW1', direction: 'in',  pin: 'V16', required: true },
        { id: 'sw2', nodeId: 'sw2_node', port: 'out', label: 'SW2', direction: 'in',  pin: 'W16', required: true },
        { id: 'ld0', nodeId: 'ld0_node', port: 'in',  label: 'LD0', direction: 'out', pin: 'U16', required: true },
        { id: 'ld1', nodeId: 'ld1_node', port: 'in',  label: 'LD1', direction: 'out', pin: 'E19', required: true },
      ],
      vectors: [],
      circuit: {
        nodes: [
          { id: 'sw0_node', type: 'INPUT',  x: 100, y: 100, label: 'SW0', config: {}, state: {} },
          { id: 'sw1_node', type: 'INPUT',  x: 100, y: 200, label: 'SW1', config: {}, state: {} },
          { id: 'sw2_node', type: 'INPUT',  x: 100, y: 300, label: 'SW2', config: {}, state: {} },
          { id: 'ld0_node', type: 'OUTPUT', x: 550, y: 150, label: 'LD0', config: {}, state: {} },
          { id: 'ld1_node', type: 'OUTPUT', x: 550, y: 270, label: 'LD1', config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
  {
    id: 'lab3-mux',
    labNumber: 3,
    title: 'Lab 3 — Multiplexer',
    description: 'Build a 2-to-1 multiplexer from basic gates and verify with all selector combinations.',
    difficulty: 'intro',
    estimatedMinutes: 45,
    example: {
      id: 'lab3-mux',
      name: 'Lab 3 Starter — Multiplexer',
      summary: '3 inputs (D0, D1, SEL) and 1 output (Y). Wire a 2-to-1 MUX.',
      course: 'ECE141',
      lab: 'Lab 3',
      concept: 'Multiplexers',
      tags: ['mux', 'starter', 'lab3'],
      expectedBehavior: 'Y = D0 when SEL=0; Y = D1 when SEL=1.',
      goals: [
        'Build a 2-to-1 MUX from AND, OR, and NOT gates',
        'Add all 8 test vectors (D0, D1, SEL combinations)',
        'Run Verify — confirm correct selection behavior',
      ],
      ioRows: [
        { id: 'd0',  nodeId: 'd0_node',  port: 'out', label: 'D0',  direction: 'in',  pin: 'V17', required: true },
        { id: 'd1',  nodeId: 'd1_node',  port: 'out', label: 'D1',  direction: 'in',  pin: 'V16', required: true },
        { id: 'sel', nodeId: 'sel_node', port: 'out', label: 'SEL', direction: 'in',  pin: 'W16', required: true },
        { id: 'y',   nodeId: 'y_node',   port: 'in',  label: 'Y',   direction: 'out', pin: 'U16', required: true },
      ],
      vectors: [],
      circuit: {
        nodes: [
          { id: 'd0_node',  type: 'INPUT',  x: 100, y: 100, label: 'D0',  config: {}, state: {} },
          { id: 'd1_node',  type: 'INPUT',  x: 100, y: 200, label: 'D1',  config: {}, state: {} },
          { id: 'sel_node', type: 'INPUT',  x: 100, y: 300, label: 'SEL', config: {}, state: {} },
          { id: 'y_node',   type: 'OUTPUT', x: 550, y: 190, label: 'Y',   config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
  {
    id: 'lab4-decoder',
    labNumber: 4,
    title: 'Lab 4 — Decoder',
    description: 'Implement a 2-to-4 binary decoder. Each output activates for exactly one input combination.',
    difficulty: 'intermediate',
    estimatedMinutes: 60,
    example: {
      id: 'lab4-decoder',
      name: 'Lab 4 Starter — 2-to-4 Decoder',
      summary: '2 inputs (A, B) and 4 outputs (Y0–Y3). Exactly one output is high at a time.',
      course: 'ECE141',
      lab: 'Lab 4',
      concept: 'Decoders',
      tags: ['decoder', 'starter', 'lab4'],
      expectedBehavior: 'Y0 high when AB=00; Y1 high when AB=01; Y2 high when AB=10; Y3 high when AB=11.',
      goals: [
        'Build 2-to-4 decoder using AND and NOT gates',
        'Add all 4 input combinations as test vectors',
        'Run Verify — confirm only one output active per vector',
      ],
      ioRows: [
        { id: 'a',  nodeId: 'a_node',  port: 'out', label: 'A',  direction: 'in',  pin: 'V17', required: true },
        { id: 'b',  nodeId: 'b_node',  port: 'out', label: 'B',  direction: 'in',  pin: 'V16', required: true },
        { id: 'y0', nodeId: 'y0_node', port: 'in',  label: 'Y0', direction: 'out', pin: 'U16', required: true },
        { id: 'y1', nodeId: 'y1_node', port: 'in',  label: 'Y1', direction: 'out', pin: 'E19', required: true },
        { id: 'y2', nodeId: 'y2_node', port: 'in',  label: 'Y2', direction: 'out', pin: 'U19', required: true },
        { id: 'y3', nodeId: 'y3_node', port: 'in',  label: 'Y3', direction: 'out', pin: 'V19', required: true },
      ],
      vectors: [],
      circuit: {
        nodes: [
          { id: 'a_node',  type: 'INPUT',  x: 100, y: 120, label: 'A',  config: {}, state: {} },
          { id: 'b_node',  type: 'INPUT',  x: 100, y: 240, label: 'B',  config: {}, state: {} },
          { id: 'y0_node', type: 'OUTPUT', x: 550, y:  80, label: 'Y0', config: {}, state: {} },
          { id: 'y1_node', type: 'OUTPUT', x: 550, y: 160, label: 'Y1', config: {}, state: {} },
          { id: 'y2_node', type: 'OUTPUT', x: 550, y: 240, label: 'Y2', config: {}, state: {} },
          { id: 'y3_node', type: 'OUTPUT', x: 550, y: 320, label: 'Y3', config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
  {
    id: 'lab5-adder',
    labNumber: 5,
    title: 'Lab 5 — Half Adder',
    description: 'Build a 1-bit half adder. Sum (XOR) and Carry (AND) outputs.',
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    example: {
      id: 'lab5-adder',
      name: 'Lab 5 Starter — Half Adder',
      summary: 'Two inputs (A, B) and two outputs (SUM, CARRY). Wire the half adder.',
      course: 'ECE141',
      lab: 'Lab 5',
      concept: 'Arithmetic Circuits',
      tags: ['adder', 'arithmetic', 'starter', 'lab5'],
      expectedBehavior: 'SUM = A XOR B; CARRY = A AND B.',
      goals: [
        'Wire a half adder using XOR and AND gates',
        'Add all 4 input combinations as test vectors',
        'Run Verify — SUM and CARRY must match the truth table',
      ],
      ioRows: [
        { id: 'a',     nodeId: 'a_node',     port: 'out', label: 'A',     direction: 'in',  pin: 'V17', required: true },
        { id: 'b',     nodeId: 'b_node',     port: 'out', label: 'B',     direction: 'in',  pin: 'V16', required: true },
        { id: 'sum',   nodeId: 'sum_node',   port: 'in',  label: 'SUM',   direction: 'out', pin: 'U16', required: true },
        { id: 'carry', nodeId: 'carry_node', port: 'in',  label: 'CARRY', direction: 'out', pin: 'E19', required: true },
      ],
      vectors: [
        { tick: 0, inputs: { a_node: 0, b_node: 0 }, expected: { sum_node: 0, carry_node: 0 } },
        { tick: 1, inputs: { a_node: 0, b_node: 1 }, expected: { sum_node: 1, carry_node: 0 } },
        { tick: 2, inputs: { a_node: 1, b_node: 0 }, expected: { sum_node: 1, carry_node: 0 } },
        { tick: 3, inputs: { a_node: 1, b_node: 1 }, expected: { sum_node: 0, carry_node: 1 } },
      ],
      circuit: {
        nodes: [
          { id: 'a_node',     type: 'INPUT',  x: 100, y: 140, label: 'A',     config: {}, state: {} },
          { id: 'b_node',     type: 'INPUT',  x: 100, y: 240, label: 'B',     config: {}, state: {} },
          { id: 'sum_node',   type: 'OUTPUT', x: 550, y: 140, label: 'SUM',   config: {}, state: {} },
          { id: 'carry_node', type: 'OUTPUT', x: 550, y: 240, label: 'CARRY', config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
  {
    id: 'lab6-full-adder',
    labNumber: 6,
    title: 'Lab 6 — Full Adder',
    description: 'Extend the half adder with a carry-in input to build a 1-bit full adder.',
    difficulty: 'intermediate',
    estimatedMinutes: 60,
    example: {
      id: 'lab6-full-adder',
      name: 'Lab 6 Starter — Full Adder',
      summary: 'Three inputs (A, B, Cin) and two outputs (SUM, Cout).',
      course: 'ECE141',
      lab: 'Lab 6',
      concept: 'Arithmetic Circuits',
      tags: ['adder', 'arithmetic', 'starter', 'lab6'],
      expectedBehavior: 'SUM and Cout implement 1-bit full addition with carry-in.',
      goals: [
        'Compose two half adders and an OR gate',
        'Add all 8 input combinations as test vectors',
        'Run Verify — all vectors must match the truth table',
      ],
      ioRows: [
        { id: 'a',    nodeId: 'a_node',    port: 'out', label: 'A',    direction: 'in',  pin: 'V17', required: true },
        { id: 'b',    nodeId: 'b_node',    port: 'out', label: 'B',    direction: 'in',  pin: 'V16', required: true },
        { id: 'cin',  nodeId: 'cin_node',  port: 'out', label: 'Cin',  direction: 'in',  pin: 'W16', required: true },
        { id: 'sum',  nodeId: 'sum_node',  port: 'in',  label: 'SUM',  direction: 'out', pin: 'U16', required: true },
        { id: 'cout', nodeId: 'cout_node', port: 'in',  label: 'Cout', direction: 'out', pin: 'E19', required: true },
      ],
      vectors: [
        { tick: 0, inputs: { a_node: 0, b_node: 0, cin_node: 0 }, expected: { sum_node: 0, cout_node: 0 } },
        { tick: 1, inputs: { a_node: 0, b_node: 0, cin_node: 1 }, expected: { sum_node: 1, cout_node: 0 } },
        { tick: 2, inputs: { a_node: 0, b_node: 1, cin_node: 0 }, expected: { sum_node: 1, cout_node: 0 } },
        { tick: 3, inputs: { a_node: 0, b_node: 1, cin_node: 1 }, expected: { sum_node: 0, cout_node: 1 } },
        { tick: 4, inputs: { a_node: 1, b_node: 0, cin_node: 0 }, expected: { sum_node: 1, cout_node: 0 } },
        { tick: 5, inputs: { a_node: 1, b_node: 0, cin_node: 1 }, expected: { sum_node: 0, cout_node: 1 } },
        { tick: 6, inputs: { a_node: 1, b_node: 1, cin_node: 0 }, expected: { sum_node: 0, cout_node: 1 } },
        { tick: 7, inputs: { a_node: 1, b_node: 1, cin_node: 1 }, expected: { sum_node: 1, cout_node: 1 } },
      ],
      circuit: {
        nodes: [
          { id: 'a_node',    type: 'INPUT',  x: 100, y: 120, label: 'A',    config: {}, state: {} },
          { id: 'b_node',    type: 'INPUT',  x: 100, y: 220, label: 'B',    config: {}, state: {} },
          { id: 'cin_node',  type: 'INPUT',  x: 100, y: 320, label: 'Cin',  config: {}, state: {} },
          { id: 'sum_node',  type: 'OUTPUT', x: 550, y: 170, label: 'SUM',  config: {}, state: {} },
          { id: 'cout_node', type: 'OUTPUT', x: 550, y: 270, label: 'Cout', config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
  {
    id: 'lab7-comparator',
    labNumber: 7,
    title: 'Lab 7 — 1-bit Magnitude Comparator',
    description: 'Determine if A > B, A = B, or A < B for single-bit inputs.',
    difficulty: 'intermediate',
    estimatedMinutes: 60,
    example: {
      id: 'lab7-comparator',
      name: 'Lab 7 Starter — Magnitude Comparator',
      summary: 'Two inputs (A, B) and three outputs (GT, EQ, LT) for comparison.',
      course: 'ECE141',
      lab: 'Lab 7',
      concept: 'Comparators',
      tags: ['comparator', 'starter', 'lab7'],
      expectedBehavior: 'Exactly one of GT, EQ, LT is high for each input pair.',
      goals: [
        'Build the comparator using XNOR, AND, and NOT gates',
        'Add all 4 input combinations as test vectors',
        'Run Verify — confirm mutual exclusion of outputs',
      ],
      ioRows: [
        { id: 'a',  nodeId: 'a_node',  port: 'out', label: 'A',  direction: 'in',  pin: 'V17', required: true },
        { id: 'b',  nodeId: 'b_node',  port: 'out', label: 'B',  direction: 'in',  pin: 'V16', required: true },
        { id: 'gt', nodeId: 'gt_node', port: 'in',  label: 'GT', direction: 'out', pin: 'U16', required: true },
        { id: 'eq', nodeId: 'eq_node', port: 'in',  label: 'EQ', direction: 'out', pin: 'E19', required: true },
        { id: 'lt', nodeId: 'lt_node', port: 'in',  label: 'LT', direction: 'out', pin: 'U19', required: true },
      ],
      vectors: [
        { tick: 0, inputs: { a_node: 0, b_node: 0 }, expected: { gt_node: 0, eq_node: 1, lt_node: 0 } },
        { tick: 1, inputs: { a_node: 0, b_node: 1 }, expected: { gt_node: 0, eq_node: 0, lt_node: 1 } },
        { tick: 2, inputs: { a_node: 1, b_node: 0 }, expected: { gt_node: 1, eq_node: 0, lt_node: 0 } },
        { tick: 3, inputs: { a_node: 1, b_node: 1 }, expected: { gt_node: 0, eq_node: 1, lt_node: 0 } },
      ],
      circuit: {
        nodes: [
          { id: 'a_node',  type: 'INPUT',  x: 100, y: 120, label: 'A',  config: {}, state: {} },
          { id: 'b_node',  type: 'INPUT',  x: 100, y: 240, label: 'B',  config: {}, state: {} },
          { id: 'gt_node', type: 'OUTPUT', x: 550, y: 120, label: 'GT', config: {}, state: {} },
          { id: 'eq_node', type: 'OUTPUT', x: 550, y: 220, label: 'EQ', config: {}, state: {} },
          { id: 'lt_node', type: 'OUTPUT', x: 550, y: 320, label: 'LT', config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
  {
    id: 'lab8-sr-latch',
    labNumber: 8,
    title: 'Lab 8 — SR Latch',
    description: 'Build a basic SR latch using NOR gates. First sequential circuit.',
    difficulty: 'advanced',
    estimatedMinutes: 75,
    example: {
      id: 'lab8-sr-latch',
      name: 'Lab 8 Starter — SR Latch',
      summary: 'Two inputs (S, R) and two outputs (Q, Qbar). NOR-based SR latch.',
      course: 'ECE141',
      lab: 'Lab 8',
      concept: 'Sequential Logic',
      tags: ['latch', 'sequential', 'starter', 'lab8'],
      expectedBehavior: 'Q=1 after S=1,R=0. Q=0 after S=0,R=1. Q holds when both inputs=0.',
      goals: [
        'Build the SR latch using two cross-coupled NOR gates',
        'Understand the hold state (S=0, R=0)',
        'Verify set and reset behavior with test vectors',
      ],
      ioRows: [
        { id: 's',    nodeId: 's_node',    port: 'out', label: 'S',    direction: 'in',  pin: 'V17', required: true },
        { id: 'r',    nodeId: 'r_node',    port: 'out', label: 'R',    direction: 'in',  pin: 'V16', required: true },
        { id: 'q',    nodeId: 'q_node',    port: 'in',  label: 'Q',    direction: 'out', pin: 'U16', required: true },
        { id: 'qbar', nodeId: 'qbar_node', port: 'in',  label: 'Qbar', direction: 'out', pin: 'E19', required: true },
      ],
      vectors: [],
      circuit: {
        nodes: [
          { id: 's_node',    type: 'INPUT',  x: 100, y: 140, label: 'S',    config: {}, state: {} },
          { id: 'r_node',    type: 'INPUT',  x: 100, y: 260, label: 'R',    config: {}, state: {} },
          { id: 'q_node',    type: 'OUTPUT', x: 550, y: 140, label: 'Q',    config: {}, state: {} },
          { id: 'qbar_node', type: 'OUTPUT', x: 550, y: 260, label: 'Qbar', config: {}, state: {} },
        ],
        connections: [],
      },
    },
  },
];

export function getLabStarterById(id: string): LabStarter | undefined {
  return LAB_STARTERS.find((s) => s.id === id);
}
