import type { TestVector } from '@redbyte/rb-utils';

export type ProjectKind = 'home' | 'blank' | 'example' | 'custom' | 'import' | 'saved';
export type ScenarioAuthority = 'none' | 'starter' | 'draft' | 'authored' | 'verified' | 'stale';

const PROJECT_KINDS: ReadonlySet<ProjectKind> = new Set([
  'home',
  'blank',
  'example',
  'custom',
  'import',
  'saved',
]);

const SCENARIO_AUTHORITIES: ReadonlySet<ScenarioAuthority> = new Set([
  'none',
  'starter',
  'draft',
  'authored',
  'verified',
  'stale',
]);

export function normalizeProjectKind(
  value: unknown,
  fallback: ProjectKind = 'blank'
): ProjectKind {
  return typeof value === 'string' && PROJECT_KINDS.has(value as ProjectKind)
    ? (value as ProjectKind)
    : fallback;
}

export function normalizeScenarioAuthority(
  value: unknown,
  fallback: ScenarioAuthority = 'none'
): ScenarioAuthority {
  return typeof value === 'string' && SCENARIO_AUTHORITIES.has(value as ScenarioAuthority)
    ? (value as ScenarioAuthority)
    : fallback;
}

export function hasExpectedOutputs(vectors: ReadonlyArray<TestVector> | undefined): boolean {
  return (vectors ?? []).some((vector) => Object.keys(vector.expected ?? {}).length > 0);
}

export function stripExpectedOutputs(vectors: ReadonlyArray<TestVector>): TestVector[] {
  return vectors.map((vector) => ({
    ...vector,
    expected: {},
  }));
}

export function deriveScenarioAuthority(input: {
  projectKind: ProjectKind;
  activeExampleId?: string | null;
  hasVectors: boolean;
  hasAssertions: boolean;
  dirtySinceVerify: boolean;
  verifyStatus?: 'pass' | 'fail' | null;
  vectorsAreAutoGenerated?: boolean;
}): ScenarioAuthority {
  if (!input.hasVectors) return 'none';
  if (input.dirtySinceVerify && input.verifyStatus) return 'stale';
  if (
    input.projectKind === 'example' &&
    input.activeExampleId &&
    input.vectorsAreAutoGenerated
  ) {
    return 'starter';
  }
  if (input.verifyStatus === 'pass' && input.hasAssertions) return 'verified';
  if (input.hasAssertions) return 'authored';
  return 'draft';
}

export function getProjectKindDisplayName(kind: ProjectKind): string {
  if (kind === 'home') return 'Project Home';
  if (kind === 'blank') return 'Blank Project';
  if (kind === 'example') return 'Example Project';
  if (kind === 'import') return 'Imported Project';
  if (kind === 'saved') return 'Saved Project';
  return 'Custom Project';
}
