/**
 * Contract gate: Export/Verify trust + project readiness model.
 *
 * Tests the pure data-structure algorithms for:
 *
 *   1. isStarterScenarioFail derivation — only softens when vectorsAreAutoGenerated=true
 *   2. isNoRunYet — distinct from starter fail
 *   3. nextActionTitle / nextActionDetail copy selection — 5 distinct branches
 *   4. gateRows verify tone — warn for starter/no-run, error for authored fail
 *   5. Pipeline gate policy — starter fail proceeds, authored fail hard-blocks
 *   6. RBEV1001 evidence diagnostic message — starter-specific vs standard
 *   7. readiness strip axes — design / scenario / verify independently
 *   8. Export-available note visibility in VerifySurface — only when design OK
 *   9. Trust pill label — AVAILABLE vs UNVERIFIED vs READY vs BLOCKED
 *  10. Authored fail path is NOT softened — stays hard gate
 */

import { describe, expect, it } from 'vitest';

// ─── Type mirrors ──────────────────────────────────────────────────────────────

interface MockVerifyResult {
  status: 'pass' | 'fail';
  failingTick?: number;
  hash?: string;
}

interface MockVerifyRun {
  qualification?: 'incomplete-mapping' | string;
}

type DisplayStatus = 'BLOCKED' | 'READY' | 'RUNNING' | 'PASS' | 'FAIL' | 'TRACE' | 'STALE';

// ─── Algorithm mirrors ─────────────────────────────────────────────────────────

function deriveIsStarterScenarioFail(opts: {
  hasBlockingErrors: boolean;
  vectorsAreAutoGenerated: boolean;
  verifyResult: MockVerifyResult | undefined;
  dirtySinceVerify: boolean;
  verifyLastRunQualification: string | undefined;
}): boolean {
  return (
    !opts.hasBlockingErrors &&
    opts.vectorsAreAutoGenerated &&
    opts.verifyResult?.status === 'fail' &&
    !opts.dirtySinceVerify &&
    opts.verifyLastRunQualification !== 'incomplete-mapping'
  );
}

function deriveIsNoRunYet(verifyResult: MockVerifyResult | undefined): boolean {
  return !verifyResult;
}

function selectNextActionTitle(opts: {
  exportTrusted: boolean;
  hasBlockingErrors: boolean;
  isStarterScenarioFail: boolean;
  isNoRunYet: boolean;
}): string {
  if (opts.exportTrusted) return 'Open Vivado and import the generated project.';
  if (opts.hasBlockingErrors) return 'Resolve blockers before downloading the build package.';
  if (opts.isStarterScenarioFail) return 'Export available — scenario not yet authored.';
  if (opts.isNoRunYet) return 'Export available — no verification run yet.';
  return '⚠ Verify first — this export may fail in Vivado.';
}

function selectVerifyGateTone(opts: {
  hasVerifyPass: boolean;
  isStarterScenarioFail: boolean;
  isNoRunYet: boolean;
  dirtySinceVerify: boolean;
  hasVerifyResult: boolean;
}): 'ok' | 'warn' | 'error' {
  if (opts.hasVerifyPass) return 'ok';
  if (opts.dirtySinceVerify && opts.hasVerifyResult) return 'error';
  if (opts.isStarterScenarioFail) return 'warn';
  if (opts.isNoRunYet) return 'warn';
  if (opts.hasVerifyResult) return 'error';
  return 'warn';
}

function selectVerifyGateDetail(opts: {
  hasVerifyPass: boolean;
  isStarterScenarioFail: boolean;
  isNoRunYet: boolean;
  dirtySinceVerify: boolean;
  failingTick: number | undefined;
}): string {
  if (opts.hasVerifyPass) return 'Complete';
  if (opts.dirtySinceVerify) return 'Stale — design changed';
  if (opts.isStarterScenarioFail) return 'Unsealed — starter scenario';
  if (opts.isNoRunYet) return 'Not run yet';
  return typeof opts.failingTick === 'number' ? `Outputs differ · t${opts.failingTick}` : 'Outputs differ';
}

/** Mirror of pipeline gate policy */
type PipelineStepResult = 'done' | 'warn' | 'error';
function pipelineClockGate(opts: {
  vectorsAreAutoGenerated: boolean;
  verifyResult: MockVerifyResult | undefined;
  dirtySinceVerify: boolean;
  verifyLastRunQualification: string | undefined;
}): { result: PipelineStepResult; detail: string } {
  const isStarterFail =
    opts.vectorsAreAutoGenerated &&
    opts.verifyResult?.status === 'fail' &&
    !opts.dirtySinceVerify &&
    opts.verifyLastRunQualification !== 'incomplete-mapping';

  if (isStarterFail) {
    return { result: 'warn', detail: 'Unsealed — starter scenario' };
  }
  if (
    !opts.verifyResult ||
    opts.verifyResult.status !== 'pass' ||
    opts.dirtySinceVerify ||
    opts.verifyLastRunQualification === 'incomplete-mapping'
  ) {
    return { result: 'error', detail: 'Verify PASS required' };
  }
  return { result: 'done', detail: '' };
}

/** Mirror of readiness strip axis derivation */
function deriveReadinessStrip(opts: {
  hasBlockingErrors: boolean;
  vectorsAreAutoGenerated: boolean;
  isStarterScenarioFail: boolean;
  isNoRunYet: boolean;
  exportTrusted: boolean;
  hasAuthoredFail: boolean;
}): { design: string; scenario: string; verify: string } {
  const design = opts.hasBlockingErrors ? 'blocked' : 'valid';
  const scenario = opts.vectorsAreAutoGenerated ? 'starter' : opts.isNoRunYet ? 'none' : 'authored';
  const verify = opts.exportTrusted
    ? 'sealed'
    : opts.isStarterScenarioFail
      ? 'unsealed'
      : opts.isNoRunYet
        ? 'never-run'
        : opts.hasAuthoredFail
          ? 'failed'
          : 'unsealed';
  return { design, scenario, verify };
}

/** Mirror of evidence diagnostic message selection */
function selectEvidenceMessage(opts: {
  verifyResult: MockVerifyResult | undefined;
  vectorsAreAutoGenerated: boolean;
}): string {
  if (!opts.verifyResult) {
    return 'No verification run found. Export files are still available, but the handoff is unverified.';
  }
  if (opts.verifyResult.status !== 'pass') {
    if (opts.vectorsAreAutoGenerated) {
      return 'Ran with auto-generated starter vectors — scenario not yet authored. Export is available but unsealed.';
    }
    return typeof opts.verifyResult.failingTick === 'number'
      ? `Latest verification failed at tick ${opts.verifyResult.failingTick}. Export files remain viewable.`
      : 'Latest verification failed. Export files remain viewable.';
  }
  return '';
}

/** Mirror of VerifySurface export-available note visibility */
function shouldShowExportAvailableNote(opts: {
  displayStatus: DisplayStatus;
  mappingComplete: boolean | undefined;
  hasOnGoToExport: boolean;
}): boolean {
  return (
    opts.displayStatus === 'FAIL' &&
    opts.mappingComplete !== false &&
    opts.hasOnGoToExport
  );
}

/** Mirror of trust pill label */
function selectTrustPillLabel(opts: {
  exportTrusted: boolean;
  hasBlockingErrors: boolean;
  isStarterScenarioFail: boolean;
  isNoRunYet: boolean;
}): string {
  if (opts.exportTrusted) return 'AVAILABLE';
  if (opts.hasBlockingErrors) return 'BLOCKED';
  if (opts.isStarterScenarioFail || opts.isNoRunYet) return 'AVAILABLE';
  return 'UNVERIFIED';
}

// ─── isStarterScenarioFail derivation ────────────────────────────────────────

describe('isStarterScenarioFail derivation', () => {
  const base = {
    hasBlockingErrors: false,
    vectorsAreAutoGenerated: true,
    verifyResult: { status: 'fail' as const },
    dirtySinceVerify: false,
    verifyLastRunQualification: undefined,
  };

  it('is true when auto-generated vectors fail with no other blockers', () => {
    expect(deriveIsStarterScenarioFail(base)).toBe(true);
  });

  it('is false when vectorsAreAutoGenerated=false (authored scenario)', () => {
    expect(deriveIsStarterScenarioFail({ ...base, vectorsAreAutoGenerated: false })).toBe(false);
  });

  it('is false when hasBlockingErrors=true', () => {
    expect(deriveIsStarterScenarioFail({ ...base, hasBlockingErrors: true })).toBe(false);
  });

  it('is false when dirtySinceVerify=true', () => {
    expect(deriveIsStarterScenarioFail({ ...base, dirtySinceVerify: true })).toBe(false);
  });

  it('is false when qualification=incomplete-mapping', () => {
    expect(deriveIsStarterScenarioFail({ ...base, verifyLastRunQualification: 'incomplete-mapping' })).toBe(false);
  });

  it('is false when verifyResult.status=pass', () => {
    expect(deriveIsStarterScenarioFail({ ...base, verifyResult: { status: 'pass' } })).toBe(false);
  });

  it('is false when verifyResult is absent', () => {
    expect(deriveIsStarterScenarioFail({ ...base, verifyResult: undefined })).toBe(false);
  });
});

// ─── isNoRunYet derivation ────────────────────────────────────────────────────

describe('isNoRunYet derivation', () => {
  it('is true when verifyResult is undefined', () => {
    expect(deriveIsNoRunYet(undefined)).toBe(true);
  });

  it('is false when verifyResult is present (pass)', () => {
    expect(deriveIsNoRunYet({ status: 'pass' })).toBe(false);
  });

  it('is false when verifyResult is present (fail)', () => {
    expect(deriveIsNoRunYet({ status: 'fail' })).toBe(false);
  });

  it('no-run and starter-fail are distinct: no-run has no verifyResult, starter-fail does', () => {
    const noRun = deriveIsNoRunYet(undefined);
    const starterFail = deriveIsNoRunYet({ status: 'fail' });
    expect(noRun).toBe(true);
    expect(starterFail).toBe(false); // starter fail has a result (fail), just auto-generated
  });
});

// ─── nextActionTitle copy selection ──────────────────────────────────────────

describe('nextActionTitle copy selection', () => {
  it('trusted: returns vivado instruction', () => {
    const title = selectNextActionTitle({ exportTrusted: true, hasBlockingErrors: false, isStarterScenarioFail: false, isNoRunYet: false });
    expect(title).toBe('Open Vivado and import the generated project.');
  });

  it('blocking errors: returns resolve blockers instruction', () => {
    const title = selectNextActionTitle({ exportTrusted: false, hasBlockingErrors: true, isStarterScenarioFail: false, isNoRunYet: false });
    expect(title).toContain('Resolve blockers');
  });

  it('starter scenario fail: returns positive availability message', () => {
    const title = selectNextActionTitle({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: true, isNoRunYet: false });
    expect(title).toBe('Export available — scenario not yet authored.');
  });

  it('no run yet: returns positive availability message', () => {
    const title = selectNextActionTitle({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: false, isNoRunYet: true });
    expect(title).toBe('Export available — no verification run yet.');
  });

  it('authored fail: returns verify-first warning', () => {
    const title = selectNextActionTitle({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: false, isNoRunYet: false });
    expect(title).toContain('⚠ Verify first');
  });

  it('starter fail does NOT say "⚠ Verify first"', () => {
    const title = selectNextActionTitle({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: true, isNoRunYet: false });
    expect(title).not.toContain('⚠');
  });
});

// ─── gateRows verify tone ────────────────────────────────────────────────────

describe('gateRows verify tone', () => {
  it('ok when verify passes', () => {
    expect(selectVerifyGateTone({ hasVerifyPass: true, isStarterScenarioFail: false, isNoRunYet: false, dirtySinceVerify: false, hasVerifyResult: true })).toBe('ok');
  });

  it('warn for starter scenario fail', () => {
    expect(selectVerifyGateTone({ hasVerifyPass: false, isStarterScenarioFail: true, isNoRunYet: false, dirtySinceVerify: false, hasVerifyResult: true })).toBe('warn');
  });

  it('warn for no run yet', () => {
    expect(selectVerifyGateTone({ hasVerifyPass: false, isStarterScenarioFail: false, isNoRunYet: true, dirtySinceVerify: false, hasVerifyResult: false })).toBe('warn');
  });

  it('error for authored scenario fail', () => {
    expect(selectVerifyGateTone({ hasVerifyPass: false, isStarterScenarioFail: false, isNoRunYet: false, dirtySinceVerify: false, hasVerifyResult: true })).toBe('error');
  });

  it('error for stale (design changed after PASS)', () => {
    expect(selectVerifyGateTone({ hasVerifyPass: false, isStarterScenarioFail: false, isNoRunYet: false, dirtySinceVerify: true, hasVerifyResult: true })).toBe('error');
  });
});

// ─── gateRows verify detail ──────────────────────────────────────────────────

describe('gateRows verify detail text', () => {
  it('starter fail → "Unsealed — starter scenario"', () => {
    expect(selectVerifyGateDetail({ hasVerifyPass: false, isStarterScenarioFail: true, isNoRunYet: false, dirtySinceVerify: false, failingTick: undefined })).toBe('Unsealed — starter scenario');
  });

  it('no run → "Not run yet"', () => {
    expect(selectVerifyGateDetail({ hasVerifyPass: false, isStarterScenarioFail: false, isNoRunYet: true, dirtySinceVerify: false, failingTick: undefined })).toBe('Not run yet');
  });

  it('authored fail with tick → includes tick number', () => {
    expect(selectVerifyGateDetail({ hasVerifyPass: false, isStarterScenarioFail: false, isNoRunYet: false, dirtySinceVerify: false, failingTick: 3 })).toBe('Outputs differ · t3');
  });

  it('stale → "Stale — design changed"', () => {
    expect(selectVerifyGateDetail({ hasVerifyPass: false, isStarterScenarioFail: false, isNoRunYet: false, dirtySinceVerify: true, failingTick: undefined })).toBe('Stale — design changed');
  });
});

// ─── Pipeline clock gate policy ───────────────────────────────────────────────

describe('pipeline clock gate policy', () => {
  it('starter scenario fail → warn (soft pass, pipeline continues)', () => {
    const result = pipelineClockGate({ vectorsAreAutoGenerated: true, verifyResult: { status: 'fail' }, dirtySinceVerify: false, verifyLastRunQualification: undefined });
    expect(result.result).toBe('warn');
    expect(result.detail).toBe('Unsealed — starter scenario');
  });

  it('authored scenario fail → error (hard block)', () => {
    const result = pipelineClockGate({ vectorsAreAutoGenerated: false, verifyResult: { status: 'fail' }, dirtySinceVerify: false, verifyLastRunQualification: undefined });
    expect(result.result).toBe('error');
    expect(result.detail).toBe('Verify PASS required');
  });

  it('no run → error (hard block)', () => {
    const result = pipelineClockGate({ vectorsAreAutoGenerated: false, verifyResult: undefined, dirtySinceVerify: false, verifyLastRunQualification: undefined });
    expect(result.result).toBe('error');
  });

  it('no run + vectorsAreAutoGenerated → error (not a fail, just no run)', () => {
    // No run is NOT a starter fail — you can't have a starter fail without a result
    const result = pipelineClockGate({ vectorsAreAutoGenerated: true, verifyResult: undefined, dirtySinceVerify: false, verifyLastRunQualification: undefined });
    expect(result.result).toBe('error');
  });

  it('stale design + auto-generated → error (dirtySinceVerify blocks)', () => {
    const result = pipelineClockGate({ vectorsAreAutoGenerated: true, verifyResult: { status: 'fail' }, dirtySinceVerify: true, verifyLastRunQualification: undefined });
    expect(result.result).toBe('error');
  });

  it('incomplete-mapping qualification + auto-generated → error (not softened)', () => {
    const result = pipelineClockGate({ vectorsAreAutoGenerated: true, verifyResult: { status: 'fail' }, dirtySinceVerify: false, verifyLastRunQualification: 'incomplete-mapping' });
    expect(result.result).toBe('error');
  });

  it('passing verify → done', () => {
    const result = pipelineClockGate({ vectorsAreAutoGenerated: false, verifyResult: { status: 'pass' }, dirtySinceVerify: false, verifyLastRunQualification: undefined });
    expect(result.result).toBe('done');
  });
});

// ─── Evidence diagnostic messages ────────────────────────────────────────────

describe('evidence diagnostic message (RBEV1001)', () => {
  it('no run → generic no-run message', () => {
    const msg = selectEvidenceMessage({ verifyResult: undefined, vectorsAreAutoGenerated: false });
    expect(msg).toContain('No verification run found');
  });

  it('starter fail → starter-specific message, not "failed at tick"', () => {
    const msg = selectEvidenceMessage({ verifyResult: { status: 'fail', failingTick: 2 }, vectorsAreAutoGenerated: true });
    expect(msg).toContain('starter vectors');
    expect(msg).toContain('unsealed');
    expect(msg).not.toContain('failed at tick');
  });

  it('authored fail with tick → tick-specific message', () => {
    const msg = selectEvidenceMessage({ verifyResult: { status: 'fail', failingTick: 2 }, vectorsAreAutoGenerated: false });
    expect(msg).toContain('tick 2');
  });

  it('authored fail without tick → generic fail message', () => {
    const msg = selectEvidenceMessage({ verifyResult: { status: 'fail' }, vectorsAreAutoGenerated: false });
    expect(msg).toContain('Latest verification failed');
    expect(msg).not.toContain('tick');
  });
});

// ─── Readiness strip axes ────────────────────────────────────────────────────

describe('readiness strip axes — three independent axes', () => {
  it('design: blocked when hasBlockingErrors', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: true, vectorsAreAutoGenerated: false, isStarterScenarioFail: false, isNoRunYet: false, exportTrusted: false, hasAuthoredFail: false });
    expect(strip.design).toBe('blocked');
  });

  it('design: valid when no blocking errors', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: false, isStarterScenarioFail: false, isNoRunYet: true, exportTrusted: false, hasAuthoredFail: false });
    expect(strip.design).toBe('valid');
  });

  it('scenario: starter when vectorsAreAutoGenerated=true', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: true, isStarterScenarioFail: true, isNoRunYet: false, exportTrusted: false, hasAuthoredFail: false });
    expect(strip.scenario).toBe('starter');
  });

  it('scenario: authored when vectorsAreAutoGenerated=false and has a run', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: false, isStarterScenarioFail: false, isNoRunYet: false, exportTrusted: false, hasAuthoredFail: true });
    expect(strip.scenario).toBe('authored');
  });

  it('scenario: none when no run and not auto-generated', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: false, isStarterScenarioFail: false, isNoRunYet: true, exportTrusted: false, hasAuthoredFail: false });
    expect(strip.scenario).toBe('none');
  });

  it('verify: sealed when exportTrusted', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: false, isStarterScenarioFail: false, isNoRunYet: false, exportTrusted: true, hasAuthoredFail: false });
    expect(strip.verify).toBe('sealed');
  });

  it('verify: unsealed for starter scenario fail', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: true, isStarterScenarioFail: true, isNoRunYet: false, exportTrusted: false, hasAuthoredFail: false });
    expect(strip.verify).toBe('unsealed');
  });

  it('verify: failed for authored scenario fail', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: false, isStarterScenarioFail: false, isNoRunYet: false, exportTrusted: false, hasAuthoredFail: true });
    expect(strip.verify).toBe('failed');
  });

  it('verify: never-run when isNoRunYet', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: false, isStarterScenarioFail: false, isNoRunYet: true, exportTrusted: false, hasAuthoredFail: false });
    expect(strip.verify).toBe('never-run');
  });

  it('three axes are independent — design valid with starter/unsealed combo', () => {
    const strip = deriveReadinessStrip({ hasBlockingErrors: false, vectorsAreAutoGenerated: true, isStarterScenarioFail: true, isNoRunYet: false, exportTrusted: false, hasAuthoredFail: false });
    expect(strip.design).toBe('valid');
    expect(strip.scenario).toBe('starter');
    expect(strip.verify).toBe('unsealed');
  });
});

// ─── VerifySurface export-available note visibility ───────────────────────────

describe('VerifySurface export-available note visibility', () => {
  it('shown when FAIL + mappingComplete=true + onGoToExport provided', () => {
    expect(shouldShowExportAvailableNote({ displayStatus: 'FAIL', mappingComplete: true, hasOnGoToExport: true })).toBe(true);
  });

  it('hidden when FAIL + mappingComplete=false (structural blocker)', () => {
    expect(shouldShowExportAvailableNote({ displayStatus: 'FAIL', mappingComplete: false, hasOnGoToExport: true })).toBe(false);
  });

  it('hidden when PASS (not needed in pass state)', () => {
    expect(shouldShowExportAvailableNote({ displayStatus: 'PASS', mappingComplete: true, hasOnGoToExport: true })).toBe(false);
  });

  it('hidden when no onGoToExport handler', () => {
    expect(shouldShowExportAvailableNote({ displayStatus: 'FAIL', mappingComplete: true, hasOnGoToExport: false })).toBe(false);
  });

  it('shown when FAIL + mappingComplete=undefined (undefined treated as not-false)', () => {
    expect(shouldShowExportAvailableNote({ displayStatus: 'FAIL', mappingComplete: undefined, hasOnGoToExport: true })).toBe(true);
  });
});

// ─── Trust pill label ─────────────────────────────────────────────────────────

describe('trust pill label', () => {
  it('BLOCKED when hasBlockingErrors', () => {
    expect(selectTrustPillLabel({ exportTrusted: false, hasBlockingErrors: true, isStarterScenarioFail: false, isNoRunYet: false })).toBe('BLOCKED');
  });

  it('AVAILABLE for starter scenario fail', () => {
    expect(selectTrustPillLabel({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: true, isNoRunYet: false })).toBe('AVAILABLE');
  });

  it('AVAILABLE for no run yet', () => {
    expect(selectTrustPillLabel({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: false, isNoRunYet: true })).toBe('AVAILABLE');
  });

  it('UNVERIFIED for authored fail', () => {
    expect(selectTrustPillLabel({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: false, isNoRunYet: false })).toBe('UNVERIFIED');
  });

  it('AVAILABLE (from exportTrusted path) when trusted', () => {
    // Note: in the actual component, exportTrusted renders 'READY FOR VIVADO', not 'AVAILABLE'
    // This test verifies the non-trusted AVAILABLE cases are distinct from UNVERIFIED
    const trusted = selectTrustPillLabel({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: true, isNoRunYet: false });
    const unverified = selectTrustPillLabel({ exportTrusted: false, hasBlockingErrors: false, isStarterScenarioFail: false, isNoRunYet: false });
    expect(trusted).not.toBe(unverified);
    expect(trusted).toBe('AVAILABLE');
    expect(unverified).toBe('UNVERIFIED');
  });
});
