/**
 * Contract gate: Sequential First-Class + Verify Trust.
 *
 * Tests the pure data-structure algorithms and display-state rules used by
 * VerifySurface and ScenarioBuilderPanel for:
 *
 *   1. isSequentialRun derivation — hasDff OR clocked_macro schedule OR lastRun sequential
 *   2. clockSignals set — built from normalizeSignalRoles where role === 'clock'
 *   3. FAIL qualification — vectorsAreAutoGenerated=true + FAIL → qualifier shown
 *   4. Sequential mode badge — isSequentialRun=true → badge shown in scope header
 *   5. Starter vector clock transitions — sequential starters include alternating clock ticks
 *   6. ScenarioBuilderPanel sequential guidance — isSequential=true → guidance shown
 *   7. Combinational behavior is unchanged — hasDff=false → no sequential treatment
 */

import { describe, expect, it } from 'vitest';

// ─── Type mirrors ──────────────────────────────────────────────────────────────

type VerifyRunSchedule = 'clocked_macro' | 'combinational' | string;

interface MockLastRun {
  status: 'pass' | 'fail';
  schedule?: VerifyRunSchedule;
  meta?: { circuitKind?: string };
  report?: { signalRoles?: Record<string, 'clock' | 'reset' | 'input' | 'output'> };
}

// ─── Algorithm mirrors ─────────────────────────────────────────────────────────

function normalizeFieldId(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9_]/g, '_');
}

/** Mirror of isSequentialRun derivation in VerifySurface */
function deriveIsSequentialRun(
  hasDff: boolean,
  lastRun?: MockLastRun
): boolean {
  return Boolean(
    hasDff ||
    lastRun?.meta?.circuitKind === 'sequential' ||
    lastRun?.schedule === 'clocked_macro'
  );
}

/** Mirror of clockSignals computation in VerifySurface */
function buildClockSignals(
  signalRoles: Record<string, 'clock' | 'reset' | 'input' | 'output'>
): Set<string> {
  const normalized: Record<string, 'clock' | 'reset' | 'input' | 'output'> = {};
  for (const [key, role] of Object.entries(signalRoles)) {
    normalized[normalizeFieldId(key)] = role;
  }
  const s = new Set<string>();
  for (const [key, role] of Object.entries(normalized)) {
    if (role === 'clock') s.add(key);
  }
  return s;
}

/** Mirror of FAIL qualification display condition */
function shouldShowAutoVectorFailNote(
  displayStatus: 'BLOCKED' | 'READY' | 'RUNNING' | 'PASS' | 'FAIL' | 'TRACE' | 'STALE',
  vectorsAreAutoGenerated: boolean
): boolean {
  return displayStatus === 'FAIL' && vectorsAreAutoGenerated;
}

/** Mirror of sequential badge display condition */
function shouldShowSeqBadge(isSequentialRun: boolean): boolean {
  return isSequentialRun;
}

/** Mirror of ScenarioBuilderPanel sequential guidance condition */
function shouldShowSequentialGuidance(isSequential: boolean): boolean {
  return isSequential;
}

/** Minimal sequential starter vector shape validator */
interface StarterVector {
  tick: number;
  inputs: Record<string, 0 | 1>;
}

function hasClockTransitions(
  vectors: StarterVector[],
  clockFieldId: string
): boolean {
  // At least one tick where clock goes from 0→1 (rising edge)
  for (let i = 1; i < vectors.length; i++) {
    const prev = vectors[i - 1]!.inputs[clockFieldId] ?? 0;
    const curr = vectors[i]!.inputs[clockFieldId] ?? 0;
    if (prev === 0 && curr === 1) return true;
  }
  return false;
}

function hasResetDeassert(
  vectors: StarterVector[],
  resetFieldId: string
): boolean {
  // At least one tick where reset transitions 1→0 (deassert)
  for (let i = 1; i < vectors.length; i++) {
    const prev = vectors[i - 1]!.inputs[resetFieldId] ?? 0;
    const curr = vectors[i]!.inputs[resetFieldId] ?? 0;
    if (prev === 1 && curr === 0) return true;
  }
  return false;
}

// ─── Fixtures ──────────────────────────────────────────────────────────────────

function makeSequentialStarterVectors(): StarterVector[] {
  // Mirrors buildSequentialBringUpVectors: clk alternates, rst=1 for tick 0-1
  return [
    { tick: 0, inputs: { clk: 0, rst: 1, en: 0 } },
    { tick: 1, inputs: { clk: 1, rst: 1, en: 0 } },
    { tick: 2, inputs: { clk: 0, rst: 0, en: 1 } },
    { tick: 3, inputs: { clk: 1, rst: 0, en: 1 } },
    { tick: 4, inputs: { clk: 0, rst: 0, en: 1 } },
    { tick: 5, inputs: { clk: 1, rst: 0, en: 1 } },
    { tick: 6, inputs: { clk: 0, rst: 0, en: 1 } },
    { tick: 7, inputs: { clk: 1, rst: 0, en: 1 } },
  ];
}

// ─── isSequentialRun derivation ────────────────────────────────────────────────

describe('isSequentialRun derivation', () => {
  it('is true when hasDff=true, regardless of lastRun', () => {
    expect(deriveIsSequentialRun(true, undefined)).toBe(true);
  });

  it('is true when lastRun.schedule === clocked_macro', () => {
    expect(deriveIsSequentialRun(false, { status: 'pass', schedule: 'clocked_macro' })).toBe(true);
  });

  it('is true when lastRun.meta.circuitKind === sequential', () => {
    expect(deriveIsSequentialRun(false, { status: 'pass', meta: { circuitKind: 'sequential' } })).toBe(true);
  });

  it('is false when hasDff=false and no sequential lastRun', () => {
    expect(deriveIsSequentialRun(false, { status: 'pass', schedule: 'combinational' })).toBe(false);
  });

  it('is false when no lastRun and hasDff=false', () => {
    expect(deriveIsSequentialRun(false, undefined)).toBe(false);
  });

  it('hasDff takes precedence even when lastRun is combinational', () => {
    expect(deriveIsSequentialRun(true, { status: 'fail', schedule: 'combinational' })).toBe(true);
  });
});

// ─── clockSignals set ──────────────────────────────────────────────────────────

describe('clockSignals set building', () => {
  it('includes signals with role=clock', () => {
    const set = buildClockSignals({ clk: 'clock', rst: 'reset', q: 'output' });
    expect(set.has('clk')).toBe(true);
  });

  it('excludes reset, input, output signals', () => {
    const set = buildClockSignals({ clk: 'clock', rst: 'reset', a: 'input', q: 'output' });
    expect(set.has('rst')).toBe(false);
    expect(set.has('a')).toBe(false);
    expect(set.has('q')).toBe(false);
  });

  it('normalizes signal names (CLK100MHZ → clk100mhz)', () => {
    const set = buildClockSignals({ CLK100MHZ: 'clock' });
    expect(set.has('clk100mhz')).toBe(true);
  });

  it('normalizes signal names with spaces (CLK IN → clk_in)', () => {
    const set = buildClockSignals({ 'CLK IN': 'clock' });
    expect(set.has('clk_in')).toBe(true);
  });

  it('returns empty set when no clock signals', () => {
    const set = buildClockSignals({ a: 'input', b: 'input', q: 'output' });
    expect(set.size).toBe(0);
  });

  it('returns empty set for empty roles', () => {
    const set = buildClockSignals({});
    expect(set.size).toBe(0);
  });

  it('handles multiple clock signals', () => {
    const set = buildClockSignals({ clk: 'clock', clk2: 'clock', rst: 'reset' });
    expect(set.has('clk')).toBe(true);
    expect(set.has('clk2')).toBe(true);
    expect(set.size).toBe(2);
  });
});

// ─── FAIL qualification (auto-vector note) ─────────────────────────────────────

describe('FAIL qualification: auto-vector note', () => {
  it('shows note when FAIL + vectorsAreAutoGenerated=true', () => {
    expect(shouldShowAutoVectorFailNote('FAIL', true)).toBe(true);
  });

  it('does NOT show note when FAIL + vectorsAreAutoGenerated=false', () => {
    expect(shouldShowAutoVectorFailNote('FAIL', false)).toBe(false);
  });

  it('does NOT show note when PASS + vectorsAreAutoGenerated=true', () => {
    expect(shouldShowAutoVectorFailNote('PASS', true)).toBe(false);
  });

  it('does NOT show note when READY + vectorsAreAutoGenerated=true', () => {
    expect(shouldShowAutoVectorFailNote('READY', true)).toBe(false);
  });

  it('does NOT show note when STALE + vectorsAreAutoGenerated=true', () => {
    expect(shouldShowAutoVectorFailNote('STALE', true)).toBe(false);
  });

  it('does NOT show note when BLOCKED + vectorsAreAutoGenerated=true', () => {
    expect(shouldShowAutoVectorFailNote('BLOCKED', true)).toBe(false);
  });
});

// ─── Sequential mode badge ─────────────────────────────────────────────────────

describe('sequential mode badge', () => {
  it('shows badge when isSequentialRun=true', () => {
    expect(shouldShowSeqBadge(true)).toBe(true);
  });

  it('does not show badge when isSequentialRun=false', () => {
    expect(shouldShowSeqBadge(false)).toBe(false);
  });

  it('badge driven by hasDff=true propagating to isSequentialRun', () => {
    const isSeq = deriveIsSequentialRun(true, undefined);
    expect(shouldShowSeqBadge(isSeq)).toBe(true);
  });

  it('no badge for pure combinational circuit', () => {
    const isSeq = deriveIsSequentialRun(false, { status: 'pass', schedule: 'combinational' });
    expect(shouldShowSeqBadge(isSeq)).toBe(false);
  });
});

// ─── ScenarioBuilderPanel guidance ────────────────────────────────────────────

describe('ScenarioBuilderPanel sequential guidance', () => {
  it('guidance shown when isSequential=true', () => {
    expect(shouldShowSequentialGuidance(true)).toBe(true);
  });

  it('guidance hidden when isSequential=false', () => {
    expect(shouldShowSequentialGuidance(false)).toBe(false);
  });

  it('guidance hidden by default (no prop = false)', () => {
    expect(shouldShowSequentialGuidance(false)).toBe(false);
  });
});

// ─── Starter vector clock transitions ─────────────────────────────────────────

describe('sequential starter vectors — clock transitions', () => {
  const vectors = makeSequentialStarterVectors();

  it('starter vectors have a rising clock edge (0→1)', () => {
    expect(hasClockTransitions(vectors, 'clk')).toBe(true);
  });

  it('starter vectors have reset deassert (1→0)', () => {
    expect(hasResetDeassert(vectors, 'rst')).toBe(true);
  });

  it('starter vectors have at least 4 ticks', () => {
    expect(vectors.length).toBeGreaterThanOrEqual(4);
  });

  it('tick 0 has rst=1 (reset asserted at start)', () => {
    const tick0 = vectors.find((v) => v.tick === 0);
    expect(tick0?.inputs['rst']).toBe(1);
  });

  it('later ticks have rst=0 (reset released after initialization)', () => {
    const laterTicks = vectors.filter((v) => v.tick >= 3);
    expect(laterTicks.every((v) => v.inputs['rst'] === 0)).toBe(true);
  });

  it('clock alternates between 0 and 1 (not stuck)', () => {
    const clkValues = vectors.map((v) => v.inputs['clk']);
    const hasHigh = clkValues.some((v) => v === 1);
    const hasLow = clkValues.some((v) => v === 0);
    expect(hasHigh).toBe(true);
    expect(hasLow).toBe(true);
  });
});

// ─── Combinational behavior preservation ──────────────────────────────────────

describe('combinational behavior — no sequential treatment leaks', () => {
  it('combinational circuit gets no sequential badge', () => {
    const isSeq = deriveIsSequentialRun(false, { status: 'pass', schedule: 'combinational' });
    expect(isSeq).toBe(false);
    expect(shouldShowSeqBadge(isSeq)).toBe(false);
  });

  it('combinational circuit gets no ScenarioBuilderPanel guidance', () => {
    const isSeq = deriveIsSequentialRun(false, undefined);
    expect(shouldShowSequentialGuidance(isSeq)).toBe(false);
  });

  it('clockSignals set is empty for pure combinational signal roles', () => {
    const set = buildClockSignals({ sw0: 'input', sw1: 'input', led0: 'output' });
    expect(set.size).toBe(0);
  });
});

// ─── clockSignals: live-authority merge ───────────────────────────────────────
//
// Slice 28 gate: clockSignals in VerifySurface must be populated from live
// signal roles even when no verify run exists yet.
//
// VerifySurface receives `liveSignalRoles` from IdeApp (deriveIoSignalRoles).
// The merge rule: live roles provide the baseline; run signal roles override
// on conflict (they are the most precise since the run has actually wired
// signals). This means:
//   - no run → liveSignalRoles drives clockSignals
//   - run exists → run roles override live roles per signal
//   - combinational liveRoles + no run → empty clockSignals (no leak)

type SignalRole = 'clock' | 'reset' | 'input' | 'output';

/** Mirror of normalizeFieldId in VerifySurface */
function normalizeFieldIdForRoles(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9_]/g, '_');
}

/** Mirror of merged signalRoleLookup in VerifySurface after slice 28 fix */
function buildMergedClockSignals(
  liveSignalRoles: Record<string, SignalRole>,
  runSignalRoles: Record<string, SignalRole>
): Set<string> {
  // Merge: live is baseline, run overrides on conflict
  const merged: Record<string, SignalRole> = {};
  for (const [key, role] of Object.entries(liveSignalRoles)) {
    merged[normalizeFieldIdForRoles(key)] = role;
  }
  for (const [key, role] of Object.entries(runSignalRoles)) {
    merged[normalizeFieldIdForRoles(key)] = role;
  }
  const s = new Set<string>();
  for (const [key, role] of Object.entries(merged)) {
    if (role === 'clock') s.add(key);
  }
  return s;
}

describe('clockSignals: live-authority merge (slice 28)', () => {
  it('sequential design, no run: liveSignalRoles with clock → non-empty clockSignals', () => {
    const live: Record<string, SignalRole> = { CLK100MHZ: 'clock', sw0: 'input', led0: 'output' };
    const runRoles: Record<string, SignalRole> = {};
    const set = buildMergedClockSignals(live, runRoles);
    expect(set.size).toBeGreaterThan(0);
    expect(set.has('clk100mhz')).toBe(true);
  });

  it('clk label in liveRoles → normalized to clk in clockSignals without run', () => {
    const live: Record<string, SignalRole> = { clk: 'clock', rst: 'reset', q: 'output' };
    const set = buildMergedClockSignals(live, {});
    expect(set.has('clk')).toBe(true);
    expect(set.size).toBe(1);
  });

  it('run signal roles override live on conflict (run clock identity wins)', () => {
    // Live says CLK100MHZ is clock; run reclassifies it as input (hypothetical conflict)
    const live: Record<string, SignalRole> = { CLK100MHZ: 'clock' };
    const run: Record<string, SignalRole> = { CLK100MHZ: 'input' };
    const set = buildMergedClockSignals(live, run);
    expect(set.has('clk100mhz')).toBe(false);
  });

  it('run roles add additional clock signals beyond live roles', () => {
    const live: Record<string, SignalRole> = { clk: 'clock', rst: 'reset' };
    const run: Record<string, SignalRole> = { clk: 'clock', rst: 'reset', clk2: 'clock' };
    const set = buildMergedClockSignals(live, run);
    expect(set.has('clk')).toBe(true);
    expect(set.has('clk2')).toBe(true);
  });

  it('combinational live roles produce empty clockSignals (no sequentiality leak)', () => {
    const live: Record<string, SignalRole> = { a: 'input', b: 'input', y: 'output' };
    const set = buildMergedClockSignals(live, {});
    expect(set.size).toBe(0);
  });

  it('empty live + empty run → empty clockSignals', () => {
    const set = buildMergedClockSignals({}, {});
    expect(set.size).toBe(0);
  });

  it('run roles alone (no live) still populate clockSignals', () => {
    const run: Record<string, SignalRole> = { clk: 'clock', d: 'input', q: 'output' };
    const set = buildMergedClockSignals({}, run);
    expect(set.has('clk')).toBe(true);
  });

  it('VerifySurface: sequential design before first run gets non-empty clockSignals (no-run trust chain)', () => {
    // Full trust chain: sequential circuit → liveSignalRoles has clock → clockSignals populated
    // This mirrors: deriveHasDff(dffCircuit) → true; liveSignalRoles → { CLK100MHZ: clock }
    // → buildMergedClockSignals(liveRoles, {}) → { clk100mhz }
    const liveRolesForSequentialDesign: Record<string, SignalRole> = {
      CLK100MHZ: 'clock',
      RST: 'reset',
      SW0: 'input',
      LED0: 'output',
    };
    const set = buildMergedClockSignals(liveRolesForSequentialDesign, {});
    expect(set.size).toBeGreaterThan(0);
    expect(set.has('clk100mhz')).toBe(true);
    // Trust chain passes: isSequentialRun=true AND clockSignals non-empty before any verify run
  });
});
