// Copyright © 2025 Connor Angiel — RedByte OS Genesis
// Use without permission prohibited.
// Licensed under the RedByte Proprietary License (RPL-1.0). See LICENSE.

/**
 * Circuit-to-Verilog generator
 * 
 * Converts LabProjectV1 / CircuitV1 into synthesizable Verilog HDL
 * with proper wire declarations, module instantiations, and I/O mappings.
 */

import type { CircuitV1, CircuitNode, CircuitConnection, IoMapping } from '@redbyte/rb-utils';
import { getPrimitive, getSupportedNodeTypes } from './primitives';

export interface VerilogGenerationOptions {
  moduleName?: string;
  includeTestbench?: boolean;
  targetBoard?: 'basys3' | 'arty-a7';
}

export interface VerilogOutput {
  verilog: string;
  moduleName: string;
  inputs: string[];
  outputs: string[];
  warnings: string[];
  unsupportedNodes: string[];
}

interface WireInfo {
  name: string;
  driver?: string;
  loads: string[];
}

function compareConnections(a: CircuitConnection, b: CircuitConnection): number {
  const left = `${a.fromNodeId}.${a.fromPin}->${a.toNodeId}.${a.toPin}`;
  const right = `${b.fromNodeId}.${b.fromPin}->${b.toNodeId}.${b.toPin}`;
  return left.localeCompare(right);
}

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values)).sort((a, b) => a.localeCompare(b));
}

/**
 * Generate synthesizable Verilog from CircuitV1
 */
export function circuitToVerilog(
  circuit: CircuitV1,
  ioMapping?: IoMapping,
  options: VerilogGenerationOptions = {}
): VerilogOutput {
  const moduleName = options.moduleName || 'redbyte_circuit';
  const warnings: string[] = [];
  const unsupportedNodes: string[] = [];
  const sortedNodes = [...circuit.nodes].sort((a, b) => a.id.localeCompare(b.id));
  const sortedConnections = [...circuit.connections].sort(compareConnections);

  // Filter out unsupported node types
  const supportedTypes = new Set(getSupportedNodeTypes());
  const supportedNodes = sortedNodes.filter((node) => {
    if (!supportedTypes.has(node.type)) {
      unsupportedNodes.push(`${node.id} (${node.type})`);
      warnings.push(`Node ${node.id} type "${node.type}" not supported for synthesis`);
      return false;
    }
    return true;
  });

  // Build wire map
  const wires = new Map<string, WireInfo>();
  const nodeOutputs = new Map<string, string[]>();

  // Initialize node output tracking
  for (const node of supportedNodes) {
    const primitive = getPrimitive(node.type);
    if (!primitive) continue;
    
    const outputs = primitive.ports.outputs.map((portName) => `${node.id}_${portName}`);
    nodeOutputs.set(node.id, outputs);
    
    for (const wireName of outputs) {
      wires.set(wireName, { name: wireName, loads: [] });
    }
  }

  // Process connections
  for (const conn of sortedConnections) {
    const fromWire = `${conn.fromNodeId}_${conn.fromPin}`;
    const toLoad = `${conn.toNodeId}_${conn.toPin}`;
    
    const wire = wires.get(fromWire);
    if (wire) {
      wire.loads.push(toLoad);
    } else {
      warnings.push(`Connection from ${conn.fromNodeId}.${conn.fromPin} has no driver`);
    }
  }

  // Determine top-level I/O
  const inputs: string[] = [];
  const outputs: string[] = [];

  if (ioMapping) {
    const sortedInputMapping = [...ioMapping.inputs].sort((a, b) => {
      const left = `${a.nodeId}.${a.port}.${a.id}`;
      const right = `${b.nodeId}.${b.port}.${b.id}`;
      return left.localeCompare(right);
    });
    const sortedOutputMapping = [...ioMapping.outputs].sort((a, b) => {
      const left = `${a.nodeId}.${a.port}.${a.id}`;
      const right = `${b.nodeId}.${b.port}.${b.id}`;
      return left.localeCompare(right);
    });

    for (const entry of sortedInputMapping) {
      const wireName = `${entry.nodeId}_${entry.port}`;
      inputs.push(wireName);
    }
    for (const entry of sortedOutputMapping) {
      const wireName = `${entry.nodeId}_${entry.port}`;
      outputs.push(wireName);
    }
  } else {
    // Auto-detect: inputs have no driver, outputs have no loads
    const sortedWireNames = Array.from(wires.keys()).sort((a, b) => a.localeCompare(b));
    for (const wireName of sortedWireNames) {
      const wire = wires.get(wireName);
      if (!wire) continue;
      if (!wire.driver && wire.loads.length > 0) {
        inputs.push(wireName);
      }
      if (wire.driver && wire.loads.length === 0) {
        outputs.push(wireName);
      }
    }
  }

  // Generate Verilog
  let verilog = `// Generated by RedByte FPGA Toolchain\n`;
  verilog += `// Source: LabProjectV1 CircuitV1\n`;
  verilog += `// Deterministic export\n\n`;

  // Module declaration
  verilog += `module ${moduleName} (\n`;
  const ports = [
    ...uniqueSorted(inputs).map((name) => `  input wire ${sanitizeIdentifier(name)}`),
    ...uniqueSorted(outputs).map((name) => `  output wire ${sanitizeIdentifier(name)}`),
  ];
  verilog += ports.join(',\n');
  verilog += `\n);\n\n`;

  // Wire declarations (internal wires only)
  const uniqueInputs = uniqueSorted(inputs);
  const uniqueOutputs = uniqueSorted(outputs);
  const internalWires = Array.from(wires.keys())
    .filter((name) => !uniqueInputs.includes(name) && !uniqueOutputs.includes(name))
    .sort((a, b) => a.localeCompare(b));
  if (internalWires.length > 0) {
    verilog += `  // Internal wires\n`;
    for (const wireName of internalWires) {
      verilog += `  wire ${sanitizeIdentifier(wireName)};\n`;
    }
    verilog += `\n`;
  }

  // Module instantiations
  verilog += `  // Component instantiations\n`;
  for (const node of supportedNodes) {
    const primitive = getPrimitive(node.type);
    if (!primitive) continue;

    const instanceName = `inst_${sanitizeIdentifier(node.id)}`;
    verilog += `  ${primitive.moduleName} ${instanceName} (\n`;

    const connections: string[] = [];
    for (const inputPort of primitive.ports.inputs) {
      const wireName = findDriverForPin(node.id, inputPort, sortedConnections, wires);
      const signalName = wireName ? sanitizeIdentifier(wireName) : '1\'b0';
      connections.push(`    .${inputPort}(${signalName})`);
    }
    for (const outputPort of primitive.ports.outputs) {
      const wireName = `${node.id}_${outputPort}`;
      connections.push(`    .${outputPort}(${sanitizeIdentifier(wireName)})`);
    }

    verilog += connections.join(',\n');
    verilog += `\n  );\n\n`;
  }

  verilog += `endmodule\n`;

  return {
    verilog,
    moduleName,
    inputs: uniqueInputs.map(sanitizeIdentifier),
    outputs: uniqueOutputs.map(sanitizeIdentifier),
    warnings,
    unsupportedNodes,
  };
}

/**
 * Find the wire that drives a given node input pin
 */
function findDriverForPin(
  nodeId: string,
  pinName: string,
  connections: CircuitConnection[],
  wires: Map<string, WireInfo>
): string | null {
  const targetLoad = `${nodeId}_${pinName}`;

  const sortedWireNames = Array.from(wires.keys()).sort((a, b) => a.localeCompare(b));
  for (const wireName of sortedWireNames) {
    const wire = wires.get(wireName);
    if (!wire) continue;
    if (wire.loads.includes(targetLoad)) {
      return wireName;
    }
  }

  // Check connections directly
  const sortedConnections = [...connections].sort(compareConnections);
  for (const conn of sortedConnections) {
    if (conn.toNodeId === nodeId && conn.toPin === pinName) {
      return `${conn.fromNodeId}_${conn.fromPin}`;
    }
  }
  
  return null;
}

/**
 * Sanitize identifiers for Verilog (alphanumeric + underscore only)
 */
function sanitizeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1');
}

/**
 * Generate XDC constraints for Basys3 board from IoMapping
 */
export function generateBasys3Constraints(ioMapping: IoMapping): string {
  let xdc = `# Basys3 Constraints\n`;
  xdc += `# Generated by RedByte FPGA Toolchain\n\n`;

  xdc += `## Clock signal (100 MHz)\n`;
  xdc += `set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk]\n`;
  xdc += `create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]\n\n`;

  if (ioMapping.inputs.length > 0) {
    xdc += `## Switches\n`;
    for (const entry of ioMapping.inputs) {
      if (entry.pin?.startsWith('SW')) {
        const idx = parseInt(entry.pin.slice(2), 10);
        const pins = ['V17', 'V16', 'W16', 'W17', 'W15', 'V15', 'W14', 'W13', 'V2', 'T3', 'T2', 'R3', 'W2', 'U1', 'T1', 'R2'];
        if (idx < pins.length) {
          const wireName = sanitizeIdentifier(`${entry.nodeId}_${entry.port}`);
          xdc += `set_property -dict { PACKAGE_PIN ${pins[idx]}  IOSTANDARD LVCMOS33 } [get_ports ${wireName}]\n`;
        }
      }
    }
    xdc += `\n`;
  }

  if (ioMapping.outputs.length > 0) {
    xdc += `## LEDs\n`;
    for (const entry of ioMapping.outputs) {
      if (entry.pin?.startsWith('LD')) {
        const idx = parseInt(entry.pin.slice(2), 10);
        const pins = ['U16', 'E19', 'U19', 'V19', 'W18', 'U15', 'U14', 'V14', 'V13', 'V3', 'W3', 'U3', 'P3', 'N3', 'P1', 'L1'];
        if (idx < pins.length) {
          const wireName = sanitizeIdentifier(`${entry.nodeId}_${entry.port}`);
          xdc += `set_property -dict { PACKAGE_PIN ${pins[idx]}  IOSTANDARD LVCMOS33 } [get_ports ${wireName}]\n`;
        }
      }
    }
  }

  return xdc;
}

/**
 * Generate constraints file based on board profile
 */
export function generateConstraints(
  ioMapping: IoMapping,
  board: 'basys3' | 'arty-a7' = 'basys3'
): string {
  switch (board) {
    case 'basys3':
      return generateBasys3Constraints(ioMapping);
    case 'arty-a7':
      // TODO: Implement Arty-A7 constraints
      return `# Arty-A7 constraints not yet implemented\n`;
    default:
      return `# Unknown board: ${board}\n`;
  }
}
