#!/usr/bin/env node
/**
 * Demo readiness checker + report generator
 *
 * Runs the full rc:check gate chain and generates a demo-ready verdict.
 * Outputs result to docs/DEMO_READY_REPORT.md
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const REPO_ROOT = process.cwd();
const DEMO_REPORT_PATH = join(REPO_ROOT, 'docs', 'DEMO_READY_REPORT.md');
const PW_REPORT_DIR = join(REPO_ROOT, 'playwright-report');
const BUILD_INFO_PATH = join(REPO_ROOT, 'apps', 'playground', 'dist', 'build.json');

function getBuildInfo() {
  try {
    const data = readFileSync(BUILD_INFO_PATH, 'utf8');
    const info = JSON.parse(data);
    return {
      sha: info.buildSha || 'dev',
      date: info.buildTime ? new Date(info.buildTime).toISOString() : new Date().toISOString(),
    };
  } catch {
    return {
      sha: 'dev',
      date: new Date().toISOString(),
    };
  }
}

function runRcCheck() {
  console.log('📋 Running rc:check gate chain...\n');
  try {
    execSync('pnpm rc:check', {
      stdio: 'inherit',
      cwd: REPO_ROOT,
    });
    return true;
  } catch (error) {
    return false;
  }
}

function generateReport(passed) {
  const buildInfo = getBuildInfo();
  const timestamp = new Date().toISOString();
  
  const report = `# DEMO READY REPORT

Generated: ${timestamp}

## Verdict

${passed ? '✅ **DEMO READY** - All gates passing' : '❌ **NOT READY** - Gates failed'}

## Build Information

- **Build SHA**: ${buildInfo.sha}
- **Build Date**: ${buildInfo.date}
- **Report Generated**: ${timestamp}

## Gate Chain Results

${passed ? `
### rc:check (Build + Unit Tests + E2E Smoke)
- ✅ Playground build succeeded
- ✅ Unit test gates passed (23+ determinism gates)
- ✅ E2E smoke tests passed (4/4 tests)
  - Shell boots to desktop without fatal errors
  - Dashboard and studio apps are registered
  - Export functionality is accessible
  - Submission inspector app is accessible
` : `
### rc:check (Build + Unit Tests + E2E Smoke)
- ❌ One or more gate(s) failed - see terminal output for details
`}

## Reports & Evidence

- **Playwright HTML Report**: \`playwright-report/index.html\`
- **Report Refresh Time**: ${new Date().toLocaleTimeString()}

## Next Steps (Demo Day)

1. Run: \`pnpm demo:ready\`
2. Verify: \`✅ DEMO READY\` verdict in this report
3. Open browser: \`http://127.0.0.1:4173/os\`
4. Screenshot of desktop shell for visual verification

---

*This report is auto-generated by \`pnpm demo:ready\`*
`;

  writeFileSync(DEMO_REPORT_PATH, report, 'utf8');
  console.log(`\n✅ Report written to: ${DEMO_REPORT_PATH}`);
}

async function main() {
  console.log('🚀 Demo Readiness Checker\n');
  console.log(`📄 Report will be written to: ${DEMO_REPORT_PATH}\n`);

  const passed = runRcCheck();
  
  generateReport(passed);

  console.log('\n' + '='.repeat(60));
  console.log('DEMO READY REPORT');
  console.log('='.repeat(60));
  console.log(`\n${passed ? '✅ DEMO READY' : '❌ NOT READY'}`);
  console.log(`\n📖 Full report: file://${DEMO_REPORT_PATH}`);
  console.log(`🎭 Demo URL: http://127.0.0.1:4173/os`);
  console.log(`📊 E2E Report: file://${PW_REPORT_DIR}/index.html`);
  console.log('\n' + '='.repeat(60) + '\n');

  process.exit(passed ? 0 : 1);
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
