import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Modal } from '@redbyte/rb-primitives';
import { VERSION, GIT_SHA, BUILD_DATE, getFullVersionString } from './version';
export const AboutModal = ({ isOpen, onClose }) => {
    return (_jsx(Modal, { isOpen: isOpen, onClose: onClose, title: "About RedByte OS", width: 640, height: 520, children: _jsxs("div", { className: "p-8 space-y-6", style: { color: 'var(--rb-text)' }, children: [_jsxs("div", { className: "text-center pb-4", style: { borderBottom: '1px solid var(--rb-border)' }, children: [_jsxs("div", { className: "flex items-center justify-center gap-2 mb-2", children: [_jsx("div", { className: "h-8 w-8 rounded-lg flex items-center justify-center", style: { background: 'var(--rb-accent)' }, children: _jsx("span", { className: "text-sm font-bold text-white leading-none", children: "R" }) }), _jsx("span", { className: "text-2xl font-semibold", style: { color: 'var(--rb-text)' }, children: "RedByte OS" })] }), _jsx("div", { className: "text-sm font-mono", style: { color: 'var(--rb-text-2)' }, children: getFullVersionString() })] }), _jsxs("div", { className: "grid grid-cols-3 gap-4 p-4 rounded-lg", style: { background: 'var(--rb-surface-1)', border: '1px solid var(--rb-border)' }, children: [_jsxs("div", { children: [_jsx("div", { className: "text-[10px] uppercase tracking-wider font-semibold mb-1", style: { color: 'var(--rb-text-3)' }, children: "Version" }), _jsxs("div", { className: "text-sm font-mono", style: { color: 'var(--rb-text)' }, children: ["v", VERSION] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-[10px] uppercase tracking-wider font-semibold mb-1", style: { color: 'var(--rb-text-3)' }, children: "Build" }), _jsx("div", { className: "text-sm font-mono", style: { color: 'var(--rb-text)' }, children: GIT_SHA.substring(0, 7) })] }), _jsxs("div", { children: [_jsx("div", { className: "text-[10px] uppercase tracking-wider font-semibold mb-1", style: { color: 'var(--rb-text-3)' }, children: "Date" }), _jsx("div", { className: "text-sm font-mono", style: { color: 'var(--rb-text)' }, children: BUILD_DATE })] })] }), _jsx("div", { children: _jsx("p", { className: "text-sm leading-relaxed", style: { color: 'var(--rb-text-2)' }, children: "RedByte OS is a browser-based deterministic operating system for digital logic education. Build, simulate, and verify circuits from basic gates to complete CPUs \u2014 entirely in your browser." }) }), _jsx("div", { className: "space-y-2", children: _jsxs("a", { href: "https://github.com/swaggyp52/redbyte-ui-genesis", target: "_blank", rel: "noopener noreferrer", className: "flex items-center gap-3 p-3 rounded-lg transition-colors", style: {
                            background: 'var(--rb-surface-1)',
                            border: '1px solid var(--rb-border)',
                            color: 'var(--rb-text)',
                        }, children: [_jsx("div", { className: "text-sm font-medium", style: { color: 'var(--rb-text)' }, children: "View on GitHub" }), _jsx("div", { className: "text-xs ml-auto", style: { color: 'var(--rb-text-3)' }, children: "Source code" })] }) }), _jsxs("div", { className: "pt-4 text-center", style: { borderTop: '1px solid var(--rb-border)' }, children: [_jsx("div", { className: "text-xs", style: { color: 'var(--rb-text-3)' }, children: "Copyright \u00A9 2025 Connor Angiel \u2014 RedByte OS Genesis" }), _jsx("div", { className: "text-xs mt-1", style: { color: 'var(--rb-text-3)' }, children: "Licensed under the RedByte Proprietary License (RPL-1.0)" })] })] }) }));
};
