#:schema node_modules/wrangler/config-schema.json
name = "lab3-webapp"
main = "dist/index.html"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
routes = [
  { pattern = "redbyteapps.dev", zone_name = "redbyteapps.dev" },
  { pattern = "redbyte-ui-genesis.pages.dev", zone_name = "pages.dev" }
]
