/**
 * Lab template definitions for the Overview tab "Start from a template" gallery.
 * Each template pre-fills the truth table and shows Basys3 I/O constraints.
 */
export const LAB_TEMPLATES = [
    {
        id: 'blank',
        name: 'Blank Canvas',
        description: 'Start from scratch with an empty truth table.',
        difficulty: 'beginner',
        concept: 'Free exploration',
        hint: 'Good for custom logic or following a handout.',
        basys3Io: '—',
        storeAction: 'reset',
    },
    {
        id: 'and-gate-demo',
        name: 'AND Gate',
        description: '2-input AND: see seg-a light when both switches are 1.',
        difficulty: 'beginner',
        concept: 'Combinational gate basics',
        hint: 'Rows 4-15 are don\'t-cares. Only SW1, SW0 matter.',
        basys3Io: 'SW1-SW0 → seg-a (LD0)',
        storeAction: 'fillAndGate',
    },
    {
        id: 'passthrough',
        name: 'Switch → LED',
        description: '4-bit direct passthrough: SW[i] → seg[i].',
        difficulty: 'beginner',
        concept: 'Wire / buffer mapping',
        hint: 'All 16 rows are valid. seg[4-6] remain off.',
        basys3Io: 'SW3-SW0 → seg[3:0]',
        storeAction: 'fillPassthrough',
    },
    {
        id: 'parity-bit',
        name: 'Parity Generator',
        description: '3-bit even parity: seg-a = XOR(SW2, SW1, SW0).',
        difficulty: 'core',
        concept: 'XOR logic, error detection',
        hint: 'Only SW2-SW0 matter; rows 8-15 are don\'t-cares.',
        basys3Io: 'SW2-SW0 → seg-a (parity out)',
        storeAction: 'fillParityBit',
    },
    {
        id: 'standard-7seg',
        name: 'Seven-Segment 0–9',
        description: 'Standard digits 0-9, rows 10-15 are don\'t-cares.',
        difficulty: 'core',
        concept: 'Active-low 7-seg encoding, don\'t-cares',
        hint: 'The canonical lab exercise. Use K-Maps to simplify.',
        basys3Io: 'SW3-SW0 → seg[6:0]',
        storeAction: 'fillStandardDigits',
    },
    {
        id: 'hex-display',
        name: 'Hex Display 0–F',
        description: 'Full 16-digit hex display including A-F.',
        difficulty: 'core',
        concept: 'Complete combinational mapping, no don\'t-cares',
        hint: 'No simplification from don\'t-cares — 16 fully defined rows.',
        basys3Io: 'SW3-SW0 → seg[6:0]',
        storeAction: 'fillHexDigits',
    },
];
