/**
 * Shared Basys3 XDC pin constants for Lab 3.
 * Single source of truth used by both verilog.tsx (export ZIP)
 * and circuitToVhdl.ts (HDL preview).
 */
export const BASYS3_SWITCH_PINS = {
    'B[0]': 'V17',
    'B[1]': 'V16',
    'B[2]': 'W16',
    'B[3]': 'W17',
};
export const BASYS3_SEG_PINS = {
    'seg[0]': 'W7',
    'seg[1]': 'W6',
    'seg[2]': 'U8',
    'seg[3]': 'V8',
    'seg[4]': 'U5',
    'seg[5]': 'V5',
    'seg[6]': 'U7',
};
export const BASYS3_ANODE_PINS = {
    'AN[0]': 'U2',
    'AN[1]': 'U4',
    'AN[2]': 'V4',
    'AN[3]': 'W4',
};
/**
 * Generate the full XDC constraints file content for the standard
 * ssd_driver entity (4-bit switch input + 7-segment output + anodes + DP).
 */
export function generateXdcString() {
    const pinLines = (pins) => Object.entries(pins)
        .map(([port, pkg]) => `set_property PACKAGE_PIN ${pkg} [get_ports {${port}}]\n` +
        `set_property IOSTANDARD LVCMOS33 [get_ports {${port}}]`)
        .join('\n');
    return `## Basys3 Constraints - Lab 3 Seven-Segment Display Driver
## Generated by RedByte IDE

# 4-bit switch inputs (SW3=MSB, SW0=LSB)
${pinLines(BASYS3_SWITCH_PINS)}

# 7-segment outputs (active-low: 0 = lit)
${pinLines(BASYS3_SEG_PINS)}

# Anode enables (AN[0] = rightmost digit)
${pinLines(BASYS3_ANODE_PINS)}

# Decimal point (disabled - tied high in top module)
set_property PACKAGE_PIN V7 [get_ports DP]
set_property IOSTANDARD LVCMOS33 [get_ports DP]
`;
}
