import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import LogicGatePlayground from '../components/examples/LogicGatePlayground';
import CounterCircuit from '../components/examples/CounterCircuit';
import WaveformViewer from '../components/examples/WaveformViewer';
import { Link as RouterLink } from 'react-router-dom';
const Link = RouterLink;
export default function Labs() {
    return (_jsx("div", { className: "py-20 bg-zinc-950 min-h-screen text-zinc-100", style: { fontFamily: '"Geist", sans-serif' }, children: _jsxs("div", { className: "container mx-auto px-6 max-w-6xl", children: [_jsxs("div", { className: "max-w-2xl mb-16", children: [_jsx("h1", { className: "text-4xl md:text-5xl font-bold tracking-tight mb-6", children: "Lab Library" }), _jsxs("p", { className: "text-xl text-zinc-400 leading-relaxed", children: ["Standardized lab modules designed for the RedByte curriculum. ", _jsx("br", {}), "Download to run offline or preview instantly in the browser."] })] }), _jsxs("div", { className: "grid md:grid-cols-2 gap-8 mb-20", children: [_jsx(LabCard, { id: "01", title: "Combinational Logic: Adder", desc: "Design a 4-bit ripple carry adder using basic logic gates. Verify truth tables and propagation delay.", tags: ['Gates', 'Arithmetic', 'Combinational'], downloadUrl: "/labs/lab01-adder.rbx.zip", previewComponent: _jsx(LogicGatePlayground, {}) }), _jsx(LabCard, { id: "02", title: "Sequential Logic: 4-Bit Counter", desc: "Build a synchronous up/down counter with reset and enable. Analyze clock edges and state transitions.", tags: ['Flip-Flops', 'State Machines', 'Sequential'], downloadUrl: "/labs/lab02-counter.rbx.zip", previewComponent: _jsx(CounterCircuit, {}) })] }), _jsxs("div", { className: "border border-zinc-800 rounded-xl bg-zinc-900/30 p-8", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h2", { className: "text-2xl font-bold mb-2", children: "Waveform Analysis" }), _jsx("p", { className: "text-zinc-400", children: "All labs include the integrated 16-channel logic analyzer." })] }), _jsx(WaveformViewer, {})] })] }) }));
}
const LabCard = ({ id, title, desc, tags, downloadUrl, previewComponent }) => (_jsxs("div", { className: "bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden hover:border-zinc-700 transition-colors flex flex-col", children: [_jsxs("div", { className: "h-64 bg-zinc-950 border-b border-zinc-800 relative group overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 flex items-center justify-center p-4", children: previewComponent }), _jsxs("div", { className: "absolute top-4 left-4 bg-zinc-900/80 backdrop-blur px-2 py-1 rounded text-xs font-mono text-zinc-400 border border-zinc-700", children: ["LAB-", id] })] }), _jsxs("div", { className: "p-6 flex-1 flex flex-col", children: [_jsx("h3", { className: "text-xl font-bold text-white mb-2", children: title }), _jsx("p", { className: "text-sm text-zinc-400 mb-6 leading-relaxed flex-1", children: desc }), _jsx("div", { className: "flex flex-wrap gap-2 mb-6", children: tags.map((t) => (_jsx("span", { className: "px-2 py-1 rounded text-[10px] font-medium uppercase tracking-wider bg-zinc-800 text-zinc-400", children: t }, t))) }), _jsxs("div", { className: "flex items-center gap-3 mt-auto", children: [_jsx("button", { className: "flex-1 py-2.5 bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold rounded-lg transition-colors shadow-lg shadow-blue-900/20", children: "Download Lab Bundle" }), _jsx("button", { className: "px-4 py-2.5 border border-zinc-700 hover:bg-zinc-800 text-zinc-300 text-sm font-medium rounded-lg transition-colors", children: "Preview" })] })] })] }));
