import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
const Home = () => {
    return (_jsxs("div", { style: { fontFamily: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' }, children: [_jsxs("section", { className: "relative overflow-hidden border-b border-zinc-800", children: [_jsx("div", { className: "absolute inset-0", style: {
                            background: 'linear-gradient(145deg, #09090B 0%, #18181B 50%, #09090B 100%)',
                        } }), _jsxs("div", { className: "relative container mx-auto px-6 py-24 md:py-32 max-w-5xl text-center", children: [_jsxs("div", { className: "inline-flex items-center gap-2 px-3 py-1 mb-6 rounded-full border border-zinc-800 bg-zinc-900/50 backdrop-blur-sm", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-green-500 animate-pulse" }), _jsx("span", { className: "text-[10px] font-medium text-zinc-400 tracking-wider uppercase", children: "v1.0.0 Stable Release" })] }), _jsxs("h1", { className: "text-5xl md:text-7xl font-bold tracking-tight text-white mb-6 leading-[1.05]", children: ["Digital Logic,", _jsx("br", {}), _jsx("span", { className: "text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-cyan-400", children: "Redefined." })] }), _jsxs("p", { className: "text-lg md:text-xl text-zinc-400 mb-10 leading-relaxed max-w-2xl mx-auto", children: ["The operating system for hands-on hardware labs. ", _jsx("br", { className: "hidden md:block" }), "Design circuits, simulate IO, and verify on real FPGAs\u2014all in one shell."] }), _jsxs("div", { className: "flex flex-col sm:flex-row items-center justify-center gap-4 mb-20", children: [_jsx(Link, { to: "/download", className: "px-8 py-3.5 rounded-lg font-semibold text-sm text-white bg-blue-600 hover:bg-blue-500 transition-all shadow-lg shadow-blue-500/20", children: "Download RedByte OS" }), _jsx(Link, { to: "/demo", className: "px-8 py-3.5 rounded-lg font-semibold text-sm text-zinc-300 border border-zinc-700 hover:border-zinc-600 hover:text-white transition-all bg-zinc-900/50", children: "Try Live Demo" })] }), _jsxs("div", { className: "relative rounded-xl border border-zinc-800 bg-zinc-900/50 shadow-2xl overflow-hidden aspect-video max-w-4xl mx-auto group", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-zinc-950 via-transparent to-transparent z-10 pointer-events-none" }), _jsx("div", { className: "absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-blue-500/50 to-transparent" }), _jsxs("div", { className: "absolute top-0 inset-x-0 h-8 bg-zinc-950/80 border-b border-zinc-800 flex items-center px-4 gap-2 z-20", children: [_jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-red-500/20 border border-red-500/50" }), _jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-amber-500/20 border border-amber-500/50" }), _jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-green-500/20 border border-green-500/50" }), _jsx("div", { className: "ml-4 text-[10px] font-mono text-zinc-500 flex-1 text-center", children: "lab-01-adder.rbl" })] }), _jsx("img", { src: "/screenshot-lab.png", alt: "RedByte Interface", className: "w-full h-full object-cover opacity-90 group-hover:scale-[1.02] transition-transform duration-700", onError: (e) => {
                                            // Fallback if image missing
                                            e.currentTarget.style.display = 'none';
                                        } }), _jsx("div", { className: "w-full h-full flex items-center justify-center text-zinc-700 font-mono text-sm", children: "[ Interactive Lab Environment Preview ]" })] })] })] }), _jsx("section", { className: "py-24 bg-zinc-950 border-b border-zinc-800", children: _jsx("div", { className: "container mx-auto px-6 max-w-6xl", children: _jsxs("div", { className: "grid md:grid-cols-3 gap-8", children: [_jsx(FeatureCard, { icon: "\u26A1", title: "Unified Simulation", desc: "Simulate circuits with real-time feedback. Toggle switches, watch LEDs, and verify logic before touching hardware." }), _jsx(FeatureCard, { icon: "\uD83D\uDD0C", title: "Hardware Verified", desc: "One-click bridge to Basys3 FPGAs. Run your virtual circuit on physical silicon with zero configuration." }), _jsx(FeatureCard, { icon: "\uD83D\uDCE6", title: "Evidence Capsules", desc: "Export verifiable .rbx.zip snapshots containing circuit state, simulation traces, and hardware logs for grading." })] }) }) }), _jsx("section", { className: "py-24 bg-zinc-900/30", children: _jsxs("div", { className: "container mx-auto px-6 max-w-4xl text-center", children: [_jsx("h2", { className: "text-3xl font-bold text-white mb-12", children: "From Logic to Lab." }), _jsxs("div", { className: "grid md:grid-cols-4 gap-4 relative", children: [_jsx("div", { className: "hidden md:block absolute top-8 left-0 w-full h-0.5 bg-zinc-800 -z-10" }), _jsx(Step, { number: "01", title: "Design", desc: "Drag & drop gates" }), _jsx(Step, { number: "02", title: "Simulate", desc: "Verify behavior" }), _jsx(Step, { number: "03", title: "Flash", desc: "Push to FPGA" }), _jsx(Step, { number: "04", title: "Submit", desc: "Export Evidence" })] })] }) }), _jsxs("section", { className: "py-20 border-t border-zinc-800 bg-zinc-950 text-center", children: [_jsx("h2", { className: "text-2xl font-bold text-white mb-6", children: "Ready to upgrade your lab?" }), _jsx(Link, { to: "/download", className: "inline-flex px-8 py-3 rounded-lg font-semibold text-sm text-zinc-950 bg-white hover:bg-zinc-200 transition-colors", children: "Get Started Now" })] })] }));
};
const FeatureCard = ({ icon, title, desc }) => (_jsxs("div", { className: "p-6 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-colors", children: [_jsx("div", { className: "text-3xl mb-4", children: icon }), _jsx("h3", { className: "text-lg font-bold text-white mb-2", children: title }), _jsx("p", { className: "text-sm text-zinc-400 leading-relaxed", children: desc })] }));
const Step = ({ number, title, desc }) => (_jsxs("div", { className: "flex flex-col items-center relative z-10", children: [_jsx("div", { className: "w-16 h-16 rounded-full bg-zinc-900 border border-zinc-800 flex items-center justify-center mb-4 text-zinc-500 font-mono font-bold text-lg shadow-lg", children: number }), _jsx("div", { className: "text-base font-bold text-white mb-1", children: title }), _jsx("div", { className: "text-xs text-zinc-500", children: desc })] }));
export default Home;
