import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function Download() {
    return (_jsx("div", { className: "bg-zinc-950 min-h-screen text-zinc-100", style: { fontFamily: '"Geist", sans-serif' }, children: _jsxs("div", { className: "container mx-auto px-6 py-20 max-w-5xl text-center", children: [_jsx("h1", { className: "text-5xl md:text-6xl font-black text-white mb-6 tracking-tight", children: "Get RedByte OS" }), _jsxs("p", { className: "text-xl text-zinc-400 mb-16 max-w-2xl mx-auto leading-relaxed", children: ["The all-in-one lab environment. ", _jsx("br", {}), "Open source, offline-first, and privacy-respecting."] }), _jsxs("div", { className: "bg-zinc-900/50 p-10 rounded-2xl border border-zinc-800 inline-block text-left relative overflow-hidden group max-w-md w-full shadow-2xl", children: [_jsx("div", { className: "absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-cyan-500" }), _jsxs("div", { className: "flex items-start justify-between mb-8", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-white mb-1", children: "Windows Bundle" }), _jsx("div", { className: "text-sm text-zinc-500 font-mono", children: "v1.0.0-stable \u2022 x64" })] }), _jsx("div", { className: "text-4xl", children: "\uD83E\uDE9F" })] }), _jsx("button", { className: "w-full py-4 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-bold text-lg shadow-lg mb-4 transition-all hover:shadow-blue-500/20 active:scale-[0.98]", children: "Download Explorer (.zip)" }), _jsx("p", { className: "text-xs text-center text-zinc-500 font-mono", children: "SHA256: e3b0c442... \u2022 145 MB" })] }), _jsxs("div", { className: "mt-12 grid md:grid-cols-3 gap-6 max-w-3xl mx-auto", children: [_jsx(PlatformCard, { icon: "\uD83C\uDF4E", title: "macOS", status: "Coming Soon" }), _jsx(PlatformCard, { icon: "\uD83D\uDC27", title: "Linux", status: "Build from Source", link: "https://github.com/swaggyp52/redbyte-ui-genesis" }), _jsx(PlatformCard, { icon: "\uD83C\uDF10", title: "Web Demo", status: "Try Instantly", link: "/demo", active: true })] }), _jsxs("div", { className: "mt-20 grid md:grid-cols-3 gap-8 text-left border-t border-zinc-900 pt-16", children: [_jsx(Feature, { title: "Portable", desc: "No administrator rights required. Just unzip and run on any lab computer." }), _jsx(Feature, { title: "Air-Gapped Ready", desc: "Zero internet dependency after download. Perfect for secure exam environments." }), _jsx(Feature, { title: "Everything Included", desc: "Bundled with Node.js runtime, hardware drivers, and documentation." })] })] }) }));
}
;
const PlatformCard = ({ icon, title, status, link, active }) => {
    const content = (_jsxs("div", { className: `p-4 rounded-lg border ${active ? 'bg-zinc-900 border-zinc-700' : 'bg-zinc-950 border-zinc-900'} flex items-center gap-4 transition-colors hover:border-zinc-700`, children: [_jsx("div", { className: "text-2xl", children: icon }), _jsxs("div", { className: "text-left", children: [_jsx("div", { className: "font-bold text-sm text-zinc-200", children: title }), _jsx("div", { className: `text-xs ${active ? 'text-green-400' : 'text-zinc-500'}`, children: status })] })] }));
    return link ? (_jsx(Link, { to: link.startsWith('http') ? '' : link, onClick: link.startsWith('http') ? () => window.open(link) : undefined, children: content })) : content;
};
const Feature = ({ title, desc }) => (_jsxs("div", { className: "block", children: [_jsxs("h3", { className: "font-bold text-zinc-200 mb-2 flex items-center gap-2", children: [_jsx("span", { className: "w-1.5 h-1.5 rounded-full bg-zinc-600" }), " ", title] }), _jsx("p", { className: "text-sm text-zinc-400 leading-relaxed pl-3.5 border-l border-zinc-800", children: desc })] }));
