export {
  AndGateIcon,
  BufferIcon,
  DockIcon,
  IconProps,
  NandGateIcon,
  NorGateIcon,
  NotGateIcon,
  OrGateIcon,
  TaskbarIcon,
  WindowCloseIcon,
  WindowMaximizeIcon,
  WindowMinimizeIcon,
  XorGateIcon,
} from './icons';
